// app/src/pages/journal-2-0/a11y/contrastExpectedFailures.js
//
// A5's audit record (wave 8, lane 8A): the Notebook contrast failures that a
// Notebook-CSS token switch CANNOT fix, each tied to the ruling it waits on, and
// the fixable failures that sit in another lane's stylesheet. Written once from
// the measured rows and then held to them: notebookContrast.test.js fails on an
// entry with no ruling id, on an entry whose measured ratio moved, and on an
// entry that passes now (fixed -- remove it).

/** The rulings these wait on -- the PROPOSED fix is lane 8A's; the controller rules. */
export const RULINGS = Object.freeze({
  'D-A4-1': "Danger text: --loss (and --color-danger, which is --loss) reads 4.01:1 on --bg-elevated in the dark theme, 3.63-3.73:1 on its own --loss-bg tint, and 4.21-4.30:1 on that tint in oled -- under 4.5:1 for the 10-13px text it is used at. No existing token passes in all three themes (--ut-red-bright is 4.58:1 dark but 3.3:1 light). Proposed: lift the dark/oled --loss lightness in tokens.css (the light theme already passes).",
  'D-A4-2': "Success text: --gain on its own --gain-bg tint reads 4.42:1 in the light theme. Proposed: darken the light --gain a step in tokens.css.",
  'D-A4-3': "Input boundaries: every Notebook input, select and textarea draws its edge in --border, 1.18:1 (dark) against the page -- WCAG 1.4.11 asks 3:1 for the visual information that identifies a control. --border-accent does not reach it either. Proposed: an input-edge value in tokens.css, or a ruling that these fields are identified by their label and placeholder instead.",
})

export const EXPECTED_FAILURES = Object.freeze([
  { pair: "components/ModalShell.module.css .errorBanner [text color]", theme: 'dark', measured: 3.73, rulingId: 'D-A4-1' },
  { pair: "components/ModalShell.module.css .errorBanner [text color]", theme: 'oled', measured: 4.30, rulingId: 'D-A4-1' },
  { pair: "components/PersonalApiCard.module.css .alert [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/AskPanel.module.css .errorMsg [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/BulkActionBar.module.css .danger [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/CaptureConnectPage.module.css .error [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/FolderSidebar.module.css .iconBtn:hover [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/FrozenList.module.css .down [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/HeroImagePicker.module.css .error [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/NoteBoardView.module.css .error [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/NoteCalendarView.module.css .error [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/NoteEditorPage.module.css .deleteBtn [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/NoteEditorPage.module.css .lockBannerError [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/NoteHistoryPanel.module.css .diffRemoved [text color]", theme: 'dark', measured: 3.73, rulingId: 'D-A4-1' },
  { pair: "components/notebook/NoteHistoryPanel.module.css .diffRemoved [text color]", theme: 'oled', measured: 4.30, rulingId: 'D-A4-1' },
  { pair: "components/notebook/NoteHistoryPanel.module.css .statusErr [text color]", theme: 'dark', measured: 3.73, rulingId: 'D-A4-1' },
  { pair: "components/notebook/NoteHistoryPanel.module.css .statusErr [text color]", theme: 'oled', measured: 4.30, rulingId: 'D-A4-1' },
  { pair: "components/notebook/NoteLinkView.module.css .badge [text color]", theme: 'dark', measured: 3.73, rulingId: 'D-A4-1' },
  { pair: "components/notebook/NoteLinkView.module.css .badge [text color]", theme: 'oled', measured: 4.30, rulingId: 'D-A4-1' },
  { pair: "components/notebook/NoteMenuActions.module.css .statusError [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/NoteShareControls.module.css .danger [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/NoteTasksView.module.css .groupOverdue [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/PropertiesSection.module.css .error [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/RelationPropertyValue.module.css .hint [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/ResearchHome.module.css .status_invalidated [text color]", theme: 'dark', measured: 3.73, rulingId: 'D-A4-1' },
  { pair: "components/notebook/ResearchHome.module.css .status_invalidated [text color]", theme: 'oled', measured: 4.30, rulingId: 'D-A4-1' },
  { pair: "components/notebook/SavedViewEditor.module.css .error [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/TableToolbar.module.css .danger [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/TemplatePicker.module.css .memberError [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/TemplatePicker.module.css .miniDanger [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/ThesisReviewSection.module.css .error [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/ThesisReviewSection.module.css .opposes [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/ThesisSection.module.css .error [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/ThesisSection.module.css .opposes [text color]", theme: 'dark', measured: 3.73, rulingId: 'D-A4-1' },
  { pair: "components/notebook/ThesisSection.module.css .opposes [text color]", theme: 'oled', measured: 4.30, rulingId: 'D-A4-1' },
  { pair: "components/notebook/ThesisSection.module.css .removeBtn:hover [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/WritingHelpPanel.module.css .error [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/export/ExportDialog.module.css .errorIcon [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/import/ImportWizard.module.css .errorIcon, .crashIcon [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "components/notebook/import/ImportWizard.module.css .failures [text color]", theme: 'dark', measured: 4.01, rulingId: 'D-A4-1' },
  { pair: "tabs/NotebookTab.module.css .error [text color]", theme: 'dark', measured: 3.63, rulingId: 'D-A4-1' },
  { pair: "tabs/NotebookTab.module.css .error [text color]", theme: 'oled', measured: 4.21, rulingId: 'D-A4-1' },
  { pair: "components/notebook/NoteHistoryPanel.module.css .diffAdded [text color]", theme: 'light', measured: 4.42, rulingId: 'D-A4-2' },
  { pair: "components/notebook/NoteHistoryPanel.module.css .statusOk [text color]", theme: 'light', measured: 4.42, rulingId: 'D-A4-2' },
  { pair: "components/notebook/ResearchHome.module.css .status_active [text color]", theme: 'light', measured: 4.42, rulingId: 'D-A4-2' },
  { pair: "components/notebook/ThesisSection.module.css .supports [text color]", theme: 'light', measured: 4.42, rulingId: 'D-A4-2' },
  { pair: "components/notebook/TickerResearchWorkspace.module.css .chip [text color]", theme: 'light', measured: 4.42, rulingId: 'D-A4-2' },
  { pair: "components/notebook/TickerResearchWorkspace.module.css .tradeChip [text color]", theme: 'light', measured: 4.42, rulingId: 'D-A4-2' },
  { pair: "components/InboundEmailCard.module.css .tokenInput [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/InboundEmailCard.module.css .tokenInput [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/InboundEmailCard.module.css .tokenInput [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/ModalShell.module.css .prefixInput [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/ModalShell.module.css .prefixInput [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/ModalShell.module.css .prefixInput [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/ModalShell.module.css .textInput, .numberInput, .select, .textarea, .numberInputInner [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/ModalShell.module.css .textInput, .numberInput, .select, .textarea, .numberInputInner [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/ModalShell.module.css .textInput, .numberInput, .select, .textarea, .numberInputInner [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/PersonalApiCard.module.css .labelInput, .tokenInput [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/PersonalApiCard.module.css .labelInput, .tokenInput [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/PersonalApiCard.module.css .labelInput, .tokenInput [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/AskPanel.module.css .input [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/AskPanel.module.css .input [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/AskPanel.module.css .input [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/BulkActionBar.module.css .moveSelect [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/BulkActionBar.module.css .moveSelect [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/BulkActionBar.module.css .moveSelect [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/CaptureDialog.module.css .input, .textarea [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/CaptureDialog.module.css .input, .textarea [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/CaptureDialog.module.css .input, .textarea [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/FolderSidebar.module.css .searchFilterField input, .searchFilterField select [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/FolderSidebar.module.css .searchFilterField input, .searchFilterField select [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/FolderSidebar.module.css .searchFilterField input, .searchFilterField select [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/FolderSidebar.module.css .searchInput [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/FolderSidebar.module.css .searchInput [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/FolderSidebar.module.css .searchInput [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/FolderSidebar.module.css .tagFilterInput [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/FolderSidebar.module.css .tagFilterInput [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/FolderSidebar.module.css .tagFilterInput [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteBoardView.module.css .groupSelect, .move [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteBoardView.module.css .groupSelect, .move [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteBoardView.module.css .groupSelect, .move [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteCalendarView.module.css .bySelect [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteCalendarView.module.css .bySelect [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteCalendarView.module.css .bySelect [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteEditorPage.module.css .fontSelect, .fontSizeSelect [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteEditorPage.module.css .fontSelect, .fontSizeSelect [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteEditorPage.module.css .fontSelect, .fontSizeSelect [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteEditorPage.module.css .headerSelect, .headerInput [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteEditorPage.module.css .headerSelect, .headerInput [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteEditorPage.module.css .headerSelect, .headerInput [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteMenuActions.module.css .templateInput [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteMenuActions.module.css .templateInput [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteMenuActions.module.css .templateInput [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteShareControls.module.css .field, .select [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteShareControls.module.css .field, .select [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteShareControls.module.css .field, .select [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteTimelineView.module.css .control select [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteTimelineView.module.css .control select [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/NoteTimelineView.module.css .control select [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/PropertiesSection.module.css .input, .select [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/PropertiesSection.module.css .input, .select [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/PropertiesSection.module.css .input, .select [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/PropertiesSection.module.css .newPropInput, .newPropType [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/PropertiesSection.module.css .newPropInput, .newPropType [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/PropertiesSection.module.css .newPropInput, .newPropType [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/SavedViewEditor.module.css .input [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/SavedViewEditor.module.css .input [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/SavedViewEditor.module.css .input [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/TagSuggestInput.module.css .input [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/TagSuggestInput.module.css .input [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/TagSuggestInput.module.css .input [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/TemplatePicker.module.css .dailyPick select [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/TemplatePicker.module.css .dailyPick select [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/TemplatePicker.module.css .dailyPick select [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/TemplatePicker.module.css .renameInput [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/TemplatePicker.module.css .renameInput [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/TemplatePicker.module.css .renameInput [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/ThesisReviewSection.module.css .dateInput [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/ThesisReviewSection.module.css .dateInput [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/ThesisReviewSection.module.css .dateInput [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/ThesisReviewSection.module.css .textarea [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/ThesisReviewSection.module.css .textarea [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/ThesisReviewSection.module.css .textarea [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/ThesisSection.module.css .searchInput [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/ThesisSection.module.css .searchInput [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/ThesisSection.module.css .searchInput [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/WidgetEmbedView.module.css .toolSelect [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/WidgetEmbedView.module.css .toolSelect [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/WidgetEmbedView.module.css .toolSelect [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/WidgetPalette.module.css .symInput, .dayInput [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/WidgetPalette.module.css .symInput, .dayInput [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/WidgetPalette.module.css .symInput, .dayInput [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "components/notebook/import/ImportWizard.module.css .destSelect [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "components/notebook/import/ImportWizard.module.css .destSelect [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "components/notebook/import/ImportWizard.module.css .destSelect [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
  { pair: "tabs/NotebookTab.module.css .sortSelect [ui-input-border border]", theme: 'dark', measured: 1.18, rulingId: 'D-A4-3' },
  { pair: "tabs/NotebookTab.module.css .sortSelect [ui-input-border border]", theme: 'oled', measured: 1.13, rulingId: 'D-A4-3' },
  { pair: "tabs/NotebookTab.module.css .sortSelect [ui-input-border border]", theme: 'light', measured: 1.16, rulingId: 'D-A4-3' },
])

/** Fixable, but in another lane's stylesheet this wave -- that lane's to make. */
export const OTHER_LANES = Object.freeze([
  { pair: "components/notebook/NoteExportControls.module.css .item:focus-visible [ui-focus box-shadow]", theme: 'light', measured: 1.72, lane: '8C', fix: "box-shadow: 0 0 0 2px var(--ut-gold) -- the translucent --focus-ring is 1.72:1 on the light theme" },
  { pair: "components/notebook/export/ExportDialog.module.css .option:focus-within [ui-focus box-shadow]", theme: 'light', measured: 1.72, lane: '8C', fix: "box-shadow: 0 0 0 2px var(--ut-gold) -- the translucent --focus-ring is 1.72:1 on the light theme" },
])
