"""APPEND one row to the barstate daily timeline. Never overwrites.

⭐⭐ WHY A TIMELINE AND NOT A RULING. On 2026-09-10 at 16:17:58 ET --
eighteen minutes AFTER the NYSE close -- ``UCTPROBE_BARSTATE_FULL`` read
``isrealtime = 1`` and ``isconfirmed = 0`` on the newest DAILY bar. That is one
instant, and one instant cannot tell two hypotheses apart:

  CALENDAR-CLOSED   the vendor confirms a daily bar at the scheduled close, and
                    16:17 should already have been ``isconfirmed = 1``. If that
                    is right, our seam and the vendor disagree about WHEN a bar
                    settles, and the tri-state we serve is early.

  VENDOR-LATE       the vendor keeps a daily bar ``isrealtime`` until some later
                    event -- the post-market close at 20:00 ET, the next
                    session's open, or a settlement feed. If that is right, our
                    seam is fine and the two simply mean different things by
                    "closed", which is a documentation problem, not a defect.

⛔ THE TWO ARE INDISTINGUISHABLE FROM ANY NUMBER OF READINGS INSIDE ONE
AFTERNOON. They are separated by rows taken AFTER 20:00 ET and BEFORE the next
09:30 ET, and by nothing else. So this file collects instants and refuses to
conclude: the ruling waits for at least one post-20:00 row and one pre-open row.

⚠️ THE CHART'S SESSION SETTING IS PART OF THE READING, NOT CONTEXT. ``regular``
and ``extended`` are different questions about the same symbol, and a row that
does not say which one was on cannot be compared with a row that had the other.
It is read FROM THE PAGE, never assumed.

⛔ SESSION STATE IS DERIVED THROUGH ``scheduled_close_seconds``, THE SAME
FUNCTION ``bar_close_state`` USES. Writing a second "is the market open"
here would put a second authority on the one question this file exists to
compare against -- and the two would drift on exactly the holiday or half-day
where the answer matters.

USAGE (append one row from a browser reading)::

    python tools/visual_conformance/append_barstate_timeline.py \\
        --instant-utc 2026-09-10T20:17:58Z --tf D \\
        --newest-bar-unix 1789047000 --chart-session regular \\
        --isrealtime 1 --isconfirmed 0 --ishistory 0 --islast 1 \\
        --islastconfirmedhistory 0 --isnew 0 \\
        --note "pre-directive reading"
"""
from __future__ import annotations

import argparse
import datetime
import io
import json
import os
import pathlib
import sys
import zoneinfo

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from api.services.indicator_compute import scheduled_close_seconds  # noqa: E402
from api.services.nyse_calendar import (  # noqa: E402
    NYSE_EARLY_CLOSES_YYYYMMDD,
    NYSE_HOLIDAYS_YYYYMMDD,
)

ET = zoneinfo.ZoneInfo("America/New_York")
OUT = ROOT / "tests" / "fixtures" / "vendor" / "barstate-daily-timeline.json"

HEADER = {
    "_": "⭐⭐ APPEND-ONLY. Every browser run adds one row; nothing here is ever rewritten.",
    "_recorder": ("⛔ GENERATED by tools/visual_conformance/append_barstate_timeline.py. "
                  "Add rows by running that program against a live reading; do not hand-edit "
                  "numbers here."),
    "_the_question": (
        "⭐⭐ ONE READING CANNOT SETTLE THIS. At 16:17:58 ET on 2026-09-10 -- 18 minutes after "
        "the NYSE close -- the newest DAILY bar read isrealtime=1, isconfirmed=0. Two "
        "hypotheses fit that equally well and are separated only by rows taken at other times "
        "of day: CALENDAR-CLOSED (the vendor should have confirmed at 16:00, so our seam and "
        "the vendor disagree about when a bar settles) versus VENDOR-LATE (the vendor holds a "
        "daily bar realtime until a later event, so the two simply mean different things by "
        "'closed'). ⛔ NO RULING UNTIL there is at least one row after 20:00 ET and one row "
        "before 09:30 ET."),
    "_how_to_read_a_row": (
        "`session` is DERIVED through scheduled_close_seconds -- the same function bar_close_state "
        "uses -- so this file and the seam can never disagree about the calendar. "
        "`ourSeamSaysForming` is what OUR tri-state would answer at this instant; "
        "`vendorIsRealtime` is what the vendor's own barstate answered. When those two differ, "
        "the row is the evidence."),
    "_chart_session_matters": (
        "⚠️ `chartSession` is READ FROM THE PAGE. 'regular' and 'extended' are different questions "
        "about the same symbol; a row without it cannot be compared with a row that had the other."),
    "rows": [],
}


def _session_facts(now_unix: float, newest_unix: float, tf: str) -> dict:
    """What the CALENDAR says about this instant, via the seam's own authority."""
    close = scheduled_close_seconds(newest_unix, tf,
                                    NYSE_HOLIDAYS_YYYYMMDD, NYSE_EARLY_CLOSES_YYYYMMDD)
    et = datetime.datetime.fromtimestamp(now_unix, ET)
    ymd = int(et.strftime("%Y%m%d"))
    return {
        "etDate": et.strftime("%Y-%m-%d"),
        "etClock": et.strftime("%H:%M:%S"),
        "isNyseHoliday": ymd in NYSE_HOLIDAYS_YYYYMMDD,
        "isNyseEarlyClose": ymd in NYSE_EARLY_CLOSES_YYYYMMDD,
        "scheduledCloseUnix": close,
        "scheduledCloseET": (datetime.datetime.fromtimestamp(close, ET).isoformat()
                             if close is not None else None),
        "secondsPastScheduledClose": (round(now_unix - close) if close is not None else None),
        "ourSeamSaysForming": (None if close is None else bool(close > now_unix)),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--instant-utc", required=True, help="ISO instant of the READING")
    ap.add_argument("--tf", default="D")
    ap.add_argument("--newest-bar-unix", type=float, required=True)
    ap.add_argument("--chart-session", required=True, choices=["regular", "extended"],
                    help="READ FROM THE PAGE, never assumed")
    ap.add_argument("--arrival", required=True, choices=["watched-form", "late"],
                    help=("⛔ LOAD-BEARING, NOT CONTEXT. `barstate-viewer-dependent-on-vendor` "
                          "measured that TradingView's flags on a CLOSED bar depend on whether "
                          "the viewer watched it form. So a row from a chart that was open all "
                          "session and a row from a freshly-loaded one are DIFFERENT READINGS, "
                          "and a timeline that does not say which is a confound wearing a "
                          "series. 'late' means the document was created after the bar closed "
                          "— prove it with performance.timeOrigin, not by intent."))
    for f in ("isrealtime", "isconfirmed", "ishistory", "islast",
              "islastconfirmedhistory", "isnew"):
        ap.add_argument(f"--{f}", type=int, required=True)
    ap.add_argument("--symbol", default="AMEX:SPY")
    ap.add_argument("--study", default="UCTPROBE_BARSTATE_FULL")
    ap.add_argument("--note", default=None)
    args = ap.parse_args()

    stamp = args.instant_utc.replace("Z", "+00:00")
    now_dt = datetime.datetime.fromisoformat(stamp)
    if now_dt.tzinfo is None:
        print("⛔ --instant-utc must carry a timezone")
        return 1
    now_unix = now_dt.timestamp()

    doc = json.loads(io.open(OUT, encoding="utf-8").read()) if OUT.exists() else dict(HEADER)
    rows = doc.setdefault("rows", [])

    facts = _session_facts(now_unix, args.newest_bar_unix, args.tf)
    row = {
        "instantUTC": now_dt.astimezone(datetime.timezone.utc)
                            .isoformat().replace("+00:00", "Z"),
        "instantET": now_dt.astimezone(ET).isoformat(),
        "symbol": args.symbol,
        "tf": args.tf,
        "study": args.study,
        "chartSession": args.chart_session,
        "arrival": args.arrival,
        "newestBarUnix": args.newest_bar_unix,
        "newestBarET": datetime.datetime.fromtimestamp(args.newest_bar_unix, ET).isoformat(),
        "session": facts,
        "vendor": {
            "isrealtime": args.isrealtime,
            "isconfirmed": args.isconfirmed,
            "ishistory": args.ishistory,
            "islast": args.islast,
            "islastconfirmedhistory": args.islastconfirmedhistory,
            "isnew": args.isnew,
        },
        "agreesWithOurSeam": (
            None if facts["ourSeamSaysForming"] is None
            else bool(facts["ourSeamSaysForming"]) == bool(args.isrealtime)
        ),
    }
    if args.note:
        row["note"] = args.note

    if any(r["instantUTC"] == row["instantUTC"] for r in rows):
        print(f"⛔ a row already exists at {row['instantUTC']} — NOTHING APPENDED")
        return 1

    rows.append(row)
    rows.sort(key=lambda r: r["instantUTC"])

    # ⭐ THE STANDING QUESTION, RECOMPUTED EVERY APPEND so the file always says what
    # it still needs rather than what it needed the day it was written.
    have_post20 = any(r["session"]["etClock"] >= "20:00:00" for r in rows)
    have_preopen = any(r["session"]["etClock"] < "09:30:00" for r in rows)
    # ⭐ THE ARRIVAL CONTROL: two rows on the SAME bar, close in time, one from a
    # chart that watched it form and one from a freshly-loaded document. Without
    # it, every row in this file is confounded by the viewer-dependence that
    # `barstate-viewer-dependent-on-vendor` already measured.
    pairs = {}
    for r in rows:
        pairs.setdefault(r["newestBarUnix"], set()).add(r["arrival"])
    have_arrival_control = any(len(v) == 2 for v in pairs.values())
    doc["_still_needed"] = {
        "anArrivalControl": not have_arrival_control,
        "aRowAfter2000ET": not have_post20,
        "aRowBefore0930ET": not have_preopen,
        "rulingUnlocked": have_arrival_control and have_post20 and have_preopen,
        "_": ("⛔ While any of these is true the mapping question stays OPEN and the seam stays "
              "unchanged. ⭐ THE ARRIVAL CONTROL IS THE ONE THAT WAS MISSING FROM THE ORIGINAL "
              "PLAN: time-of-day rows taken from ONE long-open chart cannot separate the "
              "hypotheses at all, because a bar that formed under your own session is already "
              "known to keep its realtime barstate. Two arrivals on the same bar is what "
              "discriminates; the clock rows then say for how long."),
    }

    tmp = OUT.with_suffix(".json.tmp")
    with io.open(tmp, "w", encoding="utf-8", newline="\n") as f:
        json.dump(doc, f, ensure_ascii=False, indent=2)
        f.write("\n")
    os.replace(tmp, OUT)

    print(f"appended row {len(rows)} at {row['instantET']}")
    print(f"  chart session   : {row['chartSession']}")
    print(f"  vendor          : isrealtime={args.isrealtime} isconfirmed={args.isconfirmed}")
    print(f"  our seam forming: {facts['ourSeamSaysForming']}")
    print(f"  past close by   : {facts['secondsPastScheduledClose']}s")
    print(f"  agree           : {row['agreesWithOurSeam']}")
    print(f"  ruling unlocked : {doc['_still_needed']['rulingUnlocked']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
