// app/src/components/chart/builder/graphWireFixture.test.js
//
// ─── C2D.9: THE FIXTURE BOTH LANES MEASURE ──────────────────────────────────
//
// ⛔ THIS FILE WRITES AN ARTIFACT, AND THAT IS ITS JOB. The Python lane cannot
// translate Pine — there is one parser and it is in JS (D-A1) — so a wire-size
// measurement taken through the REAL routes needs the real documents to arrive
// from somewhere. This emits them, exactly as `BuilderSheet.save()` would, into
// `tests/fixtures/graph_wire/`, and `tests/test_graph_wire_size.py` measures
// them through `api.main:app`.
//
// ⭐ SAME IDIOM AS `tests/fixtures/ast/multi_tree_parity.json`: one pinned
// artifact, produced by the lane that can produce it, read by the lane that
// must agree with it. It is regenerated by running this file, so it cannot go
// stale silently — a translator change that moved these documents would show up
// as a diff in the fixture, in the same commit.
import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'
import { translatePine } from '../engine/ast/pine'
import { memberInputTranslation } from './builderInputs'
import { paramLocatorsIn, manifestFromPlacements } from './pineParamManifest'
import { buildDefinition } from './BuilderSheet.jsx'
import { evaluateFormula } from './FormulaField.jsx'
import { BUILDER_INPUT_SCOPE, BUILDER_INPUTS } from './builderInputs.js'
import { reduceIfOversized, documentBytes } from '../engine/ast/graphDocument'

const OOS = path.resolve(process.cwd(), '../tools/c0_oos_fixtures')
const OUT = path.resolve(process.cwd(), '../tests/fixtures/graph_wire')

/** The carried rows for one script — exposed so the emitter can say WHICH case
 *  stopped producing columns instead of dying on `rows[0].source`. */
function productRows(name) {
  const src = fs.readFileSync(path.join(OOS, `${name}.pine`), 'utf8')
  const t = memberInputTranslation(translatePine, src, { paramManifest: true })
  return (t.outputs || []).filter((o) => o && o.ast && o.formula && !o.hidden).slice(0, 12)
}

/** The document the product sends, for one script. */
function productDocument(name, defId) {
  const src = fs.readFileSync(path.join(OOS, `${name}.pine`), 'utf8')
  const t = memberInputTranslation(translatePine, src, { paramManifest: true })
  const outs = (t.outputs || []).filter((o) => o && o.ast && o.formula && !o.hidden).slice(0, 12)
  const manifest = manifestFromPlacements(t.inputParams || [], outs.map((o, i) => ({
    treeIndex: i === 0 ? 'value' : `out${i + 1}`,
    locators: paramLocatorsIn(t.inputParams || [], o.ast),
  })))
  const rows = outs.map((o, i) => {
    const ev = evaluateFormula(o.formula, BUILDER_INPUT_SCOPE)
    return {
      key: i === 0 ? 'value' : `out${i + 1}`,
      label: o.title || '',
      source: o.formula,
      ast: o.ast,
      mode: ev.verdict ? ev.verdict.mode : 'clean',
      readback: ev.readback || '',
      style: 'line',
      color: BUILDER_INPUTS[0].default,
      width: BUILDER_INPUTS[1].default,
      hidden: false,
    }
  })
  return buildDefinition({
    defId,
    name: name.slice(0, 40),
    source: rows[0].source,
    ast: rows[0].ast,
    mode: rows[0].mode,
    readback: rows[0].readback,
    plots: rows,
    placement: { target: 'pane' },
    paramManifest: Object.keys(manifest).length ? manifest : null,
  })
}

/** Five points across the real distribution, not two anecdotes. */
// ⛔ A DEF ID IS `u_<12 hex>` — the store refuses anything else by name, and a
// fixture whose ids it rejects measures nothing on the lane that matters.
const CASES = [
  { name: 'long_tail__13-volatility-of-returns', id: 'u_c2d900000001', band: 'small' },
  { name: 'mid_engagement__13-spma-trend', id: 'u_c2d900000002', band: 'median' },
  { name: 'mid_engagement__14-master-line-lite', id: 'u_c2d900000003', band: 'p95' },
  { name: 'mid_engagement__22-rsi-levels-regime-map', id: 'u_c2d900000004', band: 'rsi-levels' },
  // ⚰⚰ THE `supertrend` BAND LEFT ON 2026-09-12 AND IT WAS THE BIGGEST ONE:
  // `high_engagement__03-supertrend-kivancozbilgic`, 438,263 bytes across ten plots,
  // the case the graph form shrank 60-fold. R-F refused nine of its columns and ruling
  // 1.2 refused the tenth — the author's untitled `ohlc4` fill edge — so it now carries
  // NOTHING and can produce no document to measure. It is replaced rather than dropped,
  // because the Python lane asserts five bands and a fixture that quietly shrank to four
  // would read as a passing measurement of a distribution nobody spans any more.
  { name: 'high_engagement__24-coppock-curve-multi-filter-markittick', id: 'u_c2d900000005', band: 'multi-filter' },
]

describe('C2D.9 — emit the wire-size fixture', () => {
  it('writes the documents the Python lane measures', () => {
    fs.mkdirSync(OUT, { recursive: true })
    const index = []
    for (const c of CASES) {
      // ⛔ A CASE THAT CARRIES NO COLUMNS FAILS BY NAME. Before ruling 1.2 this loop
      // read `rows[0]` from a script with zero rows and died on `undefined.source`,
      // which names the line and not the script. A fixture emitter must say WHICH
      // member of its roster stopped producing anything.
      const rows = productRows(c.name)
      expect(rows.length, `${c.name} carries no columns — it cannot be a wire-size case`)
        .toBeGreaterThan(0)
      const v1 = productDocument(c.name, c.id)
      // ⛔ THE SAVE DOOR DECIDES, not this file. `reduceIfOversized` is what the
      // product calls, so what lands here is what would actually be sent.
      const sent = reduceIfOversized(v1)
      fs.writeFileSync(path.join(OUT, `${c.id}.json`),
        JSON.stringify(sent, null, 2), 'utf8')
      index.push({
        ...c,
        v1Bytes: documentBytes(v1),
        sentBytes: documentBytes(sent),
        isGraph: !!(sent.compute && sent.compute.graph),
        plots: (sent.plots || []).length,
      })
    }
    fs.writeFileSync(path.join(OUT, 'index.json'),
      JSON.stringify({ cases: index }, null, 2), 'utf8')
    // eslint-disable-next-line no-console
    console.log(`\n=== C2D.9 fixture ===\n${index.map(
      (r) => `  ${r.band.padEnd(11)} v1 ${String(r.v1Bytes).padStart(7)}B -> sent `
        + `${String(r.sentBytes).padStart(7)}B  ${r.isGraph ? 'GRAPH' : 'forest'}  ${r.plots} plots`,
    ).join('\n')}`)
    // ⛔ THE BANDS MUST ACTUALLY SPAN SOMETHING. A fixture whose five cases are
    // all tiny would measure nothing, and would pass every assertion below.
    expect(index.some((r) => r.isGraph)).toBe(true)
    expect(index.some((r) => !r.isGraph)).toBe(true)
    expect(Math.max(...index.map((r) => r.v1Bytes)))
      .toBeGreaterThan(20 * Math.min(...index.map((r) => r.v1Bytes)))
  })
})
