"""Generated by tools/notebook_switch_rehearsal.py: one boot's switch values, then the
real sandbox launcher, unchanged."""
import os
import runpy
import sys

SET = {"J2_SHARE_LINKS_ENABLED": "1", "NOTEBOOK_ASK_INSERT_ON": "1", "NOTEBOOK_ONBOARDING_ENABLED": "1", "NOTEBOOK_PERSONAL_API_ENABLED": "1", "NOTEBOOK_PUBLISH_ENABLED": "1", "NOTEBOOK_WRITING_HELP_ENABLED": "1"}
UNSET = ["NOTEBOOK_OFFLINE_DEFAULT_ON"]
REAL = "C:\\Users\\Patrick\\uct-worktrees\\notebook-w10s2\\scripts\\hub_sandbox_boot.py"
for _k, _v in SET.items():
    os.environ[_k] = _v
for _k in UNSET:
    os.environ.pop(_k, None)
sys.argv[0] = REAL
runpy.run_path(REAL, run_name='__main__')
