"""Seed roster for The Desk → Team ("Meet the Traders").

Generated from the firm's "Inside Uncharted Territory: Meet the Traders" sheet.
Consumed by desk_store.ensure_default_team(), which inserts any member whose
name is not already present (idempotent; never clobbers admin edits or photos).
"""
from __future__ import annotations

SEED_MEMBERS: list[dict] = [
    {
        "name": "TSDR",
        "role": "Founder",
        "years_trading": "",
        "bio": "Boss Guy",
        "trading_style": "",
        "teaching_focus": "",
        "twitter_url": "https://x.com/TSDR_Trading",
        "sort_order": 0,
    },
    {
        "name": "Bracco",
        "role": "Co-Founder",
        "years_trading": "6 Years",
        "bio": "Got interested in markets in Q1 2020 and learned through trial, error, and blowing up small accounts while working shifts at the rink to fund trading. Joined his first trading community in December 2021, where he met and was mentored by TSDR Trading, learning the foundations of technical analysis and stock selection. Over the years, he evolved from a struggling options trader into a disciplined operator and now co‑runs Uncharted Territory. A student of market history with a deep passion for studying charts, patterns, and major historical moves. Transparent about struggles, drawdowns, and the realities of trading, and committed to continuous learning.",
        "trading_style": "Hunts for “fat pitches” — rare, high‑conviction trades that can define a year\nComfortable sizing up aggressively when equity and conditions align\nMix of trend‑following and selective contrarian trading at extremes\nSpecializes in mean‑reversion only in major capitulatory bottoms or parabolic blowoffs\nTrades momentum swings, breaking‑news setups, and high‑impact opportunities\nPrimarily trades stocks, but uses options or futures when the setup calls for it\nBuilds equity between major opportunities through smaller, steady trades",
        "teaching_focus": "Identifying high‑quality, high‑conviction “fat pitch” setups\nPattern recognition developed through years of studying market history\nUnderstanding when to size up and when to stay small\nTransparency around drawdowns, mistakes, and the emotional side of trading\nHelping traders recognize when he’s excited about an idea — a signal of strong conviction\nEncouraging community, accountability, and continuous study",
        "twitter_url": "https://x.com/Braczyy",
        "sort_order": 1,
    },
    {
        "name": "1ChartMaster",
        "role": "Technical / Momentum Trader",
        "years_trading": "10+ Years",
        "bio": "A fisherman by background with a natural eye for reading charts and price behavior. Over a decade of screen time has built a strong foundation in technical analysis, pattern recognition, momentum trading, catalyst‑driven setups, and identifying relative strength leaders. Known for spotting clean setups early as they form and presenting them to the group with enough time to position confidently.",
        "trading_style": "Technical analysis\nBuying pullbacks\nPattern recognition\nMomentum trading\nCatalyst‑driven setups (earnings, news, PRs)\nRelative strength leadership\nEarly identification of developing setups\nDisciplined 1:5 risk‑to‑reward framework\nSmall, controlled losses with focus on outsized winners",
        "teaching_focus": "Reading charts with precision and simplicity\nIdentifying patterns before they break\nSpotting momentum shifts and RS leaders\nUnderstanding catalysts and how they drive price\nExecuting a disciplined risk‑to‑reward strategy\nSharing practical techniques learned over 10+ years of trading",
        "twitter_url": "https://x.com/1ChartMaster",
        "sort_order": 2,
    },
    {
        "name": "Manrav",
        "role": "Momentum Swing Trader",
        "years_trading": "5 Years",
        "bio": "Aggressive momentum/swing trader blending Stockbee, TraderLion, and Oliver Kell principles. Believes screen time > books. Trades top‑down with tight risk, focusing on Relative Strength and clean technical setups.",
        "trading_style": "Top‑down momentum + RS-focused swing trading. Monthly/weekly for context, daily for setups. Trades shares and options, using options flow as a conviction overlay. Aggressive in hot markets, disciplined with tight stops.",
        "teaching_focus": "Top‑down process to stay aligned with market trend\nIdentifying high‑probability momentum setups with tight risk\nTracking Relative Strength leaders during corrections\nSitting in cash during chop and avoiding overtrading\nMastering 1–2 core setups deeply\nUsing options flow as a secondary confidence tool\nBuilding pattern recognition through screen time and chart reps\nI post entries and stop levels. Because I work a full-time job, I can't always alert exits in real-time. If a stop is hit, assume I am out. Don't wait for confirmation. Respect your stops.\nMy DMs are always open; looking forward to learning from you all!",
        "twitter_url": "https://x.com/manrav",
        "sort_order": 3,
    },
    {
        "name": "AlexJonesIndustrialAverage",
        "role": "Options-Flow Specialist",
        "years_trading": "9 Years (Actively Focust for 5 years)",
        "bio": "Conspiracy theorist, market participant, and options‑flow specialist known for transparency, humor, and real‑time communication. Balances trading with work and family commitments. Momentum‑focused trader who blends technical setups with deep options‑flow interpretation to build conviction. Meme connoisseur, patriot, and dad.",
        "trading_style": "Momentum trading\nDay trading + swing trading\nHigh‑tight flags\n9/20 EMA confluence\nOops reversals\nVolume‑price analysis (VPA)\nUses both shares and options\nLeverages options flow to size trades and confirm setups\nStrong intuition for which flow is meaningful vs noise",
        "teaching_focus": "Real‑time options flow and how to interpret it\nUsing flow as a confluence tool (not a standalone signal)\nIdentifying high‑probability momentum setups\nTransparency in entries, invalidations, and trade management\nHelping members understand the 5% of flow that actually matters\nPairing technical setups with flow‑based conviction",
        "twitter_url": "https://x.com/AlexJonesIA",
        "sort_order": 4,
    },
    {
        "name": "Jersace",
        "role": "Opportunistic Trader",
        "years_trading": "10 Years",
        "bio": "A naturally funny, high‑energy personality who found joy and freedom in growing his money. Driven by ambition, a love for experiences, and an appreciation for the finer things, he uses trading to build the life he envisions and provide for a future family. Has been in many groups, met nearly everyone in the space, and thrives on connection — believing true wealth is friends and family. Considers the community part of that circle.",
        "trading_style": "Technical‑based trader using a mix of tools, momentum reads, key setups, unusual flow, and strong instincts. Evolved from a hyper‑asymmetric trader into an opportunistic one. Enjoys long‑term equity investing but gravitates toward leveraged, time‑specific bets with defined targets — often hitting the mark.",
        "teaching_focus": "Not a formal “teacher,” but an open conversational mentor who explains his thinking, answers questions, and helps others identify true opportunities — the most important tool in any trader’s belt. Emphasizes self‑belief, mindset, and overcoming the inner enemy that holds traders back. \"You are youre own greatest enemy. Read that again\"",
        "twitter_url": "https://x.com/JersaceX",
        "sort_order": 5,
    },
    {
        "name": "DarkOblivion",
        "role": "Growth / VCP Trader",
        "years_trading": "18 Years (Actively Focused for 6 years)",
        "bio": "Has been trading since 2008 and became deeply active during the Covid era. He has traded with multiple groups over the years, so his name may already be familiar to many. His approach blends growth leadership, basing structures, VCP principles, EMA behavior, and a style that sits somewhere between Minervini and Kell. He trades with a conservative mindset, keeping equity risk per trade low and relying on a handful of high‑conviction, high‑position‑size winners to drive the bulk of his yearly returns. His strength lies in feeling the ebb and flow of the market and aligning himself with it rather than forcing trades.",
        "trading_style": "Trades a hybrid Minervini/Kell style focused on growth leaders, basing patterns, VCP structures, and EMA behavior. He prefers conservative equity risk and relies on a few high‑conviction winners each year, aligning entries with the ebb and flow of the broader market. His setups center on buying against key EMAs when weekly and daily structures sync, entering on strong daily closes or hammer recaptures of major moving averages. He favors multi‑contraction bases, leaders holding the 30‑week or 65‑EMA during market weakness, and earnings gappers that tighten against the 21‑EMA. He avoids chasing extended names, choosing instead to establish positions early within proper base structure.",
        "teaching_focus": "Identifying the shapes, behaviors, and structural traits that big winning stocks show before they move\nRecognizing constructive, accumulative chart patterns and understanding where the strongest bases form\nDistinguishing healthy consolidations from traps and low‑quality structures\nFinding leadership early while it’s still building pressure beneath key moving averages\nUnderstanding how to spot the best stocks and bases before they make their move",
        "twitter_url": "",
        "sort_order": 6,
    },
    {
        "name": "Tiny Trades",
        "role": "Momentum Swing Trader",
        "years_trading": "14 Years Investing  6 Years Active Trading",
        "bio": "Average, hard‑working guy who believes in discipline, planning, and personal responsibility. Grew up learning long‑term investing from his parents and saw firsthand the power of consistency and compound interest. Lifelong believer in building wealth through steady contributions and patience. Sarcastic, steady, and focused on long‑term growth over excitement.",
        "trading_style": "Momentum swing trader\nLong‑term buy‑and‑hold (SPY, VTI, QQQ every two weeks)\nTrades shares only\nUses weekly/daily charts for entries and exits\nBuys pullbacks, bases, and checkbacks to key moving averages\nAvoids breakouts and extended stocks\nSteps aside in bad environments\nOccasional day trades only when exceptional",
        "teaching_focus": "Higher‑timeframe structure (weekly/daily)\nIdentifying logical risk points\nMomentum swings in strong uptrends\nAccumulating in bases rather than chasing breakouts\nConsistency, discipline, and risk management\nSlow, steady account growth (“tortoise, not the hare”)\nEncouraging long‑term investing as a foundation",
        "twitter_url": "https://x.com/Tiny__Trades",
        "sort_order": 7,
    },
    {
        "name": "DMarbz",
        "role": "Technical Trader (ex-Advisor)",
        "years_trading": "Advisor for Merril Lynch and Fidelity for 13 years (Full Time 2 Years)",
        "bio": "Former Merrill Lynch and Fidelity advisor who managed a billion‑dollar book before launching his own RIA. Deep background in wealth management, market structure, and client portfolio strategy. Now trades full‑time while advising private clients. Brings a blend of institutional experience, market mechanics knowledge, and catalyst‑driven insight.",
        "trading_style": "Technical analysis\nNews‑driven catalysts (earnings, PRs, partnerships, contract wins)\nMarket mechanics (CTA flows, OPEX, month/quarter‑end positioning)\nShort‑term options trading\n“Gut‑feel” style informed by new information + market structure\nFocus on underappreciated catalysts that can move price quickly\nPlays low‑float IPOs, short‑interest setups, and SPX positioning windows",
        "teaching_focus": "Identifying significant new information for individual companies\nUnderstanding what’s driving overall market price action\nExplaining market mechanics (CTA flows, dealer positioning, OPEX effects)\nHighlighting windows where price action may turn\nHelping members interpret catalysts and structural forces behind moves",
        "twitter_url": "",
        "sort_order": 8,
    },
    {
        "name": "Ciro Viotti",
        "role": "High-ADR Momentum Trader",
        "years_trading": "10+ Years",
        "bio": "Former professional poker player and online marketing entrepreneur who transitioned into full‑time trading over a decade ago. Spent early years focused on crypto before shifting heavily into equities. Known for extreme dedication, obsessive work ethic, and a reputation as a “gunslinger” who still prioritizes tight risk management. Believes trading is both a brutal personal development path and the best profession in the world.",
        "trading_style": "High‑ADR stocks with big move potential\nMomentum themes + high‑volume closes\nMix of momentum trades and swings in established leaders\nHeavy options usage (core long‑dated + short‑dated for bursts)\nTight‑risk entries using MAs, gaps, EMA crossbacks\nOversizes early when risk is extremely tight, removes risk on first trim\nRolls short‑term call profits into shares on follow‑through\nLong/short book with downside hedges\nTrades that work immediately are sized up aggressively\nObsessive scanning, charting, and preparation",
        "teaching_focus": "How to identify high‑ADR momentum opportunities\nStructuring trades with tight risk and defined stops\nUsing options responsibly (only for advanced traders)\nUnderstanding volume, themes, and high‑probability bursts\nManaging risk while scaling size\nBalancing momentum trades with leadership swings\nNavigating the psychological brutality of trading\nDeveloping discipline, resilience, and consistency\nRecognizing when a trade should work immediately vs. when to cut it",
        "twitter_url": "https://x.com/CiroViotti",
        "sort_order": 9,
    },
    {
        "name": "Financial Contagion",
        "role": "Squeeze / Research Trader",
        "years_trading": "7 Years Active Trading",
        "bio": "Started in markets young — bought Sun Microsystems at $4 with parent‑funded capital and learned early that “cheap” isn’t a strategy. Placed 2nd in the Mid‑Atlantic High School Stock Market Challenge in 2005. Returned to markets in 2018 via Robinhood and eventually found TSDR on Spaces, whose approach resonated enough to “stalk” ever since. Outside markets, plays on multiple soccer teams and works on cars.",
        "trading_style": "Squeeze setups driven by deep research (short interest, fundamentals, insider buying, thesis‑building)\nPolicy‑driven trades (state or political catalysts outside traditional macro)\nSwing trading\nMomentum trading\nParticipating in “hot” markets — up or down\nSupport/resistance‑based trading\nExperimenting with new ideas in small size",
        "teaching_focus": "Weekly/monthly charts often signal major moves before they happen\nSupport/resistance is king — especially on long‑term charts; avoid the “dead bodies”\nFinviz is an elite free tool for scanning despite its bullish bias",
        "twitter_url": "https://x.com/SpecializedA4",
        "sort_order": 10,
    },
    {
        "name": "Beebe 🐝",
        "role": "Swing Trader",
        "years_trading": "7 Years (Full Time 2 years)",
        "bio": "Former fundamental speculator who transitioned into full‑time trading after discovering a passion for price action. Spent 2022–2024 deeply studying technical analysis, charting, and market behavior, eventually leaving her full‑time job to pursue trading professionally. Known for resilience, discipline, and the ability to “be a good loser” — losing small, winning big, and compounding consistently. Passionate about learning, improving, and helping others change their lives through trading.",
        "trading_style": "Primarily swing trading\nAllows swings to evolve into position trades when market conditions support it\nBuys support with tight candles (often early entries before larger moves)\nHeavy focus on price action and technical analysis\nUses tight risk, tight stops, and disciplined sizing\nComfortable taking many small losses to capture larger winners\nContinually refining patience, selectivity, and emotional detachment from daily P/L",
        "teaching_focus": "Price action trading and support‑based entries\nManaging risk through tight stops and controlled sizing\nDeveloping resilience and emotional discipline\nUnderstanding that losing is part of the process — losing small, winning big\nLong‑term compounding and building a sustainable equity curve\nThe personal development side of trading: patience, consistency, and incremental improvement\nEncouraging traders to pursue growth, learning, and self‑belief",
        "twitter_url": "https://x.com/awackywabbit",
        "sort_order": 11,
    },
    {
        "name": "Camden Chris",
        "role": "Swing Trader",
        "years_trading": "7 Years",
        "bio": "Full‑time husband, father, and Program Manager trading for 7 years. Focused on process, discipline, and risk‑based decision making. Trades intraday for cash flow and occasionally swings. Long‑term investor with a track record of identifying misunderstood companies early.",
        "trading_style": "My trading style is heavily centered around:\nPrice structure\nMomentum shifts\nEMAs/VWAP alignment and trend behavior\nPrice exhaustion and extension",
        "teaching_focus": "My goal is not to tell anyone what to blindly buy or sell. My goal is to provide (MY) perspective, thought process, and situational awareness that members can use within their own system and decision making",
        "twitter_url": "https://x.com/Camden_Chris",
        "sort_order": 12,
    },
    {
        "name": "Zen",
        "role": "Thematic Swing Trader",
        "years_trading": "6 Years",
        "bio": "Got hooked on markets after his first Robinhood trade opened up 100% the next day. Explored multiple styles early on — scalping, options, futures — before settling into swing trading as his core approach. Competes in the United States Investing Championship and posts results quarterly.",
        "trading_style": "Thematic swing trader focused on names with strong tailwinds from government action, sector/group strength, or news‑driven catalysts. Trades primarily off daily and weekly charts with entries refined on the 30‑minute. Shares detailed due diligence and thesis‑driven reasoning behind moves.",
        "teaching_focus": "Identifying themes with structural tailwinds, understanding how catalysts drive group movement, and using multi‑timeframe alignment (weekly/daily with 30‑min entries) to build high‑probability swing setups.",
        "twitter_url": "https://x.com/mindofzen_",
        "sort_order": 13,
    },
    {
        "name": "LostNotFound",
        "role": "Catalyst / Thesis Trader",
        "years_trading": "5 Years",
        "bio": "A father, husband, and software developer who trades with intention and curiosity. Started by managing a simple 401k and evolved into active trading during COVID, drawn to the autonomy of creating opportunities on your own time. You learn best through mistakes and hands‑on experience, and you only take trades with a clear reason — whether it’s overlooked value, a fundamental shift, or a catalyst that changes the story. You blend narrative conviction with technical structure, favoring daily/weekly alignment, base breakouts, and long‑term reversals. Your goal is to surface under‑the‑radar ideas and build the strongest future possible for your family, while encouraging others to learn at their own pace and stand firm in what works for them.",
        "trading_style": "Thesis‑driven setups; catalyst‑based trades; daily/weekly timeframe convergence; base breakouts; long‑term downtrend reversals; technical confirmation layered on top of narrative conviction; focus on under‑the‑radar opportunities.",
        "teaching_focus": "Helping traders find their own pace and process; highlighting overlooked opportunities; showing how to build conviction through narrative + technical alignment; emphasizing learning through mistakes; demonstrating how catalysts reshape trajectories; reinforcing purposeful, reason‑based trading.",
        "twitter_url": "",
        "sort_order": 14,
    },
    {
        "name": "Bucket Head",
        "role": "Swing Trader",
        "years_trading": "5 Years (Full Time 1 year)",
        "bio": "Former college baseball player who started trading during the COVID era and transitioned to full‑time after developing a structured, process‑driven approach. Builds data‑backed edges around flow and options premiums, focusing on identifying disconnects between premium positioning and price action. Brings a baseball‑honed mindset of short memory, repetition, and process obsession into trading, allowing him to recognize high‑quality opportunities with discipline and confidence.",
        "trading_style": "Primarily swing trading\nHolds 3–4 positions with active intraday hedging\nFocus on 1–2 week swings in indices and high‑momentum, highly liquid names\nData‑driven edges built around flow and options premiums\nSpecializes in reversal setups created by premium/price dislocations\nRisk defined through clean structural levels",
        "teaching_focus": "Rule‑based system built around market tide and net premiums\nUnderstanding premium/price disconnects and how to exploit them\nLayering hedges on top of swing positions\nProcess‑first mindset and disciplined execution\nHelping traders integrate a structured, flow‑driven framework into their own playbook",
        "twitter_url": "https://x.com/Zack_Davis15",
        "sort_order": 15,
    },
    {
        "name": "Nickstro",
        "role": "Momentum Breakout Trader",
        "years_trading": "4 Years",
        "bio": "A swing trader who began in the hype‑driven world of day trading but quickly realized the real money is made by sitting, not scalping. After a year of day trading, transitioned fully into swing trading and has spent the last three years sharpening momentum breakout, episodic pivot, and post‑earnings gap strategies. Trades with a low win rate (~30%) but high reward‑to‑risk (4–5:1), proving you don’t need to win often to be profitable. Believes the best moves come from long, clean bases and that stocks need time to set up. Passionate about helping struggling traders understand market rhythm, identify leaders early, and hold them through noise without panicking at the first red day.",
        "trading_style": "Momentum breakouts; episodic pivots; post‑earnings gaps; emphasizes specific entry tactics and nuanced execution; prefers larger timeframes for larger moves; focuses on leaders emerging from long, clean bases.",
        "teaching_focus": "Helping traders zoom out and understand the bigger picture; teaching when to press and when to sit tight; reinforcing that low win‑rate/high R:R is viable; encouraging patience, base‑building awareness, and holding leaders through volatility; showing that swing trading doesn’t require staring at intraday charts.",
        "twitter_url": "https://x.com/Nickstro_",
        "sort_order": 16,
    },
    {
        "name": "Stef",
        "role": "Chief Recording Officer",
        "years_trading": "4 Years",
        "bio": "A healthcare professional, wife and a proud dog mom who stumbled into the markets after Covid, originally hoping to make quick money. It didn’t take long to realize this game is anything but easy — but somewhere in the struggle, I fell in love with it. The challenge, the charts, the puzzle of price action… it hooked me. What started as curiosity turned into a passion, and now trading is a craft I’m committed to mastering every single day.",
        "trading_style": "I’m a short‑term anticipatory swing trader who focuses on pullbacks and launchpads, using MAs as a guidepost for my entries and stops. My approach is a mix of what I’ve learned from my mentors in Uncharted Territory plus influences from Stockbee, Charles Harris and Oliver Kell. I like getting in early, trading clean structure, and keeping risk tight.",
        "teaching_focus": "I became Chief Recording Officer because I nagged the guys until the recordings actually got uploaded — and it worked. Now I organize and maintain the entire library so traders can easily rewatch sessions and learn at their own pace. My focus in this group is making the content accessible, searchable, and structured so no one has to dig for the information they need. There is so much valuable content in Uncharted Territory and the growth never stops for any of us",
        "twitter_url": "https://x.com/StefCR0",
        "sort_order": 17,
    },
]
