"""Provider Abstraction Layer (D1) — shared typed-exception base and the
`ProviderResult`/`ProvenanceRecord`/`FreshnessClass` envelope every adapter
returns. entity-master-spec.md's sibling, `provider-abstraction-spec.md`
§6, is the source of truth this module implements.

The exception shape mirrors `api/services/journal_two/broker/
snaptrade_client.py`'s `SnapError` family exactly (base: message + status +
code + body; `RateLimited` adds `retry_after`) — read in full before this
module was written, per spec §2.1/§6.5's explicit instruction to copy that
shape. The one addition beyond `SnapError`: a `vendor: str` field on the
base, since — unlike SnapTrade, which has exactly one vendor — this module
serves MULTIPLE vendor families and a caller catching a bare `ProviderError`
needs to know which vendor raised it (spec §6.5: "A caller that wants
vendor-agnostic handling... catches ProviderError and reads .vendor").

Per-vendor subclass families are generated by `make_vendor_errors(vendor)`
rather than hand-written five times per vendor, so `FMPNotFound` and
`MassiveNotFound` are guaranteed to share the identical shape and MRO
without copy-paste drift — while still being genuinely DISTINCT classes
(spec §6.5: "a caller catching FMPRateLimited should never accidentally
catch a Massive rate-limit too"), confirmed by `isinstance` in the test
suite, not just by name.
"""
from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Any, Literal, Optional


# ── Typed error taxonomy (spec §6.5) ────────────────────────────────────────

class ProviderError(Exception):
    """Base for every vendor adapter's errors. Mirrors SnapError's shape
    (message + status + code + body), plus `vendor` since this base is
    shared across multiple vendor families."""

    def __init__(
        self, message: str, *, vendor: str,
        status: Optional[int] = None, code: Optional[str] = None, body: Any = None,
    ):
        super().__init__(message)
        self.vendor = vendor
        self.status = status
        self.code = code
        self.body = body


class ProviderNotConfigured(ProviderError):
    """The vendor's API key env var is unset — a distinct, common,
    non-transient case worth its own class (SnapNotConfigured's precedent)."""


class ProviderAuthError(ProviderError):
    """The vendor rejected the credential (401/403, NOT the cached-forbidden-
    endpoint case — see ProviderResult.degraded, §6.4)."""


class ProviderRateLimited(ProviderError):
    """The vendor's own limit was hit (429, or a vendor-specific
    200-with-throttle-body per AlphaVantage's precedent, spec §2.1/§9.5)."""

    def __init__(self, message: str, *, retry_after: Optional[float] = None, **kw):
        super().__init__(message, **kw)
        self.retry_after = retry_after


class ProviderTransient(ProviderError):
    """Network-level or 5xx failure, retryable per the adapter's own
    backoff policy."""


class ProviderNotFound(ProviderError):
    """The vendor answered but has nothing for this request — distinct from
    every failure class above, and distinct from a genuinely-empty
    ProviderResult (spec §6.4: a NotFound is raised; a genuine empty answer
    is a successful ProviderResult with value=[]/None)."""


class VendorErrorFamily:
    """The five leaf classes for one vendor, each a genuinely distinct
    subclass (not an alias) so `except FMPRateLimited` can never catch a
    Massive error. `.raise_not_configured(...)` etc. are convenience
    constructors that always fill `vendor` for you — every raise site in an
    adapter uses these rather than constructing the class directly, so
    `vendor` can never be forgotten or misspelled."""

    __slots__ = ("vendor", "NotConfigured", "AuthError", "RateLimited", "Transient", "NotFound")

    def __init__(self, vendor: str, class_prefix: Optional[str] = None):
        self.vendor = vendor
        # Matches the spec's own naming exactly ("FMPNotFound", "MassiveNotFound")
        # — an acronym vendor name needs its prefix given explicitly rather than
        # derived by str.capitalize(), which would produce "FmpNotFound".
        prefix = class_prefix or vendor.capitalize()
        self.NotConfigured = type(f"{prefix}NotConfigured", (ProviderNotConfigured,), {})
        self.AuthError = type(f"{prefix}AuthError", (ProviderAuthError,), {})
        self.RateLimited = type(f"{prefix}RateLimited", (ProviderRateLimited,), {})
        self.Transient = type(f"{prefix}Transient", (ProviderTransient,), {})
        self.NotFound = type(f"{prefix}NotFound", (ProviderNotFound,), {})

    def not_configured(self, message: str, **kw) -> ProviderNotConfigured:
        return self.NotConfigured(message, vendor=self.vendor, **kw)

    def auth_error(self, message: str, **kw) -> ProviderAuthError:
        return self.AuthError(message, vendor=self.vendor, **kw)

    def rate_limited(self, message: str, **kw) -> ProviderRateLimited:
        return self.RateLimited(message, vendor=self.vendor, **kw)

    def transient(self, message: str, **kw) -> ProviderTransient:
        return self.Transient(message, vendor=self.vendor, **kw)

    def not_found(self, message: str, **kw) -> ProviderNotFound:
        return self.NotFound(message, vendor=self.vendor, **kw)


def make_vendor_errors(vendor: str, class_prefix: Optional[str] = None) -> VendorErrorFamily:
    """One call per adapter module, e.g.
    `_ERR = make_vendor_errors("fmp", class_prefix="FMP")`, then
    `raise _ERR.not_found("...")`, `except _ERR.RateLimited: ...`.
    `class_prefix` defaults to `vendor.capitalize()` when omitted (fine for
    an ordinary word like "Massive"; pass it explicitly for an acronym like
    "FMP" so the generated class is `FMPNotFound`, not `FmpNotFound`)."""
    return VendorErrorFamily(vendor, class_prefix)


# ── The result envelope (spec §6.1-6.4) ─────────────────────────────────────

FreshnessClass = Literal["real_time", "delayed_15", "end_of_day", "historical"]
DegradedReason = Literal["cached_forbidden", "circuit_open"]


@dataclass(frozen=True)
class ProvenanceRecord:
    """Spec §6.2, generalizing bar_provenance.py's narrower shape."""
    vendor: str
    source_activity: str  # e.g. "fmp_client.get_key_metrics_ttm"
    fetched_at: float = field(default_factory=time.time)  # epoch; caller may override for tests
    tie_break: Optional[str] = None


@dataclass(frozen=True)
class ProviderResult:
    """Spec §6.1/§6.4. `degraded` distinguishes a cached-forbidden or
    circuit-breaker default from a genuine vendor answer — never silently
    rendered as real data (PRD §9.4/§9.6, the "quiet market" anti-pattern
    this whole system exists to prevent). `degraded_since` is populated only
    when `degraded == "cached_forbidden"` (the original 403's timestamp,
    spec §6.4)."""
    value: Any
    provenance: ProvenanceRecord
    licensing_class: str
    freshness: Optional[FreshnessClass] = None
    degraded: Optional[DegradedReason] = None
    degraded_since: Optional[float] = None
