"""Provider Abstraction Layer (D1) — shared typed-exception base and the
`ProviderResult`/`ProvenanceRecord`/`FreshnessClass` envelope every adapter
returns. entity-master-spec.md's sibling, `provider-abstraction-spec.md`
§6, is the source of truth this module implements.

The exception shape mirrors `api/services/journal_two/broker/
snaptrade_client.py`'s `SnapError` family exactly (base: message + status +
code + body; `RateLimited` adds `retry_after`) — read in full before this
module was written, per spec §2.1/§6.5's explicit instruction to copy that
shape. The one addition beyond `SnapError`: a `vendor: str` field on the
base, since — unlike SnapTrade, which has exactly one vendor — this module
serves MULTIPLE vendor families and a caller catching a bare `ProviderError`
needs to know which vendor raised it (spec §6.5: "A caller that wants
vendor-agnostic handling... catches ProviderError and reads .vendor").

Per-vendor subclass families are generated by `make_vendor_errors(vendor)`
rather than hand-written five times per vendor, so `FMPNotFound` and
`MassiveNotFound` are guaranteed to share the identical shape and MRO
without copy-paste drift — while still being genuinely DISTINCT classes
(spec §6.5: "a caller catching FMPRateLimited should never accidentally
catch a Massive rate-limit too"), confirmed by `isinstance` in the test
suite, not just by name.
"""
from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Any, Literal, Optional


# ── Typed error taxonomy (spec §6.5) ────────────────────────────────────────

class ProviderError(Exception):
    """Base for every vendor adapter's errors. Mirrors SnapError's shape
    (message + status + code + body), plus `vendor` since this base is
    shared across multiple vendor families."""

    def __init__(
        self, message: str, *, vendor: str,
        status: Optional[int] = None, code: Optional[str] = None, body: Any = None,
    ):
        super().__init__(message)
        self.vendor = vendor
        self.status = status
        self.code = code
        self.body = body


class ProviderNotConfigured(ProviderError):
    """The vendor's API key env var is unset — a distinct, common,
    non-transient case worth its own class (SnapNotConfigured's precedent)."""


class ProviderAuthError(ProviderError):
    """The vendor rejected the credential (401/403, NOT the cached-forbidden-
    endpoint case — see ProviderResult.degraded, §6.4).

    `entitlement_denied` (D1 provenance/freshness hardening, 2026-09-02)
    distinguishes two real, evidence-backed cases this class used to
    collapse into one: 403 means the credential is VALID but this specific
    resource/plan-tier is not entitled to it (Massive's live-confirmed
    index-quote gap is the evidence for this exact case); 401 means the
    credential itself was rejected. Derived automatically from `status` —
    True for 403, False for 401, `None` when the raising site didn't supply
    a recognized status. Never guessed beyond what the HTTP status already
    tells us; a "provider does not support this capability at all" state
    (distinct from "not entitled under the current plan") has no live
    evidence separating it from 403 in this codebase today, so it is not
    invented as a fourth class here."""

    def __init__(self, message: str, **kw):
        super().__init__(message, **kw)
        if self.status == 403:
            self.entitlement_denied = True
        elif self.status == 401:
            self.entitlement_denied = False
        else:
            self.entitlement_denied = None


class ProviderRateLimited(ProviderError):
    """The vendor's own limit was hit (429, or a vendor-specific
    200-with-throttle-body per AlphaVantage's precedent, spec §2.1/§9.5)."""

    def __init__(self, message: str, *, retry_after: Optional[float] = None, **kw):
        super().__init__(message, **kw)
        self.retry_after = retry_after


class ProviderTransient(ProviderError):
    """Network-level or 5xx failure, retryable per the adapter's own
    backoff policy."""


class ProviderNotFound(ProviderError):
    """The vendor answered but has nothing for this request — distinct from
    every failure class above, and distinct from a genuinely-empty
    ProviderResult (spec §6.4: a NotFound is raised; a genuine empty answer
    is a successful ProviderResult with value=[]/None)."""


class VendorErrorFamily:
    """The five leaf classes for one vendor, each a genuinely distinct
    subclass (not an alias) so `except FMPRateLimited` can never catch a
    Massive error. `.raise_not_configured(...)` etc. are convenience
    constructors that always fill `vendor` for you — every raise site in an
    adapter uses these rather than constructing the class directly, so
    `vendor` can never be forgotten or misspelled."""

    __slots__ = ("vendor", "NotConfigured", "AuthError", "RateLimited", "Transient", "NotFound")

    def __init__(self, vendor: str, class_prefix: Optional[str] = None):
        self.vendor = vendor
        # Matches the spec's own naming exactly ("FMPNotFound", "MassiveNotFound")
        # — an acronym vendor name needs its prefix given explicitly rather than
        # derived by str.capitalize(), which would produce "FmpNotFound".
        prefix = class_prefix or vendor.capitalize()
        self.NotConfigured = type(f"{prefix}NotConfigured", (ProviderNotConfigured,), {})
        self.AuthError = type(f"{prefix}AuthError", (ProviderAuthError,), {})
        self.RateLimited = type(f"{prefix}RateLimited", (ProviderRateLimited,), {})
        self.Transient = type(f"{prefix}Transient", (ProviderTransient,), {})
        self.NotFound = type(f"{prefix}NotFound", (ProviderNotFound,), {})

    def not_configured(self, message: str, **kw) -> ProviderNotConfigured:
        return self.NotConfigured(message, vendor=self.vendor, **kw)

    def auth_error(self, message: str, **kw) -> ProviderAuthError:
        return self.AuthError(message, vendor=self.vendor, **kw)

    def rate_limited(self, message: str, **kw) -> ProviderRateLimited:
        return self.RateLimited(message, vendor=self.vendor, **kw)

    def transient(self, message: str, **kw) -> ProviderTransient:
        return self.Transient(message, vendor=self.vendor, **kw)

    def not_found(self, message: str, **kw) -> ProviderNotFound:
        return self.NotFound(message, vendor=self.vendor, **kw)


def make_vendor_errors(vendor: str, class_prefix: Optional[str] = None) -> VendorErrorFamily:
    """One call per adapter module, e.g.
    `_ERR = make_vendor_errors("fmp", class_prefix="FMP")`, then
    `raise _ERR.not_found("...")`, `except _ERR.RateLimited: ...`.
    `class_prefix` defaults to `vendor.capitalize()` when omitted (fine for
    an ordinary word like "Massive"; pass it explicitly for an acronym like
    "FMP" so the generated class is `FMPNotFound`, not `FmpNotFound`)."""
    return VendorErrorFamily(vendor, class_prefix)


# ── The result envelope (spec §6.1-6.4) ─────────────────────────────────────

# "stale" added by the D1 provenance/freshness hardening pass (2026-09-02):
# real, evidence-backed state distinct from the other four -- a vendor
# answered successfully (not NotFound, not degraded) but its OWN reported
# observation timestamp is old enough that the value should not be trusted
# as current. This is exactly finding #2 from the D1 Real-Provider
# Validation Checkpoint (a stale/delisted symbol can get a stale FMP quote
# rather than an error) generalized into the freshness taxonomy instead of
# living only as prose in a checkpoint doc.
FreshnessClass = Literal["real_time", "delayed_15", "end_of_day", "historical", "stale"]
DegradedReason = Literal["cached_forbidden", "circuit_open"]

# How old a quote-shaped result's OWN vendor-reported observation timestamp
# must be before it is classified "stale" rather than its normal tier.
# Deliberately coarse and NOT session-aware (a real market calendar --
# knowing today is a holiday, weekend, or half-day -- is a future S8/S11
# concern, not D1's): 5 days is comfortably longer than any weekend+holiday
# gap this program has to reason about (a Friday close before a Monday
# holiday reopens Tuesday, under 3.5 days), so a value older than this is
# evidence the symbol is not trading normally (delisted/halted/illiquid),
# not merely "the market happens to be closed right now."
STALE_AFTER_SECONDS = 5 * 86_400


def freshness_from_observed_age(
    observed_at: Optional[float], *, normal: FreshnessClass, now: Optional[float] = None,
) -> FreshnessClass:
    """Shared, evidence-based freshness classification used by every
    adapter's quote-shaped typed methods, so the "how stale is too stale"
    rule lives in exactly one place instead of drifting per-vendor. Returns
    `normal` (the vendor's documented/expected tier -- "real_time" for
    Massive, "delayed_15" for FMP) when `observed_at` is missing (nothing
    to evidence staleness with -- never fabricated) or recent; returns
    "stale" only when the vendor's OWN observation timestamp says so. This
    must never be driven by request recency -- "we just asked the vendor"
    is not evidence the underlying value is current, which is exactly the
    bug this same hardening pass fixed in `massive.get_quote` (it used to
    report freshness="real_time" regardless of what the vendor's status
    field said)."""
    if observed_at is None:
        return normal
    now = now if now is not None else time.time()
    if now - observed_at > STALE_AFTER_SECONDS:
        return "stale"
    return normal


@dataclass(frozen=True)
class ProvenanceRecord:
    """Spec §6.2, generalizing bar_provenance.py's narrower shape.

    `source_observed_at` (D1 hardening, 2026-09-02) is the vendor's OWN
    reported observation/last-trade timestamp for the value -- distinct
    from `fetched_at`, which is only when D1 made the request. This is the
    "source/market data time" vs "request time" distinction: a request
    made at 4:05pm ET for a stock that last traded at 4:00pm ET has a
    `fetched_at` five minutes newer than its `source_observed_at`, and
    that gap is real information, not noise. `None` when the vendor's
    response carries no such timestamp for this capability -- never
    backfilled from `fetched_at`, which would silently misrepresent
    request time as observation time."""
    vendor: str
    source_activity: str  # e.g. "fmp_client.get_key_metrics_ttm"
    fetched_at: float = field(default_factory=time.time)  # epoch; caller may override for tests
    tie_break: Optional[str] = None
    source_observed_at: Optional[float] = None


@dataclass(frozen=True)
class ProviderResult:
    """Spec §6.1/§6.4. `degraded` distinguishes a cached-forbidden or
    circuit-breaker default from a genuine vendor answer — never silently
    rendered as real data (PRD §9.4/§9.6, the "quiet market" anti-pattern
    this whole system exists to prevent). `degraded_since` is populated only
    when `degraded == "cached_forbidden"` (the original 403's timestamp,
    spec §6.4).

    `freshness=None` is a deliberate, documented state meaning "not
    established" (D1 hardening, 2026-09-02) -- distinct from every named
    FreshnessClass value, including "stale". A consumer (AI or otherwise)
    must read `None` as UNKNOWN, never coerce it to "real_time" or any
    other assumed default; "unknown" was intentionally not added as its
    own string literal since `None` already carries that meaning everywhere
    in this envelope (`Optional[FreshnessClass]`), and a redundant literal
    would just create two spellings of the same fact."""
    value: Any
    provenance: ProvenanceRecord
    licensing_class: str
    freshness: Optional[FreshnessClass] = None
    degraded: Optional[DegradedReason] = None
    degraded_since: Optional[float] = None

    def to_dict(self) -> dict:
        """AI/consumer-facing serialization (D1 hardening, 2026-09-02) --
        a stable, documented, JSON-safe shape so a future AI/intelligence
        surface doesn't need to know this is a dataclass or hand-roll
        `dataclasses.asdict`. Every field here is already a primitive/
        Optional[primitive], so this is a plain recursive-free conversion,
        not new machinery."""
        return {
            "value": self.value,
            "provenance": {
                "vendor": self.provenance.vendor,
                "source_activity": self.provenance.source_activity,
                "fetched_at": self.provenance.fetched_at,
                "tie_break": self.provenance.tie_break,
                "source_observed_at": self.provenance.source_observed_at,
            },
            "licensing_class": self.licensing_class,
            "freshness": self.freshness,
            "degraded": self.degraded,
            "degraded_since": self.degraded_since,
        }
