"""TERM-061 (FB-X2-01) — the member API endpoint whitelist, GENERATED from the live route table.

FB-X2-01: *"publish a skill file with an endpoint whitelist, because the whitelist is the
load-bearing half"* — it exists to stop somebody else's agent inventing endpoints. Its named
anti-pattern is DOC-1: *"a whitelist is a roster, and it must be generated from the registry,
or it becomes the thing it exists to prevent."* So nothing here is typed: every entry is derived
from `api.main:app`'s routes, `auth_surface_check`'s guard walk, the open-reads gate's table and
the rate-limit families.

An entry is a member-callable READ:
  * method GET, under `/api/`, outside the excluded prefixes below (admin, auth, streams, render
    pages, webhooks, the push door) — none of those is a member data read an agent should call;
  * gated at MEMBER or PAID level — `require_paid` ⇒ `paid`; `get_current_user` and the other
    member guards ⇒ `member`; or the open-reads gate's own table says paid/member. An ADMIN or
    machine-secret guard anywhere in the tree excludes the route. An OPEN route is excluded: the
    spec makes egress over unauthenticated routes a redistribution question, not a feature;
  * declared in a rate-limit family (FB-S9-03 is this item's hard gate: "limits before any
    programmatic client"). A route with no family is excluded and reported, never listed.

Each entry carries the `tier` the caller must hold — the entitlement-inheritance rule ("your
assistant can only retrieve what you could retrieve yourself"): an agent acting for a member
gets exactly the member's own session's access, so the tier is what that member needs.

⛔ UNPUBLISHED by owner ruling (2026-09-29): the artefacts live in `docs/api/`, are served by no
route, and no MCP surface exists. `tests/test_skill_whitelist.py` holds the committed files equal
to what this module generates, so the list cannot drift from the code.
"""
from __future__ import annotations

import json
import re

EXCLUDED_PREFIXES = (
    "/api/admin", "/api/auth", "/api/stream", "/api/r/", "/api/webhooks", "/api/push",
    "/api/desk/zoom-webhook", "/api/debug",
)

#: Member-gated reads that still do not belong in an AGENT's whitelist, each with its reason.
#: Matched against the route template. A new route matching one of these is excluded by rule,
#: not by a hand-typed path list.
EXCLUDED_PATTERNS = (
    (r"token", "credential or capability-link surface (minting, listing, or a secret in the path)"),
    (r"/capture/connections|/connectors", "linked-account management, not a data read"),
    (r"-debug(/|$)", "diagnostic route"),
)

ADMIN_GUARDS = {"require_admin", "require_flow_admin", "verify_push_secret", "require_push_secret"}
PAID_GUARDS = {"require_paid"}
MEMBER_GUARDS = {"get_current_user", "require_flow_user", "require_bars_access", "require_article_reader"}


def _tier(route, path: str) -> str | None:
    from api import auth_surface_check as asc
    from api import open_reads_gate as org

    guards = asc._guard_names_for(route)
    if guards & ADMIN_GUARDS:
        return None
    if guards & PAID_GUARDS:
        return "paid"
    if guards & MEMBER_GUARDS:
        return "member"
    if asc.READ_GATE_NAME in guards:
        fam = org.family_of(path)
        if fam in ("paid", "member"):
            return fam
    return None


def build(app) -> dict:
    """`{"entries": [...], "excluded_no_rate_family": [...]}` — sorted, deterministic."""
    from api import rate_limit_policy as rlp

    entries, no_family = [], []
    seen = set()
    for route in getattr(app, "routes", []):
        path = getattr(route, "path", "") or ""
        methods = getattr(route, "methods", None) or set()
        if "GET" not in methods or not path.startswith("/api/"):
            continue
        if path.startswith(EXCLUDED_PREFIXES) or (path in seen):
            continue
        if any(re.search(pat, path, re.I) for pat, _why in EXCLUDED_PATTERNS):
            continue
        tier = _tier(route, path)
        if tier is None:
            continue
        hit = rlp.classify(path)
        if hit is None:
            no_family.append(path)
            continue
        seen.add(path)
        entries.append({"method": "GET", "path": path, "tier": tier, "rate_limit_family": hit[1]})
    entries.sort(key=lambda e: e["path"])
    return {"entries": entries, "excluded_no_rate_family": sorted(set(no_family))}


def to_json(data: dict) -> str:
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def to_skill_md(data: dict) -> str:
    lines = [
        "# UCT Intelligence — member API skill file (UNPUBLISHED)",
        "",
        "Generated by `api/services/skill_whitelist.py` from the live route table; do not edit by hand.",
        "Regenerate with `UPDATE_SKILL_WHITELIST=1 python -m pytest tests/test_skill_whitelist.py`.",
        "",
        "## Rules for an agent",
        "",
        "- Call ONLY the endpoints listed below. If a question needs an endpoint that is not on this list,",
        "  say it is not available — never guess or construct a path.",
        "- You act with the member's own session: you can read only what that member can read. A `paid`",
        "  endpoint answers 402 to a member without a paid plan; report that, do not retry elsewhere.",
        "- Every endpoint is rate limited per member; on 429 wait for the `Retry-After` header.",
        "",
        f"## Endpoints ({len(data['entries'])})",
        "",
        "| method | path | tier | rate-limit family |",
        "|---|---|---|---|",
    ]
    for e in data["entries"]:
        lines.append(f"| {e['method']} | `{e['path']}` | {e['tier']} | {e['rate_limit_family']} |")
    lines.append("")
    return "\n".join(lines)
