"""BRK-04 (roadmap RM-L04) — Web Push as an alert channel. W3C Push API + VAPID.

Owner ruling 2026-10-02: "Yes, build it." A member who turns on *Push
notifications to this device* in Settings › Notifications is told about an
alert on that device even with no UCT tab open.

WHAT THIS MODULE OWNS
=====================
  • the ``web_push_subscriptions`` table in auth.db (one row per DEVICE endpoint);
  • subscribe / unsubscribe / list, OWNER-scoped (every statement carries ``user_id``);
  • ``dispatch(user_id, ...)`` — the channel, called by
    ``watchlist_alert_service`` AFTER the in-app/email/Discord channels;
  • the two pieces of crypto the protocol needs, on ``cryptography`` (already a
    pinned requirement): the VAPID ES256 JWT (RFC 8292) and the ``aes128gcm``
    payload encryption (RFC 8291 + RFC 8188). ⭐ NO NEW DEPENDENCY — ``pywebpush``
    is not in requirements.txt, and the two RFCs are ~60 lines on a library we
    already ship. ``tests/test_web_push.py`` pins the encryption to RFC 8291's
    own Appendix A test vector, byte for byte.

⛔ THE CHANNEL MUST NEVER BLOCK OR RAISE INTO THE ALERT PATH
==========================================================
``dispatch`` reads two env vars and, only when both the flag and the keys are
present, SUBMITS a job to this module's own two-thread executor and returns.
The subscription read, the encryption and every HTTP POST happen on that
executor — never on the thread that is delivering the alert (which may be the
live-price poll's worker). Every failure is caught and logged; nothing
propagates. ⛔ The push outcome is deliberately NOT a channel in
``_delivery_report``: it is not known when the report is built, and the report's
``channels_ok`` count decides whether S7 leases are released — a channel that
cannot answer in time must not be allowed to vote.

DARK: ``WEB_PUSH_ENABLED`` (read per call, unset = off). Off ⇒ the routes 404
before identity, ``dispatch`` returns before touching the database, and no
executor thread is ever created.

INERT WITHOUT KEYS: ``WEB_PUSH_VAPID_PUBLIC_KEY`` / ``WEB_PUSH_VAPID_PRIVATE_KEY``
/ ``WEB_PUSH_VAPID_SUBJECT``. Missing (or a public key that is not the private
key's) ⇒ the channel does nothing and says so in ONE log line per process.
Keys are generated by ``tools/gen_vapid_keys.py`` and are never committed.

⛔ SSRF: the server POSTs to a URL a member's browser handed it, so the endpoint
host must belong to a known push service (``PUSH_SERVICE_HOST_SUFFIXES``).
"""
from __future__ import annotations

import base64
import hashlib
import hmac
import json
import logging
import os
import struct
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from typing import Optional
from urllib.parse import urlsplit

_logger = logging.getLogger(__name__)

ENABLED_ENV = "WEB_PUSH_ENABLED"
PUBLIC_KEY_ENV = "WEB_PUSH_VAPID_PUBLIC_KEY"
PRIVATE_KEY_ENV = "WEB_PUSH_VAPID_PRIVATE_KEY"
SUBJECT_ENV = "WEB_PUSH_VAPID_SUBJECT"

#: Devices one member may register. The oldest is dropped past this — a member
#: who reinstalls a browser ten times leaves ten dead endpoints otherwise.
MAX_SUBSCRIPTIONS_PER_USER = 10
#: Push services cap the encrypted body at 4096 bytes; the record overhead is
#: 86 (header) + 17 (delimiter + tag), so the JSON payload is kept well under.
MAX_PAYLOAD_BYTES = 3000
RECORD_SIZE = 4096
TTL_SECONDS = 24 * 3600
HTTP_TIMEOUT_SECONDS = 10

#: Host suffixes of the push services the four browser engines use. Chrome/Edge
#: (FCM), Firefox (autopush), Safari/iOS (APNs web push), legacy Edge (WNS).
PUSH_SERVICE_HOST_SUFFIXES = (
    "fcm.googleapis.com",
    "push.services.mozilla.com",
    "push.apple.com",
    "notify.windows.com",
)

_SCHEMA = """
CREATE TABLE IF NOT EXISTS web_push_subscriptions (
  endpoint_hash TEXT    PRIMARY KEY,
  user_id       TEXT    NOT NULL,
  endpoint      TEXT    NOT NULL,
  p256dh        TEXT    NOT NULL,
  auth          TEXT    NOT NULL,
  created_at    INTEGER NOT NULL,
  last_sent_at  INTEGER,
  last_status   INTEGER
);
CREATE INDEX IF NOT EXISTS idx_web_push_subscriptions_user
  ON web_push_subscriptions(user_id);
"""


def is_enabled() -> bool:
    """Read PER CALL. Unset means OFF."""
    return os.environ.get(ENABLED_ENV, "0").strip().lower() in ("1", "true", "yes", "on")


# ── base64url ────────────────────────────────────────────────────────────────

def b64u_encode(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


def b64u_decode(s: str) -> bytes:
    s = (s or "").strip()
    return base64.urlsafe_b64decode(s + "=" * (-len(s) % 4))


# ── VAPID config ─────────────────────────────────────────────────────────────

_inert_logged = False
_inert_lock = threading.Lock()


def _log_inert_once(reason: str) -> None:
    global _inert_logged
    with _inert_lock:
        if _inert_logged:
            return
        _inert_logged = True
    _logger.warning("web push is INERT: %s (run tools/gen_vapid_keys.py and set "
                    "%s / %s / %s)", reason, PUBLIC_KEY_ENV, PRIVATE_KEY_ENV, SUBJECT_ENV)


def _private_key_from_b64(raw_b64: str):
    from cryptography.hazmat.primitives.asymmetric import ec
    d = int.from_bytes(b64u_decode(raw_b64), "big")
    return ec.derive_private_key(d, ec.SECP256R1())


def _public_raw(key) -> bytes:
    from cryptography.hazmat.primitives import serialization
    return key.public_key().public_bytes(serialization.Encoding.X962,
                                         serialization.PublicFormat.UncompressedPoint)


def vapid_config() -> Optional[dict]:
    """The three VAPID settings, validated, or None (and one log line) when the
    channel cannot work. Read per call so a Railway var change needs no code path
    beyond a restart, and blanking a key turns the channel off."""
    pub = os.environ.get(PUBLIC_KEY_ENV, "").strip()
    priv = os.environ.get(PRIVATE_KEY_ENV, "").strip()
    sub = os.environ.get(SUBJECT_ENV, "").strip()
    if not (pub and priv and sub):
        _log_inert_once("VAPID keys/subject unset")
        return None
    if not (sub.startswith("mailto:") or sub.startswith("https://")):
        _log_inert_once(f"{SUBJECT_ENV} must start with mailto: or https://")
        return None
    try:
        key = _private_key_from_b64(priv)
        if _public_raw(key) != b64u_decode(pub):
            _log_inert_once(f"{PUBLIC_KEY_ENV} is not the public half of {PRIVATE_KEY_ENV}")
            return None
    except Exception as e:  # malformed key material
        _log_inert_once(f"VAPID key unreadable ({type(e).__name__})")
        return None
    return {"public_key": pub, "private_key": key, "subject": sub}


def vapid_jwt(endpoint: str, private_key, subject: str, now: Optional[int] = None) -> str:
    """RFC 8292 §2: an ES256 JWT whose audience is the push service's origin."""
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature
    parts = urlsplit(endpoint)
    claims = {"aud": f"{parts.scheme}://{parts.netloc}",
              "exp": int(now if now is not None else time.time()) + 12 * 3600,
              "sub": subject}
    header = {"typ": "JWT", "alg": "ES256"}
    signing_input = (b64u_encode(json.dumps(header, separators=(",", ":")).encode())
                     + "." + b64u_encode(json.dumps(claims, separators=(",", ":")).encode()))
    der = private_key.sign(signing_input.encode("ascii"), ec.ECDSA(hashes.SHA256()))
    r, s = decode_dss_signature(der)
    return signing_input + "." + b64u_encode(r.to_bytes(32, "big") + s.to_bytes(32, "big"))


# ── RFC 8291 payload encryption (aes128gcm, RFC 8188) ────────────────────────

def _hkdf_extract(salt: bytes, ikm: bytes) -> bytes:
    return hmac.new(salt, ikm, hashlib.sha256).digest()


def _hkdf_expand(prk: bytes, info: bytes, length: int) -> bytes:
    # length <= 32 everywhere here, so one block of HKDF-Expand is the whole output.
    return hmac.new(prk, info + b"\x01", hashlib.sha256).digest()[:length]


def encrypt(plaintext: bytes, ua_public_b64: str, auth_secret_b64: str, *,
            _as_private=None, _salt: Optional[bytes] = None) -> bytes:
    """Encrypt one push message body for one subscription (RFC 8291 §3.4).

    ``_as_private`` / ``_salt`` exist ONLY so the RFC's Appendix A vector can be
    reproduced; production always draws a fresh ephemeral key and salt."""
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    ua_public = b64u_decode(ua_public_b64)
    auth_secret = b64u_decode(auth_secret_b64)
    if len(ua_public) != 65 or len(auth_secret) != 16:
        raise ValueError("subscription keys are malformed")
    as_private = _as_private or ec.generate_private_key(ec.SECP256R1())
    as_public = _public_raw(as_private)
    ua_key = ec.EllipticCurvePublicKey.from_encoded_point(ec.SECP256R1(), ua_public)
    ecdh_secret = as_private.exchange(ec.ECDH(), ua_key)
    prk_key = _hkdf_extract(auth_secret, ecdh_secret)
    ikm = _hkdf_expand(prk_key, b"WebPush: info\x00" + ua_public + as_public, 32)
    salt = _salt if _salt is not None else os.urandom(16)
    prk = _hkdf_extract(salt, ikm)
    cek = _hkdf_expand(prk, b"Content-Encoding: aes128gcm\x00", 16)
    nonce = _hkdf_expand(prk, b"Content-Encoding: nonce\x00", 12)
    if len(plaintext) + 1 + 16 > RECORD_SIZE:
        raise ValueError("payload too large for one record")
    ciphertext = AESGCM(cek).encrypt(nonce, plaintext + b"\x02", None)
    header = salt + struct.pack("!IB", RECORD_SIZE, len(as_public)) + as_public
    return header + ciphertext


# ── subscriptions (auth.db) ──────────────────────────────────────────────────

_ensured: set = set()


def _conn():
    from api.services import auth_db
    conn = auth_db.get_connection()
    key = auth_db._DB_PATH
    if key not in _ensured:
        conn.executescript(_SCHEMA)
        _ensured.add(key)
    return conn


def endpoint_allowed(endpoint: str) -> bool:
    try:
        parts = urlsplit(endpoint or "")
    except ValueError:
        return False
    host = (parts.hostname or "").lower()
    if parts.scheme != "https" or not host or parts.username or parts.password:
        return False
    if parts.port not in (None, 443):
        return False
    return any(host == s or host.endswith("." + s) for s in PUSH_SERVICE_HOST_SUFFIXES)


def _hash(endpoint: str) -> str:
    return hashlib.sha256(endpoint.encode("utf-8")).hexdigest()[:40]


def subscribe(user_id, endpoint: str, p256dh: str, auth: str) -> dict:
    """Register (or move) one device endpoint to ``user_id``.

    An endpoint is a DEVICE, so it belongs to whoever subscribed it last: a
    shared browser that a second member signs into must stop telling the first
    one's alerts to the second one. Raises ValueError on a bad subscription."""
    uid = str(user_id or "").strip()
    if not uid:
        raise ValueError("a subscription needs a member")
    if not endpoint_allowed(endpoint):
        raise ValueError("endpoint is not a known push service")
    if len(endpoint) > 2048:
        raise ValueError("endpoint too long")
    try:
        if len(b64u_decode(p256dh)) != 65 or len(b64u_decode(auth)) != 16:
            raise ValueError
    except Exception:
        raise ValueError("subscription keys are malformed") from None
    h = _hash(endpoint)
    with _conn() as conn:
        conn.execute(
            "INSERT INTO web_push_subscriptions "
            "(endpoint_hash, user_id, endpoint, p256dh, auth, created_at) VALUES (?,?,?,?,?,?) "
            "ON CONFLICT(endpoint_hash) DO UPDATE SET user_id=excluded.user_id, "
            "p256dh=excluded.p256dh, auth=excluded.auth, created_at=excluded.created_at",
            (h, uid, endpoint, p256dh, auth, int(time.time())))
        conn.execute(
            "DELETE FROM web_push_subscriptions WHERE user_id=? AND endpoint_hash NOT IN ("
            " SELECT endpoint_hash FROM web_push_subscriptions WHERE user_id=?"
            " ORDER BY created_at DESC, rowid DESC LIMIT ?)",
            (uid, uid, MAX_SUBSCRIPTIONS_PER_USER))
    return {"subscribed": True}


def unsubscribe(user_id, endpoint: str) -> bool:
    with _conn() as conn:
        cur = conn.execute(
            "DELETE FROM web_push_subscriptions WHERE user_id=? AND endpoint_hash=?",
            (str(user_id), _hash(endpoint or "")))
        return cur.rowcount > 0


def list_subscriptions(user_id) -> list[dict]:
    with _conn() as conn:
        rows = conn.execute(
            "SELECT endpoint_hash, endpoint, p256dh, auth FROM web_push_subscriptions "
            "WHERE user_id=? ORDER BY created_at", (str(user_id),)).fetchall()
    return [dict(r) for r in rows]


def _prune(endpoint_hash: str) -> None:
    with _conn() as conn:
        conn.execute("DELETE FROM web_push_subscriptions WHERE endpoint_hash=?", (endpoint_hash,))


def _stamp(endpoint_hash: str, status: int) -> None:
    with _conn() as conn:
        conn.execute("UPDATE web_push_subscriptions SET last_sent_at=?, last_status=? "
                     "WHERE endpoint_hash=?", (int(time.time()), int(status), endpoint_hash))


# ── delivery ─────────────────────────────────────────────────────────────────

def build_payload(title: str, body: str, url: Optional[str] = None,
                  tag: Optional[str] = None) -> bytes:
    """The JSON the service worker reads. Truncated, never refused: an alert too
    long for a push still deserves a push that says something."""
    t = str(title or "UCT alert")[:120]
    b = str(body or "")[:400]
    u = url if isinstance(url, str) and url.startswith("/") and not url.startswith("//") else "/"
    doc = {"title": t, "body": b, "url": u[:300]}
    if tag:
        doc["tag"] = str(tag)[:64]
    raw = json.dumps(doc, separators=(",", ":")).encode("utf-8")
    while len(raw) > MAX_PAYLOAD_BYTES and doc["body"]:
        doc["body"] = doc["body"][: len(doc["body"]) // 2]
        raw = json.dumps(doc, separators=(",", ":")).encode("utf-8")
    return raw


def _post(endpoint: str, body: bytes, headers: dict) -> int:
    import requests
    return requests.post(endpoint, data=body, headers=headers,
                         timeout=HTTP_TIMEOUT_SECONDS).status_code


def send_to_user(user_id, payload: bytes, config: dict) -> dict:
    """Send one payload to every device of one member. Runs on the executor.

    A 404/410 from the push service means the subscription is gone for good
    (RFC 8030 §7.3): the row is deleted. Anything else is stamped and kept."""
    sent = pruned = failed = 0
    for sub in list_subscriptions(user_id):
        ep, h = sub["endpoint"], sub["endpoint_hash"]
        try:
            if not endpoint_allowed(ep):
                _prune(h)
                pruned += 1
                continue
            body = encrypt(payload, sub["p256dh"], sub["auth"])
            headers = {
                "Authorization": f"vapid t={vapid_jwt(ep, config['private_key'], config['subject'])}, "
                                 f"k={config['public_key']}",
                "Content-Encoding": "aes128gcm",
                "Content-Type": "application/octet-stream",
                "TTL": str(TTL_SECONDS),
                "Urgency": "high",
            }
            status = _post(ep, body, headers)
            if status in (404, 410):
                _prune(h)
                pruned += 1
            elif 200 <= status < 300:
                _stamp(h, status)
                sent += 1
            else:
                _stamp(h, status)
                failed += 1
                _logger.warning("web push: %s answered %s", urlsplit(ep).hostname, status)
        except Exception as e:
            failed += 1
            _logger.warning("web push: send failed (%s: %s)", type(e).__name__, e)
    return {"sent": sent, "pruned": pruned, "failed": failed}


_executor: Optional[ThreadPoolExecutor] = None
_executor_lock = threading.Lock()


def _get_executor() -> ThreadPoolExecutor:
    global _executor
    with _executor_lock:
        if _executor is None:
            _executor = ThreadPoolExecutor(max_workers=2, thread_name_prefix="web-push")
        return _executor


def _job(user_id, payload: bytes, config: dict) -> None:
    try:
        send_to_user(user_id, payload, config)
    except Exception as e:
        _logger.warning("web push: job failed (%s: %s)", type(e).__name__, e)


def dispatch(user_id, title: str, body: str, url: Optional[str] = None,
             tag: Optional[str] = None) -> bool:
    """THE CHANNEL. Queue one alert for every device of ``user_id`` and return.

    Never raises, never blocks on I/O: off ⇒ False before anything is read;
    inert (no keys) ⇒ False with one log line per process; otherwise the work
    is submitted to this module's executor and True means *queued*, not sent."""
    try:
        if not is_enabled() or not user_id:
            return False
        config = vapid_config()
        if config is None:
            return False
        payload = build_payload(title, body, url, tag)
        _get_executor().submit(_job, user_id, payload, config)
        return True
    except Exception as e:
        _logger.warning("web push: dispatch failed (%s: %s)", type(e).__name__, e)
        return False
