"""Wave K Slice 1 — cross-implementation rail for the canonical note text.

⛔ THE WHOLE POINT: this does NOT test my Python against my own reading of the
ProseMirror spec. The fixtures in `fixtures_pm_citation_text.json` were
GENERATED BY THE REAL `prosemirror-model` PACKAGE (see the generator recorded
in the Slice 1 commit) -- `doc.textBetween(0, size, '\n')` for the text, and
`doc.descendants()` for every text node's true position. The Python
implementation is asserted to reproduce both, exactly.

That matters because this is the identical failure shape Wave J shipped:
`_buildPageText` (pdf.js) and pypdf independently produced "the page's text",
they disagreed by a newline, and every anchor silently landed null. Here the
backend computes citation locations and the frontend resolves them, so the
same disagreement would silently mis-navigate every citation. A rail that
compared Python to Python could not see it.

Regenerate the fixtures (from app/, so module resolution finds the package):
    NODE_PATH="$PWD/node_modules" node <generator> > ../tests/fixtures_pm_citation_text.json
"""
from __future__ import annotations

import io
import json
from pathlib import Path

import pytest

from api.services.journal_two.note_citation_text import (
    flatten,
    locate,
    pm_range,
)
from api.services.journal_two.notes import extract_plain_text

_FIXTURES = json.loads(
    io.open(Path(__file__).with_name("fixtures_pm_citation_text.json"), encoding="utf-8").read()
)


@pytest.mark.parametrize("case", sorted(_FIXTURES))
def test_python_reproduces_prosemirrors_own_canonical_text(case):
    fx = _FIXTURES[case]
    assert flatten(fx["json"])["text"] == fx["text"], (
        f"{case}: Python flattening disagrees with prosemirror-model's "
        f"textBetween -- the Wave J pdf.js/pypdf failure shape"
    )


@pytest.mark.parametrize("case", sorted(_FIXTURES))
def test_python_reproduces_prosemirrors_own_text_node_positions(case):
    fx = _FIXTURES[case]
    got = [(s["pm_start"], s["pm_end"]) for s in flatten(fx["json"])["spans"] if not s["is_atom"]]
    want = [(s["pm_start"], s["pm_end"]) for s in fx["textSpans"]]
    assert got == want, f"{case}: text-node ProseMirror positions disagree"


@pytest.mark.parametrize("case", sorted(_FIXTURES))
def test_every_span_slices_back_to_its_own_text(case):
    fx = _FIXTURES[case]
    flat = flatten(fx["json"])
    for s in flat["spans"]:
        if s["is_atom"]:
            continue
        assert flat["text"][s["flat_start"]:s["flat_end"]]


class TestMarkTransparency:
    """The Slice 0 finding, closed. A phrase crossing a mark boundary is
    genuinely present in the note and MUST be locatable."""

    def test_a_phrase_crossing_a_bold_boundary_is_found_and_mapped(self):
        doc = _FIXTURES["markBoundary"]["json"]
        hits = locate(doc, "expects gross margins to normalize")
        assert len(hits) == 1, "the exact phrase Slice 0 proved unresolvable"
        # And it maps to a real ProseMirror range spanning the boundary.
        assert hits[0]["to"] > hits[0]["from"]

    def test_a_phrase_crossing_a_link_boundary_is_found(self):
        assert len(locate(_FIXTURES["linkAcross"]["json"], "see the filing for")) == 1

    def test_a_phrase_crossing_several_adjacent_marks_is_found(self):
        # a|b(bold)|c(italic)|d(bold+italic)|e -- four boundaries in five chars.
        assert len(locate(_FIXTURES["adjacentMarks"]["json"], "abcde")) == 1

    def test_the_mapped_range_covers_exactly_the_phrase_in_pm_coordinates(self):
        doc = _FIXTURES["markBoundary"]["json"]
        flat = flatten(doc)
        needle = "gross margins to normalize"
        start = flat["text"].index(needle)
        rng = pm_range(start, start + len(needle), flat["spans"])
        # PM positions are 1-based inside the first paragraph, so the width of
        # the range equals the character length of the phrase -- no mark tokens
        # are counted, which is the property that makes this work at all.
        assert rng["to"] - rng["from"] == len(needle)


class TestBlockSeparators:
    def test_block_boundaries_become_a_newline_not_a_space(self):
        assert flatten(_FIXTURES["twoParas"]["json"])["text"] == "First para.\nSecond para."

    def test_a_phrase_cannot_be_matched_across_a_block_boundary_by_accident(self):
        # "para.Second" must not exist -- if blocks were joined with nothing,
        # retrieval would invent phrases spanning unrelated paragraphs.
        assert "para.Second" not in flatten(_FIXTURES["twoParas"]["json"])["text"]

    def test_nested_list_items_each_get_their_own_line(self):
        text = flatten(_FIXTURES["nestedList"]["json"])["text"]
        assert text == "Risks:\nChina exposure\nCustomer concentration"

    def test_a_range_inside_a_separator_maps_to_no_position(self):
        flat = flatten(_FIXTURES["twoParas"]["json"])
        sep = flat["text"].index("\n")
        assert pm_range(sep, sep + 1, flat["spans"]) is None


class TestAmbiguity:
    def test_a_duplicate_phrase_reports_every_occurrence_rather_than_the_first(self):
        # Slice 0 recorded silent first-match as a defect. Ambiguity must be
        # visible to the caller so the citation can degrade honestly.
        hits = locate(_FIXTURES["duplicatePhrase"]["json"], "Revenue")
        assert len(hits) == 2
        assert hits[0]["from"] != hits[1]["from"]

    def test_a_phrase_absent_from_the_note_yields_no_location(self):
        assert locate(_FIXTURES["simple"]["json"], "never written here") == []

    def test_an_empty_needle_yields_no_location_rather_than_everything(self):
        assert locate(_FIXTURES["simple"]["json"], "") == []


class TestDivergenceFromBodyPlain:
    """Proves WHY this module exists, so nobody later 'unifies' the two."""

    def test_body_plain_inserts_spaces_at_mark_boundaries_and_this_does_not(self):
        doc = _FIXTURES["markBoundary"]["json"]
        assert "  " in extract_plain_text(doc), (
            "body_plain is expected to double-space at mark boundaries"
        )
        assert "  " not in flatten(doc)["text"]

    def test_the_canonical_text_matches_what_a_member_reads(self):
        doc = _FIXTURES["markBoundary"]["json"]
        assert flatten(doc)["text"] == "Management expects gross margins to normalize lower."

    def test_offsets_into_body_plain_would_address_the_wrong_characters(self):
        # The concrete consequence: same phrase, different offset in each
        # representation. A citation built on body_plain offsets would point
        # somewhere else in the rendered note.
        doc = _FIXTURES["markBoundary"]["json"]
        needle = "to normalize lower."
        assert extract_plain_text(doc).index(needle) != flatten(doc)["text"].index(needle)


class TestRobustness:
    @pytest.mark.parametrize("bad", [None, "", 42, [], {"type": "doc"}])
    def test_malformed_docs_degrade_instead_of_raising(self, bad):
        out = flatten(bad)
        assert out["text"] == "" and out["spans"] == []

    def test_non_dict_attrs_do_not_crash_the_walk(self):
        # The permissive body validator and the importer both round-trip
        # arbitrary JSON; notes.extract_plain_text carries the same guard.
        doc = {"type": "doc", "content": [
            {"type": "paragraph", "attrs": ["not", "a", "dict"],
             "content": [{"type": "text", "text": "ok"}]}]}
        assert flatten(doc)["text"] == "ok"

    def test_an_atom_occupies_one_position_however_long_it_reads(self):
        doc = {"type": "doc", "content": [{"type": "paragraph", "content": [
            {"type": "text", "text": "a"},
            {"type": "attachmentChip", "attrs": {"name": "a-very-long-filename.pdf"}},
            {"type": "text", "text": "b"}]}]}
        flat = flatten(doc)
        atom = [s for s in flat["spans"] if s["is_atom"]][0]
        assert atom["pm_end"] - atom["pm_start"] == 1
        assert flat["text"] == "a[file: a-very-long-filename.pdf]b"
