"""Wave K Slice 1 — cross-implementation rail for the canonical note text.

⛔ THE WHOLE POINT: this does NOT test my Python against my own reading of the
ProseMirror spec. The fixtures in `fixtures_pm_citation_text.json` were
GENERATED BY THE REAL `prosemirror-model` PACKAGE
(tools/gen_pm_citation_fixtures.cjs) --
`doc.textBetween(0, size, '\n', citationLeafText)` for the text, with the leaf
text function imported from the client (askCitation.js), and
`doc.descendants()` for every text node's and every text-reading leaf's true
position. The Python implementation is asserted to reproduce all three,
exactly.

That matters because this is the identical failure shape Wave J shipped:
`_buildPageText` (pdf.js) and pypdf independently produced "the page's text",
they disagreed by a newline, and every anchor silently landed null. Here the
backend computes citation locations and the frontend resolves them, so the
same disagreement would silently mis-navigate every citation. A rail that
compared Python to Python could not see it.

Regenerate the fixtures (from app/, so module resolution finds the package):
    NODE_PATH="$PWD/node_modules" node ../tools/gen_pm_citation_fixtures.cjs > ../tests/fixtures_pm_citation_text.json
"""
from __future__ import annotations

import io
import json
from pathlib import Path

import pytest

from api.services.journal_two.note_citation_text import (
    flatten,
    locate,
    pm_range,
)
from api.services.journal_two.notes import extract_plain_text

_FIXTURES = json.loads(
    io.open(Path(__file__).with_name("fixtures_pm_citation_text.json"), encoding="utf-8").read()
)


@pytest.mark.parametrize("case", sorted(_FIXTURES))
def test_python_reproduces_prosemirrors_own_canonical_text(case):
    fx = _FIXTURES[case]
    assert flatten(fx["json"])["text"] == fx["text"], (
        f"{case}: Python flattening disagrees with prosemirror-model's "
        f"textBetween -- the Wave J pdf.js/pypdf failure shape"
    )


@pytest.mark.parametrize("case", sorted(_FIXTURES))
def test_python_reproduces_prosemirrors_own_text_node_positions(case):
    fx = _FIXTURES[case]
    got = [(s["pm_start"], s["pm_end"]) for s in flatten(fx["json"])["spans"] if not s["is_atom"]]
    want = [(s["pm_start"], s["pm_end"]) for s in fx["textSpans"]]
    assert got == want, f"{case}: text-node ProseMirror positions disagree"


@pytest.mark.parametrize("case", sorted(_FIXTURES))
def test_every_span_slices_back_to_its_own_text(case):
    fx = _FIXTURES[case]
    flat = flatten(fx["json"])
    for s in flat["spans"]:
        if s["is_atom"]:
            continue
        assert flat["text"][s["flat_start"]:s["flat_end"]]


class TestMarkTransparency:
    """The Slice 0 finding, closed. A phrase crossing a mark boundary is
    genuinely present in the note and MUST be locatable."""

    def test_a_phrase_crossing_a_bold_boundary_is_found_and_mapped(self):
        doc = _FIXTURES["markBoundary"]["json"]
        hits = locate(doc, "expects gross margins to normalize")
        assert len(hits) == 1, "the exact phrase Slice 0 proved unresolvable"
        # And it maps to a real ProseMirror range spanning the boundary.
        assert hits[0]["to"] > hits[0]["from"]

    def test_a_phrase_crossing_a_link_boundary_is_found(self):
        assert len(locate(_FIXTURES["linkAcross"]["json"], "see the filing for")) == 1

    def test_a_phrase_crossing_several_adjacent_marks_is_found(self):
        # a|b(bold)|c(italic)|d(bold+italic)|e -- four boundaries in five chars.
        assert len(locate(_FIXTURES["adjacentMarks"]["json"], "abcde")) == 1

    def test_the_mapped_range_covers_exactly_the_phrase_in_pm_coordinates(self):
        doc = _FIXTURES["markBoundary"]["json"]
        flat = flatten(doc)
        needle = "gross margins to normalize"
        start = flat["text"].index(needle)
        rng = pm_range(start, start + len(needle), flat["spans"])
        # PM positions are 1-based inside the first paragraph, so the width of
        # the range equals the character length of the phrase -- no mark tokens
        # are counted, which is the property that makes this work at all.
        assert rng["to"] - rng["from"] == len(needle)


class TestBlockSeparators:
    def test_block_boundaries_become_a_newline_not_a_space(self):
        assert flatten(_FIXTURES["twoParas"]["json"])["text"] == "First para.\nSecond para."

    def test_a_phrase_cannot_be_matched_across_a_block_boundary_by_accident(self):
        # "para.Second" must not exist -- if blocks were joined with nothing,
        # retrieval would invent phrases spanning unrelated paragraphs.
        assert "para.Second" not in flatten(_FIXTURES["twoParas"]["json"])["text"]

    def test_nested_list_items_each_get_their_own_line(self):
        text = flatten(_FIXTURES["nestedList"]["json"])["text"]
        assert text == "Risks:\nChina exposure\nCustomer concentration"

    def test_a_range_inside_a_separator_maps_to_no_position(self):
        flat = flatten(_FIXTURES["twoParas"]["json"])
        sep = flat["text"].index("\n")
        assert pm_range(sep, sep + 1, flat["spans"]) is None


class TestAmbiguity:
    def test_a_duplicate_phrase_reports_every_occurrence_rather_than_the_first(self):
        # Slice 0 recorded silent first-match as a defect. Ambiguity must be
        # visible to the caller so the citation can degrade honestly.
        hits = locate(_FIXTURES["duplicatePhrase"]["json"], "Revenue")
        assert len(hits) == 2
        assert hits[0]["from"] != hits[1]["from"]

    def test_a_phrase_absent_from_the_note_yields_no_location(self):
        assert locate(_FIXTURES["simple"]["json"], "never written here") == []

    def test_an_empty_needle_yields_no_location_rather_than_everything(self):
        assert locate(_FIXTURES["simple"]["json"], "") == []


class TestDivergenceFromBodyPlain:
    """Proves WHY this module exists, so nobody later 'unifies' the two."""

    def test_body_plain_inserts_spaces_at_mark_boundaries_and_this_does_not(self):
        doc = _FIXTURES["markBoundary"]["json"]
        assert "  " in extract_plain_text(doc), (
            "body_plain is expected to double-space at mark boundaries"
        )
        assert "  " not in flatten(doc)["text"]

    def test_the_canonical_text_matches_what_a_member_reads(self):
        doc = _FIXTURES["markBoundary"]["json"]
        assert flatten(doc)["text"] == "Management expects gross margins to normalize lower."

    def test_offsets_into_body_plain_would_address_the_wrong_characters(self):
        # The concrete consequence: same phrase, different offset in each
        # representation. A citation built on body_plain offsets would point
        # somewhere else in the rendered note.
        doc = _FIXTURES["markBoundary"]["json"]
        needle = "to normalize lower."
        assert extract_plain_text(doc).index(needle) != flatten(doc)["text"].index(needle)


class TestRobustness:
    @pytest.mark.parametrize("bad", [None, "", 42, [], {"type": "doc"}])
    def test_malformed_docs_degrade_instead_of_raising(self, bad):
        out = flatten(bad)
        assert out["text"] == "" and out["spans"] == []

    def test_non_dict_attrs_do_not_crash_the_walk(self):
        # The permissive body validator and the importer both round-trip
        # arbitrary JSON; notes.extract_plain_text carries the same guard.
        doc = {"type": "doc", "content": [
            {"type": "paragraph", "attrs": ["not", "a", "dict"],
             "content": [{"type": "text", "text": "ok"}]}]}
        assert flatten(doc)["text"] == "ok"

    def test_an_atom_occupies_one_position_however_long_it_reads(self):
        # attachmentChip is a BLOCK atom in the app schema -- never inside a
        # paragraph (this test used to put it there, a shape the editor cannot
        # produce) -- so it reads as its own line.
        doc = {"type": "doc", "content": [
            {"type": "paragraph", "content": [{"type": "text", "text": "a"}]},
            {"type": "attachmentChip", "attrs": {"name": "a-very-long-filename.pdf"}},
            {"type": "paragraph", "content": [{"type": "text", "text": "b"}]}]}
        flat = flatten(doc)
        atom = [s for s in flat["spans"] if s["is_atom"]][0]
        assert atom["pm_end"] - atom["pm_start"] == 1
        assert (atom["pm_start"], atom["pm_end"]) == (3, 4)
        assert flat["text"] == "a\n[file: a-very-long-filename.pdf]\nb"


# ── Position-drift guard (the gap in my own "ephemeral ⇒ no drift" reasoning) ──

from api.services.journal_two.note_citation_text import (  # noqa: E402
    DEGRADED,
    PRECISE_STATES,
    RERESOLVED_EXACT,
    VALID_EXACT,
    VALID_NOTE_ONLY,
    fingerprint,
    resolve_note_citation,
    verify,
)

_P = lambda t: {"type": "paragraph", "content": [{"type": "text", "text": t}]}  # noqa: E731
_DOC = lambda *ps: {"type": "doc", "content": list(ps)}  # noqa: E731


class TestFingerprintStrictness:
    """Measured against real prosemirror-model behaviour, not reasoned."""

    def test_a_formatting_only_edit_does_NOT_invalidate_positions(self):
        # Adding a bold mark splits a text node but shifts nothing. Treating
        # this as "changed" would needlessly degrade citations on every
        # formatting tweak.
        plain = _DOC(_P("alpha"), _P("beta"))
        bolded = _DOC(
            {"type": "paragraph", "content": [
                {"type": "text", "text": "al"},
                {"type": "text", "text": "pha", "marks": [{"type": "bold"}]}]},
            _P("beta"))
        assert fingerprint(plain) == fingerprint(bolded)

    def test_a_block_wrap_that_preserves_text_DOES_invalidate_positions(self):
        # The case text-only fingerprinting would miss: identical text,
        # every later position shifted by 2.
        plain = _DOC(_P("alpha"), _P("beta"))
        quoted = _DOC({"type": "blockquote", "content": [_P("alpha")]}, _P("beta"))
        assert flatten(plain)["text"] == flatten(quoted)["text"]
        assert fingerprint(plain) != fingerprint(quoted)

    def test_an_ordinary_text_edit_changes_the_fingerprint(self):
        assert fingerprint(_DOC(_P("alpha"))) != fingerprint(_DOC(_P("alphaX")))


class TestVerifyIsTheRealGuarantee:
    def test_verify_accepts_the_passage_it_cited(self):
        doc = _DOC(_P("Management expects margins to normalize."))
        hit = locate(doc, "margins to normalize")[0]
        assert verify(doc, hit["from"], hit["to"], "margins to normalize")

    def test_verify_rejects_a_range_that_now_holds_different_text(self):
        doc = _DOC(_P("Management expects margins to normalize."))
        hit = locate(doc, "margins to normalize")[0]
        edited = _DOC(_P("XX Management expects margins to normalize."))
        # Same numeric range, still syntactically valid, different text.
        assert not verify(edited, hit["from"], hit["to"], "margins to normalize")

    def test_verify_works_across_a_mark_boundary(self):
        doc = _FIXTURES["markBoundary"]["json"]
        hit = locate(doc, "expects gross margins to")[0]
        assert verify(doc, hit["from"], hit["to"], "expects gross margins to")


class TestResolveNoteCitation:
    def test_unchanged_note_uses_the_original_positions(self):
        doc = _DOC(_P("Management expects margins to normalize."))
        hit = locate(doc, "margins to normalize")[0]
        r = resolve_note_citation(doc, hit["from"], hit["to"],
                                  "margins to normalize", fingerprint(doc))
        assert r["state"] == VALID_EXACT
        assert (r["from"], r["to"]) == (hit["from"], hit["to"])

    def test_an_edited_note_re_resolves_rather_than_using_stale_positions(self):
        before = _DOC(_P("Management expects margins to normalize."))
        hit = locate(before, "margins to normalize")[0]
        fp = fingerprint(before)
        # A paragraph inserted ABOVE shifts every position after it.
        after = _DOC(_P("New opening paragraph."), _P("Management expects margins to normalize."))
        r = resolve_note_citation(after, hit["from"], hit["to"],
                                  "margins to normalize", fp)
        assert r["state"] == RERESOLVED_EXACT
        assert r["from"] != hit["from"], "must not reuse the stale position"
        assert verify(after, r["from"], r["to"], "margins to normalize")

    def test_an_ambiguous_re_resolution_degrades_instead_of_guessing(self):
        before = _DOC(_P("Revenue was strong."))
        fp = fingerprint(before)
        after = _DOC(_P("Revenue was strong."), _P("Revenue was strong."))
        r = resolve_note_citation(after, 1, 8, "Revenue", fp)
        assert r["state"] == VALID_NOTE_ONLY
        assert r["from"] is None, "never pick an occurrence when ambiguous"

    def test_quote_context_rescues_an_otherwise_ambiguous_re_resolution(self):
        before = _DOC(_P("x"))
        after = _DOC(_P("Revenue was strong."), _P("Revenue guidance was raised."))
        r = resolve_note_citation(after, 1, 8, "Revenue", fingerprint(before),
                                  suffix=" guidance")
        assert r["state"] == RERESOLVED_EXACT
        assert verify(after, r["from"], r["to"], "Revenue")

    def test_a_deleted_passage_degrades_honestly(self):
        before = _DOC(_P("Management expects margins to normalize."))
        fp = fingerprint(before)
        after = _DOC(_P("Entirely different content now."))
        r = resolve_note_citation(after, 1, 20, "margins to normalize", fp)
        assert r["state"] == DEGRADED
        assert r["from"] is None

    def test_a_fingerprint_match_with_wrong_text_still_refuses_the_stale_jump(self):
        # The exotic case a fingerprint can be fooled by. verify() catches it,
        # which is why verify and not the fingerprint is the guarantee.
        doc = _DOC(_P("Management expects margins to normalize."))
        r = resolve_note_citation(doc, 1, 10, "not the cited text", fingerprint(doc))
        assert r["state"] not in PRECISE_STATES

    def test_only_the_two_precise_states_may_claim_a_passage_jump(self):
        assert PRECISE_STATES == {VALID_EXACT, RERESOLVED_EXACT}
        for s in (VALID_NOTE_ONLY, DEGRADED):
            assert s not in PRECISE_STATES


# ── Empty textblocks and block atoms (closeout-parity 2026-09-23) ────────────

@pytest.mark.parametrize("case", sorted(_FIXTURES))
def test_python_reproduces_prosemirrors_own_leaf_positions(case):
    """Every leaf that READS AS TEXT (textBetween's leafText argument) sits at
    the position prosemirror-model gives it, slices back to its text, and
    carries the identity the client's citationAtomIdentity gives it (None when
    it has none) -- `_ATOM_IDENTITY` pinned the way `_ATOM_TEXT` is."""
    fx = _FIXTURES[case]
    flat = flatten(fx["json"])
    got = [(s["pm_start"], s["pm_end"], flat["text"][s["flat_start"]:s["flat_end"]], s["atom"])
           for s in flat["spans"] if s["is_atom"]]
    want = [(s["pm_start"], s["pm_end"], s["text"], s["atom"]) for s in fx["leafSpans"]]
    assert got == want, f"{case}: leaf positions/text/identity disagree with the client"


def test_the_fixtures_cover_empty_textblocks_and_block_atoms():
    # Non-vacuity: the two classes below are pinned only if the fixtures
    # actually hold them.
    assert sum(1 for fx in _FIXTURES.values() if fx["leafSpans"]) >= 8
    for name in ("consecutiveEmpty", "emptyTableCells", "chipMiddle", "realisticMixed"):
        assert name in _FIXTURES


class TestEmptyTextblocks:
    """textBetween emits a separator for EVERY textblock but the first, an
    empty one included. Collapsing runs of them made every flat offset after
    an empty paragraph disagree with the client's own text."""

    def test_each_empty_paragraph_is_its_own_separator(self):
        assert flatten(_FIXTURES["consecutiveEmpty"]["json"])["text"] == "First.\n\n\n\nSecond."

    def test_a_leading_empty_paragraph_consumes_the_first_slot(self):
        assert flatten(_FIXTURES["emptyParaStart"]["json"])["text"] == "\nFirst.\nSecond."

    def test_a_trailing_empty_paragraph_still_emits_its_separator(self):
        assert flatten(_FIXTURES["emptyParaEnd"]["json"])["text"] == "First.\nSecond.\n"

    def test_empty_table_cells_each_count(self):
        assert flatten(_FIXTURES["emptyTableCells"]["json"])["text"] == "A1\n\n\nB2"

    def test_separators_move_offsets_never_positions(self):
        # Positions come from node sizes; separators only shift FLAT offsets.
        # This is why the fix cannot invalidate an issued {from, to}.
        for case in ("emptyParaStart", "consecutiveEmpty", "emptyTableCells", "realisticMixed"):
            fx = _FIXTURES[case]
            flat = flatten(fx["json"])
            assert flat["content_size"] == fx["contentSize"]
            assert [(s["pm_start"], s["pm_end"]) for s in flat["spans"] if not s["is_atom"]] == \
                   [(s["pm_start"], s["pm_end"]) for s in fx["textSpans"]]


class TestBlockAtomsAreTheirOwnLine:
    """A block atom's placeholder is its own line. Before, the NEXT block's
    text was glued onto it ("[file: q3.pdf]After.", "NVDA daily chartAfter."),
    so the member's own paragraph after any chip, excerpt or chart could never
    be verified by the client and read garbled to the model."""

    def test_the_paragraph_after_a_chip_is_not_glued(self):
        assert flatten(_FIXTURES["chipMiddle"]["json"])["text"] == "Before.\n[file: q3-filing.pdf]\nAfter."

    def test_two_atoms_in_a_row_are_two_lines(self):
        text = flatten(_FIXTURES["twoAtomsInARow"]["json"])["text"]
        assert text == "Before.\n[file: a.pdf]\nNVDA daily chart\nAfter."

    def test_ask_current_note_blocks_split_at_the_atom(self):
        # The consumer that turns this text into citable passages: each block
        # is its own passage with its own verifiable range.
        from api.services.journal_two import ask_retrieval as ar
        blocks = ar._note_blocks(_FIXTURES["chipMiddle"]["json"], "")
        assert [(b["text"], b["location"]["from"], b["location"]["to"]) for b in blocks] == [
            ("Before.", 1, 8), ("[file: q3-filing.pdf]", 9, 10), ("After.", 11, 17)]
        # This chip has no href, so no identity: its block is still listed,
        # but never labelled a passage the client would refuse to open.
        assert [b["precise"] for b in blocks] == [True, False, True]
        assert all("atom" not in b["location"] for b in blocks)


# ── Positions count UTF-16 units (fix round 1, M3) ──────────────────────────

_PASSAGES = [(case, p) for case in sorted(_FIXTURES) for p in _FIXTURES[case]["passages"]]


def test_the_fixtures_hold_astral_characters_and_cited_passages():
    # Non-vacuity: without an astral character in the ground truth, code
    # points and UTF-16 units agree and every rail below passes vacuously.
    astral = [c for c, fx in _FIXTURES.items() if any(ord(ch) > 0xFFFF for ch in fx["text"])]
    assert len(astral) >= 5, astral
    assert len(_PASSAGES) >= 15


@pytest.mark.parametrize("case", sorted(_FIXTURES))
def test_python_reproduces_prosemirrors_content_size(case):
    # The fingerprint's size component. An emoji is two positions.
    assert flatten(_FIXTURES[case]["json"])["content_size"] == _FIXTURES[case]["contentSize"]


@pytest.mark.parametrize("case,passage", _PASSAGES,
                         ids=[f"{c}:{ascii(p['text'])}" for c, p in _PASSAGES])
def test_a_passage_near_an_astral_character_maps_to_prosemirrors_range(case, passage):
    """Before, inside, across a mark and after an emoji: the range the server
    issues is the one textBetween gives the passage, and the server's own
    verify reads the passage back from it."""
    doc = _FIXTURES[case]["json"]
    want = (passage["pm_from"], passage["pm_to"])
    assert [(h["from"], h["to"]) for h in locate(doc, passage["text"])] == [want]
    got = resolve_note_citation(doc, *want, passage["text"], fingerprint(doc))
    leaves = {(s["pm_start"], s["pm_end"]): s for s in _FIXTURES[case]["leafSpans"]}
    if want in leaves:
        # An atom passage: its placeholder text proves nothing about WHICH
        # atom (review-parity N1), so text alone never opens it...
        assert got["state"] == VALID_NOTE_ONLY
        # ...and its identity, when it has one, opens it in place.
        if leaves[want]["atom"]:
            by_id = resolve_note_citation(doc, *want, passage["text"], fingerprint(doc),
                                          atom=leaves[want]["atom"])
            assert (by_id["state"], by_id["from"], by_id["to"]) == (VALID_EXACT, *want)
    else:
        assert got["state"] in PRECISE_STATES and (got["from"], got["to"]) == want
        assert verify(doc, *want, passage["text"])
        assert got["state"] == VALID_EXACT


def test_verify_refuses_a_position_between_the_halves_of_an_emoji():
    # "🔥 Margins..." -- position 2 is INSIDE the emoji's surrogate pair. No
    # code-point offset names it, so it can never verify.
    doc = _FIXTURES["astralBefore"]["json"]
    assert not verify(doc, 2, 4, " ")
    assert verify(doc, 1, 3, "\U0001F525")


def test_ask_consumers_issue_utf16_ranges():
    from api.services.journal_two import ask_retrieval as ar
    # Ask Current Note: one block per line, each at ProseMirror's range.
    blocks = ar._note_blocks(_FIXTURES["astralThenChip"]["json"], "")
    assert [(b["location"]["from"], b["location"]["to"]) for b in blocks] == [(1, 7), (8, 9), (10, 19)]
    # Ask My Notebook's passage picker, a word after the emoji.
    doc = _FIXTURES["astralBefore"]["json"]
    _snippet, loc, _validity = ar._best_note_passage(doc, '"margins"')
    assert (loc["from"], loc["to"]) == (4, 11)
    assert verify(doc, loc["from"], loc["to"], "Margins")


# ── A KNOWN type answers by type (fix round 1, M1) ──────────────────────────

class TestTextblockInference:
    """`isTextblock` is a property of the node TYPE in ProseMirror. Loadable
    but malformed JSON -- a container holding text directly -- must not grow a
    separator textBetween never emits."""

    def test_a_known_container_holding_text_directly_gets_no_separator(self):
        doc = {"type": "doc", "content": [
            {"type": "paragraph", "content": [{"type": "text", "text": "A"}]},
            {"type": "blockquote", "content": [{"type": "text", "text": "B"}]}]}
        assert flatten(doc)["text"] == "AB"

    def test_an_unknown_type_holding_inline_content_is_still_inferred(self):
        doc = {"type": "doc", "content": [
            {"type": "paragraph", "content": [{"type": "text", "text": "A"}]},
            {"type": "futureTextblock", "content": [{"type": "text", "text": "B"}]}]}
        assert flatten(doc)["text"] == "A\nB"


# ── An atom resolves by IDENTITY, never by its placeholder (fix round 2) ─────

_EX = lambda i: {"type": "documentExcerpt", "attrs": {"excerptId": i}}  # noqa: E731
_WIDGET = lambda at: {"type": "widgetEmbed",  # noqa: E731
                      "attrs": {"widgetId": "chart", "capturedAt": at}}  # reads "[widget]"


def _atom_citation(doc, atom_id):
    """The location the SERVER issues for the atom with this id -- the real
    issuer (`_note_blocks`), so these rails cover issuance and resolution."""
    from api.services.journal_two import ask_retrieval as ar
    locs = [b["location"] for b in ar._note_blocks(doc, "")
            if (b["location"].get("atom") or {}).get("id") == atom_id]
    assert len(locs) == 1, f"the server issued no single citation for {atom_id!r}"
    return locs[0]


def _resolve(doc, loc, snippet, **kw):
    return resolve_note_citation(doc, loc["from"], loc["to"], snippet, loc["fingerprint"], **kw)


class TestAtomsResolveByIdentity:
    """Review-parity N1: every excerpt reads "[excerpt]", so after ONE delete a
    text match lands on the look-alike -- in place when they were adjacent,
    by re-resolution when text sat between them. N2: a unique atom whose
    placeholder ALSO appears as ordinary text was refused as ambiguous."""

    def test_the_server_issues_every_identity_kind_it_can_name(self):
        from api.services.journal_two import ask_retrieval as ar
        fx = _FIXTURES["identityAtoms"]
        issued = [b["location"].get("atom") for b in ar._note_blocks(fx["json"], "")]
        # Text blocks carry none; each atom carries exactly the fixture's.
        assert issued == [None, *[s["atom"] for s in fx["leafSpans"]], None]
        assert {a["type"] for a in issued if a} == {"attachmentChip", "documentExcerpt", "widgetEmbed"}

    def test_an_empty_identity_attr_is_no_identity(self):
        from api.services.journal_two import ask_retrieval as ar
        blocks = ar._note_blocks(_FIXTURES["identityAttrsEmpty"]["json"], "")
        assert all("atom" not in b["location"] for b in blocks)
        assert [b["precise"] for b in blocks] == [True, False, False, False, True]

    def test_adjacent_twin_deleted_never_lands_on_the_survivor(self):
        # Reviewer case 7: [Thesis, ex1, ex2, After.]; ex1 cited, then deleted,
        # so ex2 slides into ex1's exact position and reads the same.
        before = _DOC(_P("Thesis."), _EX("ex1"), _EX("ex2"), _P("After."))
        loc = _atom_citation(before, "ex1")
        after = _DOC(_P("Thesis."), _EX("ex2"), _P("After."))
        r = _resolve(after, loc, "[excerpt]", atom=loc["atom"])
        assert r["state"] == VALID_NOTE_ONLY and r["from"] is None

    def test_twin_across_a_paragraph_is_never_re_resolved_onto(self):
        # Reviewer case 8: a paragraph between them made the survivor a UNIQUE
        # text hit, so the text path re-resolved onto it.
        before = _DOC(_P("Thesis."), _EX("ex1"), _P("Between."), _EX("ex2"), _P("After."))
        loc = _atom_citation(before, "ex1")
        after = _DOC(_P("Thesis."), _P("Between."), _EX("ex2"), _P("After."))
        assert _resolve(after, loc, "[excerpt]", atom=loc["atom"])["state"] == VALID_NOTE_ONLY
        # And the text path, handed no identity, refuses the unique atom hit too.
        assert _resolve(after, loc, "[excerpt]")["state"] == VALID_NOTE_ONLY

    def test_a_widget_twin_is_never_selected(self):
        # Reviewer case 9: the same shape for "[widget]".
        before = _DOC(_P("Thesis."), _WIDGET("2026-09-01T14:00:00.000Z"), _P("Between."),
                      _WIDGET("2026-09-02T14:00:00.000Z"), _P("After."))
        loc = _atom_citation(before, "chart|2026-09-01T14:00:00.000Z")
        after = _DOC(_P("Thesis."), _P("Between."), _WIDGET("2026-09-02T14:00:00.000Z"), _P("After."))
        assert _resolve(after, loc, "[widget]", atom=loc["atom"])["state"] == VALID_NOTE_ONLY

    def test_an_atom_in_place_opens_exactly(self):
        doc = _DOC(_P("Thesis."), _EX("ex1"), _EX("ex2"), _P("After."))
        loc = _atom_citation(doc, "ex2")
        r = _resolve(doc, loc, "[excerpt]", atom=loc["atom"])
        assert (r["state"], r["from"], r["to"]) == (VALID_EXACT, loc["from"], loc["to"])

    def test_a_moved_atom_re_resolves_by_identity(self):
        before = _DOC(_P("Thesis."), _EX("ex1"), _EX("ex2"), _P("After."))
        loc = _atom_citation(before, "ex2")
        after = _DOC(_P("A new opening."), _P("Thesis."), _EX("ex1"), _EX("ex2"), _P("After."))
        r = _resolve(after, loc, "[excerpt]", atom=loc["atom"])
        assert r["state"] == RERESOLVED_EXACT
        assert (r["from"], r["to"]) == (loc["from"] + 16, loc["to"] + 16)  # "A new opening." + 2

    def test_a_unique_atom_whose_placeholder_is_also_typed_text_opens(self):
        # N2: "[excerpt]" typed in a paragraph made the round-1 text count 2.
        doc = _DOC(_P("I typed [excerpt] here."), _EX("ex1"))
        loc = _atom_citation(doc, "ex1")
        assert _resolve(doc, loc, "[excerpt]", atom=loc["atom"])["state"] == VALID_EXACT
        moved = _DOC(_P("Above."), _P("I typed [excerpt] here."), _EX("ex1"))
        r = _resolve(moved, loc, "[excerpt]", atom=loc["atom"])
        assert r["state"] == RERESOLVED_EXACT and (r["from"], r["to"]) == (loc["from"] + 8, loc["to"] + 8)

    def test_two_atoms_with_one_identity_off_position_open_the_note_only(self):
        # A pasted copy duplicates the attrs; neither copy can be preferred.
        before = _DOC(_P("Thesis."), _EX("ex1"))
        loc = _atom_citation(before, "ex1")
        after = _DOC(_P("Thesis, rewritten."), _EX("ex1"), _EX("ex1"))
        assert _resolve(after, loc, "[excerpt]", atom=loc["atom"])["state"] == VALID_NOTE_ONLY

    def test_a_citation_without_identity_never_opens_an_atom(self):
        # Issued before identities existed, or to an atom with none: even on an
        # UNCHANGED note with a unique placeholder, the text proves nothing.
        doc = _FIXTURES["excerptMiddle"]["json"]
        leaf = _FIXTURES["excerptMiddle"]["leafSpans"][0]
        r = resolve_note_citation(doc, leaf["pm_start"], leaf["pm_end"], "[excerpt]", fingerprint(doc))
        assert r["state"] == VALID_NOTE_ONLY and r["from"] is None

    def test_a_text_citation_whose_only_remaining_hit_is_an_atom_is_refused(self):
        before = _DOC(_P("Thesis."), _P("[excerpt]"), _EX("ex1"))
        hit = locate(before, "[excerpt]")[0]  # the typed paragraph, not the atom
        after = _DOC(_P("Thesis."), _EX("ex1"))
        r = resolve_note_citation(after, hit["from"], hit["to"], "[excerpt]", fingerprint(before))
        assert r["state"] == VALID_NOTE_ONLY and r["from"] is None

    def test_quote_context_never_rescues_a_text_citation_onto_an_atom(self):
        # Two "[excerpt]" hits (typed text + the atom); the suffix picks the
        # atom's. Context proves which TEXT, never which atom -- refused too.
        doc = _DOC(_P("Typed [excerpt] here."), _EX("ex1"), _P("After."))
        r = resolve_note_citation(doc, 999, 1000, "[excerpt]", "stale", suffix="\nAfter.")
        assert r["state"] == VALID_NOTE_ONLY and r["from"] is None
        # Control: the same context on typed text still rescues it.
        typed = _DOC(_P("[excerpt] one."), _P("[excerpt] two."))
        r = resolve_note_citation(typed, 999, 1000, "[excerpt]", "stale", suffix=" two.")
        assert r["state"] == RERESOLVED_EXACT and verify(typed, r["from"], r["to"], "[excerpt]")

    def test_the_passage_picker_cites_an_atom_by_identity(self):
        from api.services.journal_two import ask_evidence as ev
        from api.services.journal_two import ask_retrieval as ar
        _snippet, loc, validity = ar._best_note_passage(_DOC(_P("Thesis."), _EX("ex1")), '"excerpt"')
        assert loc["atom"] == {"type": "documentExcerpt", "id": "ex1"} and validity == ev.CITE_EXACT
        # No identity (a chip with no href): no atom, and never labelled exact.
        _snippet, loc, validity = ar._best_note_passage(_FIXTURES["chipMiddle"]["json"], '"filing"')
        assert "atom" not in loc and validity == ev.CITE_NOTE_ONLY


# ── An identity is ISSUED only when it names one atom (fix round 3) ──────────

from api.services.journal_two.note_citation_text import atom_at  # noqa: E402

_MTF = "chartsMtfThenSingle"
_MTF_SHARED = {"type": "widgetEmbed", "id": "chart|2026-09-01T14:00:00.000Z"}


def _chart_blocks(case):
    from api.services.journal_two import ask_retrieval as ar
    return [b for b in ar._note_blocks(_FIXTURES[case]["json"], "") if b["text"].startswith("[chart:")]


def _without(case, index):
    """The fixture doc with its top-level node `index` deleted."""
    content = list(_FIXTURES[case]["json"]["content"])
    del content[index]
    return {"type": "doc", "content": content}


class TestAnIdentityIsIssuedOnlyWhenUnique:
    """rereview2 R2-1: every chart of one /mtf or /compare insert shares
    widgetId|capturedAt -- measured 500/500 on the real chartInsertNodes, and
    these fixtures are pinned to that builder by askCitation.parity.test.js.
    An identity that names several atoms let the client select a sibling
    after one delete, so it is never issued."""

    def test_the_fixture_really_holds_a_shared_identity(self):
        # Non-vacuity: the rule below is only visible on atoms that share one.
        ids = [s["atom"]["id"] for s in _FIXTURES[_MTF]["leafSpans"]]
        assert len(ids) == 4 and len(set(ids[:3])) == 1 and ids[3] != ids[0]

    def test_an_mtf_stack_issues_no_identity_and_is_labelled_note_only(self):
        charts = _chart_blocks(_MTF)
        assert [b["text"] for b in charts] == [
            "[chart: NVDA D]", "[chart: NVDA 1h]", "[chart: NVDA 15m]", "[chart: AMD D]"]
        for b in charts[:3]:
            assert "atom" not in b["location"] and b["precise"] is False, b["text"]
        # A later, separately inserted chart is unique and still gets its own.
        assert charts[3]["location"]["atom"] == {
            "type": "widgetEmbed", "id": "chart|2026-09-01T14:05:00.000Z"}
        assert charts[3]["precise"] is True

    def test_a_compare_pair_issues_no_identity(self):
        charts = _chart_blocks("chartsCompare")
        assert len(charts) == 2
        assert all("atom" not in b["location"] and b["precise"] is False for b in charts)

    @pytest.mark.parametrize("case,cited,deleted", [
        (_MTF, 1, 1),            # reviewer case 14: the D chart ABOVE the cited 1h deleted
        (_MTF, 1, 2),            # case 15: the cited 1h deleted
        (_MTF, 0, 1),            # case 16: the cited D deleted
        ("chartsCompare", 0, 1),  # case 19: the cited "before" chart deleted
    ], ids=["case14", "case15", "case16", "case19"])
    def test_deleting_one_chart_never_opens_a_sibling(self, case, cited, deleted):
        b = _chart_blocks(case)[cited]
        loc = b["location"]
        r = resolve_note_citation(_without(case, deleted), loc["from"], loc["to"], b["text"],
                                  loc["fingerprint"], atom=loc.get("atom"))
        assert r["state"] not in PRECISE_STATES and r["from"] is None

    def test_control_the_shared_identity_WOULD_open_a_sibling(self):
        # Why it is never issued: handed it anyway, case 15 opens the 15m
        # chart that slid into the deleted 1h's position.
        after = _without(_MTF, 2)
        r = resolve_note_citation(after, 15, 16, "[chart: NVDA 1h]", "stale", atom=_MTF_SHARED)
        assert r["state"] == VALID_EXACT
        lands = [s for s in flatten(after)["spans"] if s["is_atom"] and s["pm_start"] == r["from"]]
        assert lands[0]["text"] == "[chart: NVDA 15m]"

    def test_a_copy_inside_an_inserted_answer_still_counts(self):
        # The client's lookup walks the whole doc, so the count does too.
        alone = _DOC(_P("Thesis."), _EX("ex1"))
        copied = _DOC(_P("Thesis."), _EX("ex1"), {"type": "askInsert", "content": [_EX("ex1")]})
        rng = {"from": 9, "to": 10}
        assert atom_at(flatten(alone), rng) == {"type": "documentExcerpt", "id": "ex1"}
        assert atom_at(flatten(copied), rng) is None


class TestTheMirrorTakesTheClientsAtomShape:
    """Review M1: the client takes an identity only with a string `type` and a
    non-empty string `id`; the mirror took any truthy value."""

    @pytest.mark.parametrize("bad", [
        {"type": "documentExcerpt", "id": ""}, {"type": 7, "id": "ex1"}, {"id": "ex1"}, "ex1", ["ex1"],
    ], ids=["empty-id", "non-string-type", "no-type", "a-string", "a-list"])
    def test_a_malformed_atom_is_no_identity_and_the_text_decides(self, bad):
        doc = _DOC(_P("Management expects margins to normalize."))
        hit = locate(doc, "margins")[0]
        r = resolve_note_citation(doc, hit["from"], hit["to"], "margins", fingerprint(doc), atom=bad)
        assert r["state"] == VALID_EXACT

    def test_extra_keys_do_not_hide_a_well_formed_identity(self):
        doc = _DOC(_P("Thesis."), _EX("ex1"))
        r = resolve_note_citation(doc, 9, 10, "[excerpt]", fingerprint(doc),
                                  atom={"type": "documentExcerpt", "id": "ex1", "label": "Q3"})
        assert (r["state"], r["from"], r["to"]) == (VALID_EXACT, 9, 10)


class TestThePassagePickerPrefersAnExactOccurrence:
    """Review M2: the first occurrence of a term inside an atom with no
    identity labelled the note note_only although a later plain-text
    occurrence cites exactly."""

    _CHIP = {"type": "attachmentChip", "attrs": {"name": "margins.pdf"}}  # no href

    def test_a_later_text_occurrence_beats_an_idless_atom(self):
        from api.services.journal_two import ask_evidence as ev
        from api.services.journal_two import ask_retrieval as ar
        doc = _DOC(self._CHIP, _P("Gross margins fell."))
        _snippet, loc, validity = ar._best_note_passage(doc, '"margins"')
        assert validity == ev.CITE_EXACT and "atom" not in loc
        assert verify(doc, loc["from"], loc["to"], "margins")

    def test_with_no_text_occurrence_the_atom_still_opens_the_note(self):
        from api.services.journal_two import ask_evidence as ev
        from api.services.journal_two import ask_retrieval as ar
        doc = _DOC(self._CHIP, _P("Nothing else."))
        _snippet, loc, validity = ar._best_note_passage(doc, '"margins"')
        assert validity == ev.CITE_NOTE_ONLY and (loc["from"], loc["to"]) == (0, 1)
