"""`docs/account-deletion-manifest.md` names EXACTLY the tables the account purge deletes.

Wave 7, lane J, item J4. The manifest was hand-typed beside the code it describes and, at
the wave-6 close, was 16 tables short of what `account_purge.purge_user_data` deletes -- 20
by wave 7, once lane G's email-in tables (`j2_inbound_addresses`, `j2_inbound_usage`,
`j2_inbound_drops`) and lane H's `j2_note_embeddings` landed. Its table is now GENERATED by
`tools/account_deletion_manifest.py` and never typed.

Three independent readings of "what the purge deletes", and they must agree:

* the DOC -- parsed here from its own markdown table rows;
* the RUNTIME -- `purge_user_data` run against an empty in-memory database reports, in
  `rows_deleted`, every table it issued a DELETE against (a missing table is a counted no-op);
* the DERIVATION -- the generator's AST read of `account_purge.py`.

A difference fails BY NAME, in either direction. Non-vacuity controls name `j2_notes` and the
indirect `j2_option_legs`, so an empty parse on either side cannot pass.
"""
from __future__ import annotations

import re
import sqlite3
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "tools"))

import account_deletion_manifest as gen  # noqa: E402

DOC = REPO / "docs" / "account-deletion-manifest.md"
_ROW = re.compile(r"^\|\s*`(j2_[a-z0-9_]+)`\s*\|")


def _doc_text() -> str:
    return DOC.read_text(encoding="utf-8").replace("\r\n", "\n")


def _doc_purged() -> set[str]:
    """The table names in the doc's manifest table (the generated block), read as markdown."""
    names = set()
    for line in gen.doc_block(_doc_text()).splitlines():
        m = _ROW.match(line)
        if m:
            names.add(m.group(1))
    return names


def _doc_not_purged() -> set[str]:
    """The names the doc's hand-written 'correctly NOT purged' section lists."""
    text = _doc_text()
    start = text.index("### Correctly NOT purged")
    nxt = text.find("\n## ", start)
    section = text[start: nxt if nxt != -1 else len(text)]
    return {m.group(1) for line in section.splitlines() if (m := _ROW.match(line))}


def _runtime_purged() -> set[str]:
    """Every table `purge_user_data` issues a DELETE against, read off its own report.

    An in-memory database has none of the tables, so every DELETE is a "no such table"
    no-op -- which the purge still records by name. The attachment half resolves under the
    repo-root conftest's sandbox pins and finds no directory for this id."""
    from api.services.journal_two import account_purge

    conn = sqlite3.connect(":memory:")
    try:
        report = account_purge.purge_user_data("j4-manifest-probe-no-such-user", conn)
    finally:
        conn.close()
    assert report["errors"] == [], report["errors"]
    return set(report["rows_deleted"])


def _diff(label_a: str, a: set[str], label_b: str, b: set[str]) -> str:
    lines = []
    for name in sorted(a - b):
        lines.append(f"  {name}: in {label_a}, NOT in {label_b}")
    for name in sorted(b - a):
        lines.append(f"  {name}: in {label_b}, NOT in {label_a}")
    return "\n".join(lines)


def test_the_manifest_names_exactly_the_tables_the_purge_deletes():
    doc, runtime = _doc_purged(), _runtime_purged()
    # Non-vacuity, by name, on BOTH sides.
    for name in ("j2_notes", "j2_option_legs"):
        assert name in runtime, f"the purge's own report does not name {name}: {sorted(runtime)}"
        assert name in doc, f"the doc's table does not name {name}"
    problem = _diff("the purge (runtime)", runtime, "docs/account-deletion-manifest.md", doc)
    assert not problem, ("the manifest and the purge disagree -- regenerate with "
                         "`python tools/account_deletion_manifest.py --write`:\n" + problem)


def test_the_derivation_reads_what_the_purge_runs():
    derived, runtime = gen.purged_tables(), _runtime_purged()
    problem = _diff("the purge (runtime)", runtime, "the generator's AST derivation", derived)
    assert not problem, problem
    indirect = {t: (fk, parent) for t, fk, parent in gen.derive()["indirect"]}
    assert indirect.get("j2_option_legs") == ("strategy_id", "j2_option_strategies")
    assert indirect.get("j2_broker_member_stale_notify") == ("broker_account_id", "j2_broker_accounts")


def test_the_generated_block_in_the_doc_is_current():
    """Owner keys and ownership are derived too -- not only the names."""
    assert gen.doc_block(_doc_text()) == gen.render(), (
        "docs/account-deletion-manifest.md is stale -- run "
        "`python tools/account_deletion_manifest.py --write`")


def test_what_the_doc_says_is_NOT_purged_really_is_not_and_the_code_says_why():
    not_purged, runtime = _doc_not_purged(), _runtime_purged()
    assert "j2_broker_digest_dedup" in not_purged, "non-vacuity: the not-purged section was not read"
    both = sorted(not_purged & runtime)
    assert not both, f"listed as NOT purged but the purge deletes them: {both}"
    src = gen.PURGE.read_text(encoding="utf-8")
    silent = sorted(n for n in not_purged if n not in src)
    assert not silent, f"excluded in the doc but account_purge.py does not say why: {silent}"


def test_every_member_table_the_schema_creates_is_purged_or_emptied_by_a_trigger():
    """Doc == code is not enough on its own: the CODE can be short of the SCHEMA. Every
    `j2_*` table `journal_two.db.ensure_schema` creates with a `user_id` column is either
    deleted by the purge, or emptied by an `AFTER DELETE` trigger on a table the purge
    deletes (the FTS mirrors) -- read from the schema's own trigger SQL, never listed here.
    Self-ensured tables (email-in, embeddings, reminders, weekly digest) are not created by
    `ensure_schema`; the doc-vs-purge rail above is what covers them."""
    from api.services.journal_two.db import ensure_schema

    conn = sqlite3.connect(":memory:")
    try:
        ensure_schema(conn)
        tables = [r[0] for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type = 'table' AND name LIKE 'j2\\_%' ESCAPE '\\'")]
        member = sorted(t for t in tables
                        if any(c[1] == "user_id" for c in conn.execute(f'PRAGMA table_info("{t}")')))
        triggers = conn.execute(
            "SELECT tbl_name, sql FROM sqlite_master WHERE type = 'trigger'").fetchall()
    finally:
        conn.close()
    purged = _runtime_purged()
    emptied_by = {}
    for base, sql in triggers:
        if base in purged and re.search(r"\bAFTER\s+DELETE\b", sql or "", re.IGNORECASE):
            for target in re.findall(r"DELETE\s+FROM\s+(\w+)", sql, re.IGNORECASE):
                emptied_by.setdefault(target, base)
    # Non-vacuity, by name: the schema was read, and the notes FTS mirror is seen as trigger-emptied.
    assert "j2_notes" in member, f"the schema read saw no j2_notes: {member[:5]}"
    assert emptied_by.get("j2_notes_fts") == "j2_notes", sorted(emptied_by)
    left = [t for t in member if t not in purged and t not in emptied_by]
    assert not left, ("tables holding a member's user_id that an account deletion leaves "
                      f"behind: {left} -- add them to account_purge._DIRECT_USER_TABLES")


def _seed_member(conn, uid: str) -> None:
    """One note, one document with one page, and one excerpt for `uid` -- through the base
    tables, so the schema's own AFTER INSERT triggers fill every full-text mirror."""
    ts = "2026-09-25T00:00:00+00:00"
    conn.execute("INSERT INTO j2_notes (id, user_id, title, body_json, body_plain, tags, created_at, updated_at)"
                 " VALUES (?,?,?,?,?,?,?,?)", (f"note-{uid}", uid, f"title {uid}", '{"type":"doc"}',
                                                f"body {uid}", "[]", ts, ts))
    conn.execute("INSERT INTO j2_note_documents (id, user_id, note_id, attachment_url, status, created_at)"
                 " VALUES (?,?,?,?,'ready',?)", (f"doc-{uid}", uid, f"note-{uid}", f"/att/{uid}.pdf", ts))
    conn.execute("INSERT INTO j2_note_document_pages (document_id, user_id, page_number, text)"
                 " VALUES (?,?,1,?)", (f"doc-{uid}", uid, f"page words {uid}"))
    conn.execute("INSERT INTO j2_note_excerpts (id, user_id, note_id, document_id, page_number, captured_text,"
                 " created_at) VALUES (?,?,?,?,1,?,?)", (f"exc-{uid}", uid, f"note-{uid}", f"doc-{uid}",
                                                         f"saved passage {uid}", ts))
    conn.commit()


def test_the_tables_only_a_trigger_empties_really_lose_the_deleted_members_rows():
    """Fix round 1, review I-2. The schema rail above accepts a table as covered when an
    AFTER DELETE trigger's SQL TEXT names it -- a reading. The full-text triggers key on a
    `_fts_map` row, and a wrong or missing map entry deletes nothing while that text still
    reads fine. So FIRE them: seed two members, purge one through the real
    `purge_user_data`, and every `user_id` table the purge does not delete itself must go
    from one row to none for the deleted member and stay at one for the other -- by name.
    The set is derived (member tables minus what the purge deletes), never typed."""
    from api.services.journal_two import account_purge
    from api.services.journal_two import notes as notes_svc
    from api.services.journal_two.db import ensure_schema

    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    try:
        ensure_schema(conn)
        notes_svc.register_note_sql_functions(conn)
        tables = [r[0] for r in conn.execute(
            r"SELECT name FROM sqlite_master WHERE type = 'table' AND name LIKE 'j2\_%' ESCAPE '\'")]
        member = {t for t in tables if any(c[1] == "user_id" for c in conn.execute(f'PRAGMA table_info("{t}")'))}
        only_by_trigger = sorted(member - _runtime_purged())
        # Non-vacuity, by name: the three full-text mirrors are what this is about.
        fts = {"j2_notes_fts", "j2_note_document_pages_fts", "j2_note_excerpts_fts"}
        assert fts <= set(only_by_trigger), only_by_trigger
        for uid in ("gone", "stays"):
            _seed_member(conn, uid)

        def count(t, uid):
            return conn.execute(f'SELECT COUNT(*) FROM "{t}" WHERE user_id = ?', (uid,)).fetchone()[0]

        before = {t: (count(t, "gone"), count(t, "stays")) for t in only_by_trigger}
        unseeded = sorted(t for t, (g, s_) in before.items() if (g, s_) != (1, 1))
        assert not unseeded, f"the seed did not reach these (extend _seed_member): {unseeded} {before}"
        report = account_purge.purge_user_data("gone", conn)
        assert report["errors"] == [], report["errors"]
        after = {t: (count(t, "gone"), count(t, "stays")) for t in only_by_trigger}
    finally:
        conn.close()
    wrong = {t: v for t, v in after.items() if v != (0, 1)}
    assert not wrong, f"(deleted member, other member) rows left after the purge, want (0, 1): {wrong}"


@pytest.mark.parametrize("source", [
    "X = 1\n",                                              # no tuple at all
    "_DIRECT_USER_TABLES = ()\n",                            # an empty tuple
    "_DIRECT_USER_TABLES = (name,)\n",                       # a non-literal entry
    "_DIRECT_USER_TABLES = ('a',)\n_run('b', 'DELETE FROM b WHERE user_id = ?', ())\n",
])
def test_a_derivation_that_cannot_read_the_purge_RAISES_rather_than_returning_empty(source):
    with pytest.raises(gen.DerivationError):
        gen.derive(source)
