"""``self[n]`` in the Python lane, held to the JS lane's own output.

⭐⭐ THE KEYSTONE OF MEMBER-AUTHORED INDICATORS. A 2-pole filter is
``c1*input + c2*prev + c3*prev_prev`` by definition -- Butterworth, SuperSmoother,
every Ehlers design -- so a recurrence that could read exactly one bar of its own
past could not express the DSP family at all.

⛔ THE FIXTURE IS THE ONE AUTHORITY. ``app/.../selfLag.test.js`` reads this same
file, so a lane that drifts fails against the OTHER LANE'S OWN OUTPUT rather than
against a number somebody retyped in a docstring. Retyping the expected series
here is exactly the second-authority defect this repo keeps paying for.
"""
from __future__ import annotations

import io
import json
import math
import pathlib

import pytest

from api.services import ast_interpret as ai

FIXTURE = pathlib.Path(__file__).parent / "fixtures" / "ast" / "self_lag_parity.json"


def _doc() -> dict:
    return json.load(io.open(FIXTURE, encoding="utf-8"))


def _bars() -> list:
    out = []
    for i in range(300):
        c = 100 + math.sin(i / 9) * 8 + i * 0.06
        out.append({"o": c - 0.3, "h": c + 0.8, "l": c - 0.8, "c": c, "v": 100000})
    return out


def test_the_butterworth_matches_the_other_lane_bar_for_bar():
    doc = _doc()
    got = ai.interpret(doc["ast"], _bars(), {})
    expected = doc["expected"]
    assert len(got) == len(expected)
    for i, (a, b) in enumerate(zip(got, expected)):
        if b is None:
            assert a is None, f"bar {i}: this lane produced {a} where the other produced nothing"
            continue
        assert a is not None, f"bar {i}: this lane produced nothing where the other produced {b}"
        assert abs(a - b) < 1e-9, f"bar {i}: {a} vs {b}"


def test_the_fixture_is_not_mostly_holes():
    # ⛔ NON-VACUITY. The comparison above passes on an all-null column.
    assert sum(1 for v in _doc()["expected"] if v is not None) > 200


def test_a_second_lag_actually_changes_the_answer():
    """⛔ Without this, a lane that silently DROPPED ``self[1]`` would pass the
    parity test by computing a plain one-lag filter -- as long as the fixture had
    been generated by the same broken code. This compares two formulas within
    THIS lane, so it cannot be satisfied that way."""
    doc = _doc()
    two_pole = ai.interpret(doc["ast"], _bars(), {})

    def strip_second_lag(node):
        """The tree minus its `- 0.64125 * self[1]` term, found structurally."""
        if not isinstance(node, dict):
            return node
        if node.get("type") == "op" and node.get("name") == "-":
            right = node["args"][1]
            if _mentions_self_offset(right):
                return strip_second_lag(node["args"][0])
        clone = dict(node)
        if isinstance(clone.get("args"), list):
            clone["args"] = [strip_second_lag(a) for a in clone["args"]]
        return clone

    dropped = ai.interpret(strip_second_lag(doc["ast"]), _bars(), {})
    assert abs(two_pole[-1] - dropped[-1]) > 0.01


def _mentions_self_offset(node) -> bool:
    if not isinstance(node, dict):
        return False
    if node.get("type") == "offset":
        child = (node.get("args") or [None])[0]
        if isinstance(child, dict) and child.get("type") == "series" and child.get("name") == "self":
            return True
    return any(_mentions_self_offset(a) for a in (node.get("args") or []))


def _accum(update: dict, warmup: int = 250) -> dict:
    return {
        "type": "call", "name": "accum",
        "args": [{"type": "series", "name": "close"}, update, {"type": "num", "value": warmup}],
    }


def _self_at(k: int) -> dict:
    return {"type": "offset", "value": k, "args": [{"type": "series", "name": "self"}]}


def test_a_lag_past_the_ceiling_refuses_by_name():
    tree = _accum({"type": "op", "name": "+",
                   "args": [_self_at(ai.MAX_SELF_LAG + 1), {"type": "num", "value": 0}]})
    with pytest.raises(Exception) as err:
        ai.interpret(tree, _bars(), {})
    assert str(ai.MAX_SELF_LAG) in str(err.value)


def test_and_the_ceiling_is_reachable_so_it_is_a_guard_not_a_latch():
    # `lesson_gate_that_cannot_fail`: a cap nothing can trip is not a cap.
    tree = _accum({"type": "op", "name": "+",
                   "args": [_self_at(ai.MAX_SELF_LAG), {"type": "num", "value": 0}]})
    col = ai.interpret(tree, _bars(), {})
    assert any(v is not None for v in col)


def test_an_offset_over_an_expression_still_refuses():
    """`(self + close)[1]` asks for a past value of a formula the step loop never
    computed. Refusing it keeps ``self[k]`` meaning exactly "the running value k
    bars ago" rather than something a reader has to derive."""
    inner = {"type": "op", "name": "+",
             "args": [{"type": "series", "name": "self"}, {"type": "series", "name": "close"}]}
    tree = _accum({"type": "offset", "value": 1, "args": [inner]})
    with pytest.raises(Exception) as err:
        ai.interpret(tree, _bars(), {})
    assert "never computed" in str(err.value)


def test_the_two_lanes_declare_the_same_ceiling():
    """⛔ A cap that differs between lanes is a formula that draws on a chart and
    refuses in the scanner. Read from the JS source, never retyped."""
    js = pathlib.Path(__file__).parents[1] / "app" / "src" / "components" / "chart" / "engine" / "ast" / "interpret.js"
    text = io.open(js, encoding="utf-8").read()
    marker = "export const MAX_SELF_LAG = "
    assert marker in text, "the JS lane no longer declares MAX_SELF_LAG"
    declared = int(text.split(marker, 1)[1].split("\n", 1)[0].strip())
    assert declared == ai.MAX_SELF_LAG
