"""TERM-046 — short interest moves onto Finviz behind SHORT_INTEREST_SOURCE.

Recorded fixtures only, no network anywhere:
  * tests/fixtures/short_interest/yfinance_flag_off_golden.json — the exact bytes
    the PRE-TERM-046 get_short_interest produced (generated by exec'ing the base
    blob), which the flag-off path must still produce.
  * tests/fixtures/short_interest/parity_recorded.json — Finviz's own values and
    yfinance's .info for six tickers, recorded in the same minute on 2026-09-29.

The Finviz artifact is built through the REAL finviz_universe.run_pull (fetch
stubbed with the recorded cells), so the path under test is the one production
runs: export CSV -> _parse -> artifact -> short_interest.
"""
import json
import os
from datetime import date
from pathlib import Path

import pytest

from api.services import short_interest as si
from api.services import yf_util
from api.services.screener import finviz_universe as fv

FIX = Path(__file__).parent / "fixtures" / "short_interest"
GOLDEN = json.loads((FIX / "yfinance_flag_off_golden.json").read_text(encoding="utf-8"))
PARITY = json.loads((FIX / "parity_recorded.json").read_text(encoding="utf-8"))
PULL_ISO = "2026-09-29T06:45:03+00:00"      # 02:45 ET on the recording day
HEADERS = ["Ticker", "Shares Outstanding", "Shares Float", "Short Float", "Short Ratio"]


@pytest.fixture(autouse=True)
def _isolate(monkeypatch, tmp_path):
    monkeypatch.delenv("SHORT_INTEREST_SOURCE", raising=False)
    monkeypatch.setenv("SCREENER_FINVIZ_ARTIFACT", str(tmp_path / "screener_finviz.json"))
    monkeypatch.setenv("SHORT_INTEREST_HISTORY_DB_PATH", str(tmp_path / "si_hist.db"))
    monkeypatch.setattr(si, "_today_et", lambda: date(2026, 9, 29))
    si._CACHE = type(si._CACHE)()
    si._SNAP.update(key=None, snap=None)
    yield


def _fv_row(sym):
    p = PARITY["tickers"][sym]["finviz_quote_page"]
    return [sym, p["Shs Outstand"], p["Shs Float"], p["Short Float"], p["Short Ratio"]]


def _csv(rows):
    return "\n".join(",".join(r) for r in [HEADERS] + rows) + "\n"


def _pull(monkeypatch, rows, as_of=PULL_ISO):
    """The real run_pull, fetch stubbed; padded past _MIN_ROWS with filler."""
    filler = [[f"Z{i:04d}", "100.00M", "90.00M", "1.00%", "1.00"] for i in range(fv._MIN_ROWS)]
    monkeypatch.setattr(fv, "_fetch_finviz_csv_text", lambda: _csv(rows + filler))
    monkeypatch.setattr(fv, "_now_iso", lambda: as_of)
    si._SNAP.update(key=None, snap=None)
    return fv.run_pull()


def _stub_yf(monkeypatch, infos):
    current = {}

    def fake(fn, default, *a, **k):
        return infos.get(current["sym"])

    monkeypatch.setattr(yf_util, "bounded_call", fake)
    return current


# ── the flag ─────────────────────────────────────────────────────────────────

def test_the_default_source_is_yfinance_in_the_literal_and_the_behaviour(monkeypatch):
    assert si.SHORT_INTEREST_MODE_FLAGS["SHORT_INTEREST_SOURCE"][0] == "yfinance"
    assert si.source() == "yfinance"
    for junk in ("", "  ", "FINVIZZ", "finra", "1"):
        monkeypatch.setenv("SHORT_INTEREST_SOURCE", junk)
        assert si.source() == "yfinance", junk
    monkeypatch.setenv("SHORT_INTEREST_SOURCE", " Finviz ")
    assert si.source() == "finviz"


@pytest.mark.parametrize("env", [None, "", "not-a-source"])
@pytest.mark.parametrize("case", sorted(GOLDEN["golden"]))
def test_flag_off_is_byte_identical_to_the_pre_term046_code(monkeypatch, case, env, tmp_path):
    if env is not None:
        monkeypatch.setenv("SHORT_INTEREST_SOURCE", env)
    current = _stub_yf(monkeypatch, GOLDEN["infos"])
    touched = []
    monkeypatch.setattr(si, "_load_finviz_snapshot", lambda: touched.append(1))
    current["sym"] = (case or "").upper().strip()
    si._CACHE = type(si._CACHE)()
    assert json.dumps(si.get_short_interest(case)) == GOLDEN["golden"][case]
    assert not touched, "flag off must never read the Finviz artifact"
    assert not (tmp_path / "si_hist.db").exists(), "flag off must write no history"


def test_the_golden_is_not_vacuous():
    """Control: the golden covers every branch of the old function — data, both
    error shapes, the empty-ticker refusal — so byte-equality above means something."""
    g = GOLDEN["golden"]
    assert len(g) >= 15
    assert json.loads(g["AAPL"])["shares_short"] == 128753092
    assert json.loads(g["NONEINFO"])["error"].startswith("yfinance failed")
    assert json.loads(g["EMPTY"])["error"] == "no short interest data available"
    assert json.loads(g[""]) == {"error": "ticker required"}
    assert {json.loads(g[k])["crowded"] for k in ("AAPL", "MODERATE", "HIGH", "VHIGH")} == {
        "low", "moderate", "high", "very_high"}


# ── the Finviz path ─────────────────────────────────────────────────────────

def _armed(monkeypatch):
    monkeypatch.setenv("SHORT_INTEREST_SOURCE", "finviz")
    rows = [_fv_row(s) for s in PARITY["tickers"]]
    return _pull(monkeypatch, rows)


def test_finviz_path_keeps_every_consumer_field_and_reads_no_yfinance(monkeypatch):
    _armed(monkeypatch)
    monkeypatch.setattr(yf_util, "bounded_call",
                        lambda *a, **k: pytest.fail("finviz path must not call yfinance"))
    out = si.get_short_interest("aapl")
    old_keys = list(json.loads(GOLDEN["golden"]["AAPL"]))
    assert list(out)[:len(old_keys)] == old_keys, "shared keys, same order"
    assert out["short_pct_of_float"] == 0.88
    assert out["days_to_cover"] == 2.71
    assert out["shares_short"] == round(0.0088 * 14.58e9)
    assert out["crowded"] == "low"
    assert out["licensing_class"] == "LA"
    assert out["source"].startswith("finviz")
    assert out["shares_short_prior_month"] is None, "no history yet -> unknown, not zero"
    assert out["shares_short_change_pct"] is None


def test_as_of_is_the_settlement_date_never_the_pull_date(monkeypatch):
    receipt = _armed(monkeypatch)
    assert receipt["wrote"] is True
    for sym, rec in PARITY["tickers"].items():
        out = si.get_short_interest(sym)
        assert out["as_of_date"] == "2026-09-15", sym
        # ⭐ the inference agrees with FINRA's own date as Yahoo reports it
        assert out["as_of"] == rec["yfinance_info"]["dateShortInterest"], sym
        assert out["as_of_date"] != "2026-09-29"
        assert out["pulled_at"] == PULL_ISO
        assert "inferred" in out["as_of_basis"]


def test_the_ambiguous_day_reports_no_date_rather_than_a_guess(monkeypatch):
    monkeypatch.setenv("SHORT_INTEREST_SOURCE", "finviz")
    _pull(monkeypatch, [_fv_row("AAPL")], as_of="2026-09-25T06:45:00+00:00")
    out = si.get_short_interest("AAPL")
    assert out["as_of"] is None and out["as_of_date"] is None
    assert out["as_of_candidates"] == ["2026-08-31", "2026-09-15"]
    assert out["short_pct_of_float"] == 0.88, "the value is still served"


@pytest.mark.parametrize("pulled_on,expected", [
    (date(2026, 9, 29), date(2026, 9, 15)),
    (date(2026, 9, 28), date(2026, 9, 15)),     # S+9 business days: certain
    (date(2026, 9, 24), date(2026, 8, 31)),     # Labor Day inside the window
    (date(2026, 10, 14), date(2026, 9, 30)),
])
def test_infer_settlement_table(pulled_on, expected):
    assert si.infer_settlement(pulled_on) == {"settlement": expected, "candidates": []}


def test_settlement_calendar_follows_the_holiday_list():
    # 2027-02-15 is Presidents Day -> the mid-month settlement moves to Fri 02-12
    assert date(2027, 2, 12) in si.settlement_dates_before(date(2027, 2, 20), 2)
    # Yahoo's sharesShortPreviousMonthDate on the recording day is two steps back
    assert si.settlement_dates_before(date(2026, 9, 15), 3)[2] == date(2026, 8, 14)


def test_unknown_is_never_rendered_as_zero_or_low(monkeypatch):
    monkeypatch.setenv("SHORT_INTEREST_SOURCE", "finviz")
    _pull(monkeypatch, [
        ["NOPCT", "100.00M", "90.00M", "-", "3.10"],       # short float unknown
        ["ZERO", "100.00M", "90.00M", "0.00%", "0.00"],     # a real zero
        ["NOSHORT", "100.00M", "90.00M", "-", "-"],         # nothing at all
        ["NOFLOAT", "100.00M", "-", "4.00%", "1.00"],       # float unknown
    ])
    nopct = si.get_short_interest("NOPCT")
    assert nopct["short_pct_of_float"] is None
    assert nopct["shares_short"] is None
    assert nopct["crowded"] is None, "unknown short float is not 'low'"
    assert nopct["days_to_cover"] == 3.1

    zero = si.get_short_interest("ZERO")
    assert zero["short_pct_of_float"] == 0.0 and zero["shares_short"] == 0
    assert zero["crowded"] == "low"

    assert si.get_short_interest("NOSHORT") == {
        "ticker": "NOSHORT", "error": "no short interest data available"}

    nofloat = si.get_short_interest("NOFLOAT")
    assert nofloat["short_pct_of_float"] == 4.0
    assert nofloat["shares_short"] is None, "no float -> shares short unknown, not 0"
    assert nofloat["short_pct_of_shares_outstanding"] is None


def test_a_missing_header_is_unknown_for_every_ticker(monkeypatch, tmp_path):
    _armed(monkeypatch)
    path = Path(os.environ["SCREENER_FINVIZ_ARTIFACT"])
    blob = json.loads(path.read_text(encoding="utf-8"))
    blob["missing_headers"] = ["short_float_pct"]
    path.write_text(json.dumps(blob), encoding="utf-8")
    si._SNAP.update(key=None, snap=None)
    out = si.get_short_interest("GME")
    assert out["short_pct_of_float"] is None and out["crowded"] is None
    assert out["days_to_cover"] == 5.76


def test_no_artifact_and_unknown_ticker_degrade_to_error_dicts(monkeypatch):
    monkeypatch.setenv("SHORT_INTEREST_SOURCE", "finviz")
    miss = si.get_short_interest("AAPL")
    assert miss["ticker"] == "AAPL" and miss["error"].startswith("finviz failed")
    _armed(monkeypatch)
    assert si.get_short_interest("NOTATICKER")["error"] == "no short interest data available"
    assert si.get_short_interest("") == {"error": "ticker required"}


def test_the_provider_envelope_is_stamped(monkeypatch):
    _armed(monkeypatch)
    res = si.fetch_finviz_short_interest("NVDA")
    assert res.licensing_class == "LA"
    assert res.provenance.vendor == "finviz"
    assert res.provenance.source_observed_at == 1789430400.0
    assert res.freshness is None
    monkeypatch.setattr(si, "_today_et", lambda: date(2026, 10, 9))
    assert si.fetch_finviz_short_interest("NVDA").freshness == "stale"


# ── history ─────────────────────────────────────────────────────────────────

def test_flag_off_pull_writes_no_history_and_an_unchanged_receipt(monkeypatch, tmp_path):
    receipt = _pull(monkeypatch, [_fv_row("AAPL")])
    assert set(receipt) == {"rows", "kept", "missing_headers", "bare_pct", "wrote", "as_of"}
    assert not (tmp_path / "si_hist.db").exists()


def test_history_is_dated_append_only_and_first_write_wins(monkeypatch):
    receipt = _armed(monkeypatch)
    h = receipt["short_interest_history"]
    assert h["settlement_date"] == "2026-09-15"
    assert h["recorded"] == len(PARITY["tickers"]) + fv._MIN_ROWS
    # same settlement, a changed value on a later pull: the first row stands
    rows = [_fv_row(s) for s in PARITY["tickers"]]
    rows[0][3] = "5.00%"
    again = _pull(monkeypatch, rows, as_of="2026-09-30T06:45:00+00:00")
    assert again["short_interest_history"]["recorded"] == 0
    series = si.get_short_interest_history("AAPL")
    assert series == [{"settlement_date": "2026-09-15", "shares_short": round(0.0088 * 14.58e9),
                       "short_float_pct": 0.88, "short_ratio": 2.71, "pulled_at": PULL_ISO}]


def test_an_ambiguous_pull_records_nothing(monkeypatch):
    monkeypatch.setenv("SHORT_INTEREST_SOURCE", "finviz")
    r = _pull(monkeypatch, [_fv_row("AAPL")], as_of="2026-09-25T06:45:00+00:00")
    assert r["short_interest_history"]["recorded"] == 0
    assert r["short_interest_history"]["skipped"] == "settlement_ambiguous"
    assert si.get_short_interest_history("AAPL") == []


def test_prior_month_comes_only_from_recorded_history(monkeypatch):
    monkeypatch.setenv("SHORT_INTEREST_SOURCE", "finviz")
    # a month earlier: a pull that represents the 2026-08-14 settlement
    _pull(monkeypatch, [["AAPL", "14.61B", "14.58B", "0.80%", "2.50"]],
          as_of="2026-08-27T06:45:00+00:00")
    _armed(monkeypatch)
    out = si.get_short_interest("AAPL")
    prior = round(0.0080 * 14.58e9)
    assert out["shares_short_prior_month"] == prior
    assert out["shares_short_change_pct"] == round((round(0.0088 * 14.58e9) - prior) / prior * 100, 2)
    assert "shares_short_prior_month" in out["derived_fields"]


# ── parity, by field ────────────────────────────────────────────────────────

# Finviz (flag on) vs yfinance (flag off), on the frozen recording. Pinned as a
# table so the differences are a reviewed fact, not a summary percentage.
EXPECTED_PARITY = {
    #        short_pct_of_float  days_to_cover   shares_short (finviz derived, yahoo)
    "AAPL": ((0.88, 0.88), (2.71, 3.03), (128304000, 128753092)),
    "NVDA": ((1.27, 1.27), (2.36, 2.29), (294513000, 294225803)),
    "TSLA": ((2.44, 1.95), (1.76, 1.79), (68808000, 68862357)),
    "GME":  ((9.45, 8.4),  (5.76, 5.27), (39054015, 39069126)),
    "CVNA": ((9.25, 11.63), (6.95, 8.14), (62208100, 62226156)),
    "PLTR": ((2.72, 2.8),  (1.64, 2.08), (60112000, 60184903)),
}


def test_parity_by_field_on_recorded_fixtures(monkeypatch):
    _armed(monkeypatch)
    fin = {s: si.get_short_interest(s) for s in PARITY["tickers"]}
    monkeypatch.delenv("SHORT_INTEREST_SOURCE")
    current = _stub_yf(monkeypatch, {s: d["yfinance_info"] for s, d in PARITY["tickers"].items()})
    yah = {}
    for s in PARITY["tickers"]:
        current["sym"] = s
        si._CACHE = type(si._CACHE)()
        yah[s] = si.get_short_interest(s)
    got = {s: ((fin[s]["short_pct_of_float"], yah[s]["short_pct_of_float"]),
               (fin[s]["days_to_cover"], yah[s]["days_to_cover"]),
               (fin[s]["shares_short"], yah[s]["shares_short"])) for s in fin}
    assert got == EXPECTED_PARITY
    for s in fin:
        # derived shares short sits within Short Float's 2-decimal rounding of FINRA's
        rel = abs(fin[s]["shares_short"] - yah[s]["shares_short"]) / yah[s]["shares_short"]
        assert rel < 0.01, (s, rel)
        assert fin[s]["as_of"] == yah[s]["as_of"], s
        # Yahoo carries prior-month from FINRA; Finviz cannot until history exists
        assert yah[s]["shares_short_prior_month"] is not None
        assert fin[s]["shares_short_prior_month"] is None
        # Yahoo leaves % of shares outstanding empty on every recorded ticker
        assert yah[s]["short_pct_of_shares_outstanding"] is None
        assert fin[s]["short_pct_of_shares_outstanding"] is not None
