/**
 * EXPLAIN-MOUNT GUARD — PACKET-AA CP2 (2026-09-25).
 *
 * Structural, like wiring.guard.test.js beside it, because OptionsFlow.jsx is a
 * partner-owned ~9k-line file edited concurrently and a stale-buffer save can
 * silently drop an additive mount without breaking the page (the exact class
 * wiring.guard exists for). It reads the source and asserts the ONE mount CP2
 * added is still there, still additive, and still passes the print the way the
 * backend's FlowPrint model needs it.
 *
 * ⛔ `spot` MUST be the UNDERLYING. In the contract-detail panel `curPrice` is
 * the OPTION's mark (`px.mark || px.last || px.mid`) and `px.spot` is the
 * underlying (`q.underlyingPrice`). Passing `curPrice` as `spot` would feed the
 * explainer a $2.35 "stock price" for a $180 stock and every read it produced
 * would be confidently wrong. That trap is railed by name below.
 *
 * If a case fails, re-apply the mount (three insertions: the import after
 * FlowIcon's, a <th className="of-explain">, a <td className="of-explain">
 * inside the strikeTrades row) — do not edit this file. If CP2 was reverted ON
 * PURPOSE, delete this file in the same commit and restore the
 * FlowExplainButton entry in components/screener/reachable.test.js.
 */
import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

const FILE = path.resolve(__dirname, '../OptionsFlow.jsx')
const CODE = fs.readFileSync(FILE, 'utf8')

// The Strike Flow Detail table's row map is the ONLY strikeTrades.map in the
// file; the region under test runs from it to the tbody that closes it.
function strikeRowRegion() {
  const start = CODE.indexOf('{strikeTrades.map((tr,i)=>(')
  const end = CODE.indexOf('</tbody>', start)
  return { start, end, text: start >= 0 && end > start ? CODE.slice(start, end) : '' }
}

describe('PACKET-AA CP2 — the explain trigger is mounted on the Strike Flow Detail rows', () => {
  it('control: the Strike Flow Detail row map still exists exactly once (the guard can see it)', () => {
    expect(CODE.split('{strikeTrades.map((tr,i)=>(').length - 1).toBe(1)
    expect(strikeRowRegion().text.length).toBeGreaterThan(200)
  })

  it('imports the CP1 component from its own home beside FlowIcon', () => {
    expect(CODE.includes('import FlowExplainButton from "./optionsFlow/FlowExplainButton";')).toBe(true)
    expect(CODE.includes('import FlowIcon from "./optionsFlow/FlowIcon";')).toBe(true)
  })

  it('adds exactly two of-explain hooks: one header cell, one row cell', () => {
    const hooks = CODE.match(/className="of-explain"/g) || []
    expect(hooks.length).toBe(2)
    expect(/<th key="explain" className="of-explain"/.test(CODE)).toBe(true)
    expect(/<td className="of-explain"/.test(strikeRowRegion().text)).toBe(true)
  })

  it('mounts FlowExplainButton inside the strikeTrades row, and nowhere else', () => {
    expect((CODE.match(/<FlowExplainButton\b/g) || []).length).toBe(1)
    expect(/<FlowExplainButton\b/.test(strikeRowRegion().text)).toBe(true)
  })

  it('passes the print in FlowPrint shape: ticker, cp, strike, ISO exp, dte, premium, volume, oi, side, spot, order_type, color', () => {
    const t = strikeRowRegion().text
    for (const key of ['ticker:sym', 'cp,', 'strike:parseFloat(K)', 'exp:expToISO(exp)', 'dte:Math.max(0,',
      'premium:tr.P', 'volume:Math.round(tr.V', 'oi:Math.round(tr.OI', 'order_type:tr.Ty', 'color:tr.Co']) {
      expect(t.includes(key), `print is missing ${key}`).toBe(true)
    }
    // side is translated from the row's AA/BB/B/A codes into the strings
    // flow_explain._aggression actually matches — never the raw codes.
    for (const label of ['"ABOVE ASK"', '"BELOW BID"', '"BID"', '"ASK"']) {
      expect(t.includes(`:${label}`) || t.includes(`?${label}`), `side mapping lacks ${label}`).toBe(true)
    }
  })

  it('⛔ spot is the UNDERLYING (px.spot), never the option mark (curPrice), and the trigger waits for it', () => {
    const t = strikeRowRegion().text
    expect(/spot:px\?\.spot\|\|0/.test(t)).toBe(true)
    expect(/spot:\s*curPrice/.test(t)).toBe(false)
    // the endpoint requires spot > 0, so the button is gated on it instead of
    // rendering a trigger whose every tap would 422
    expect(t.includes('{(px?.spot||0)>0 && <FlowExplainButton')).toBe(true)
  })

  it('is additive: the pre-existing header array and every original Price cell are untouched', () => {
    expect(CODE.includes('{["Day","Time","Type","Side","Color","Vol","OI","Premium","Price"].map(h=>(')).toBe(true)
    expect(strikeRowRegion().text.includes('{tr.price>0?"$"+tr.price.toFixed(2):"—"}</td>')).toBe(true)
  })
})
