"""Regenerate the Breadth Library search fixtures the JS lane is pinned to.

    python tools/breadth/gen_library_search_fixtures.py

⭐ THE PYTHON RANKING (`breadth_symbols.library_search`) IS THE REFERENCE. This script runs it
over every universe as if published, with the active publication set, and writes:

  app/src/components/chart/__fixtures__/breadthLibraryRows.json    the catalogue the JS lane ranks
  app/src/components/chart/__fixtures__/breadthSearchParity.json   query → expected symbols

⛔ NEVER HAND-EDIT EITHER FILE TO MAKE A TEST PASS. If `breadthLibrary.parity.test.js` goes red,
one lane drifted: fix that lane, then re-run this.

⚠️ Deterministic and offline: universes are forced published, and availability (which reads the
live stores) is replaced by the static universe floors, so the output depends only on code.
"""
from __future__ import annotations

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, ROOT)

from api.services import breadth_symbols as bs      # noqa: E402
from api.services import breadth_universes as bu    # noqa: E402

FIX = os.path.join(ROOT, "app", "src", "components", "chart", "__fixtures__")

QUERIES = [
    "50 day", "50 MA", "above 50", "A50", "NASDAQ breadth", "NYSE breadth", "US breadth",
    "high low", "new highs", "new lows", "net high low", "NETHL", "200 day", "above 200",
    "momentum", "NASDAQ:A50", "US:NETHL", "UCTA50", "UCT:A50", "NASDAQ:AAPL", "FOO:BAR",
    # ⭐ finishing pass (2026-10-07): the trader spellings `_QUERY_SYNONYMS` exists for
    "percent above 50-day", "pct above 200", "50 dma", "20 sma", "advancers", "decliners",
    "advancing issues", "NYSE advancing", "stage 2", "up 25%", "new 20-day highs",
]


def main() -> None:
    bu.published_universe_ids = lambda: list(bu.UNIVERSE_IDS)          # all universes "published"
    bs.display_floor = lambda uid: None                                  # static floors, no stores
    bs.availability = lambda: {u: {"state": "not_populated", "rows": 0, "first": None,
                                   "last": None} for u in bu.UNIVERSE_IDS}
    cat = bs.library_catalog(published_only=True)
    rows = cat["rows"]
    with open(os.path.join(FIX, "breadthLibraryRows.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump({k: cat[k] for k in ("rows", "families", "universes", "metric_order")}, f, indent=0)
        f.write("\n")
    queries = {q: [r["symbol"] for r in bs.library_search(q, limit=12, published_only=True)]
               for q in QUERIES}
    with open(os.path.join(FIX, "breadthSearchParity.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump({"_note": "GENERATED by tools/breadth/gen_library_search_fixtures.py from "
                            "breadth_symbols.library_search with all universes published. "
                            "The JS matcher must agree.",
                   "synonyms": dict(sorted(bs._QUERY_SYNONYMS.items())),
                   "queries": queries}, f, indent=0)
        f.write("\n")
    print(f"rows={len(rows)} queries={len(queries)}")


if __name__ == "__main__":
    main()
