// ONE-TIME NORMALISATION OF THE THREE-PANE COT GROUP (f288540c4) → ONE PANE.
//
// ⭐ THE FIXTURES ARE THE DEPLOYED CODE'S OWN OUTPUT. `legacyCotThreePane.f288540c4.json`
// was generated by running `createFromResult` AT f288540c4 — the release that served the
// three-pane layout — over the product row production returned, so these cases convert
// exactly what members could have saved, not a hand-written approximation of it.

import { describe, it, expect } from 'vitest'
import legacy from '../__fixtures__/legacyCotThreePane.f288540c4.json'
import { migrateLegacyCotGroups, PANE_TARGET_PREFIX } from '../engine/legacyCotGroups'
import { paneOfTarget, parsePaneOfTarget } from '../engine/sourceRef'
import { mergeChartSettings } from '../chartDefaults'
import { mergeSettingsOverride } from '../instanceShape'
import { marketIndicatorResults, createFromResult, sideBySideBars, GROUP_PANE_HEIGHT } from '../discoveryCatalog'
import { removeInstance, addInstance } from '../engine/instanceControls'
import { paneOwnKeys, paneOwnerOf } from '../engine/displayTarget'
import { presentedPlot } from '../engine/presentation'
import { poolKey } from '../engine/pool'
import * as registry from '../engine/nativeRegistry'

const clone = (x) => JSON.parse(JSON.stringify(x))
const live = (cs) => (cs.indicatorInstances || []).filter((i) => i && !i.deleted && i.instanceId)
const cot = (cs) => live(cs).filter((i) => String(i.inputs?.source || '').startsWith('sym:COT:'))
const load = (blob) => mergeChartSettings(clone(blob))
const hosts = (cs) => [...paneOwnKeys(cs.indicatorInstances, cs)]
const cotHosts = (cs) => hosts(cs).filter((k) => cot(cs).some((i) => i.instanceId === k))

describe('the old three-pane save', () => {
  it('the fixture IS the three-pane form (guard against a fixture that drifted)', () => {
    const parts = cot(legacy.one)
    expect(parts).toHaveLength(3)
    expect(parts.every((p) => !p.placement && !p.presentation.bar && !p.group.note)).toBe(true)
    expect(hosts(legacy.one).filter((k) => parts.some((p) => p.instanceId === k))).toHaveLength(3)
  })

  it('1–3 · loads as ONE pane holding exactly three participant series, no orphan panes', () => {
    const cs = load(legacy.one)
    const parts = cot(cs)
    expect(parts).toHaveLength(3)
    expect(cotHosts(cs)).toEqual([parts[0].instanceId])
    for (const p of parts) expect(paneOwnerOf(p, cs)).toBe(parts[0].instanceId)
  })

  it('4–5 · dataset and logical-instance identity are preserved', () => {
    const before = cot(legacy.one)
    const after = cot(load(legacy.one))
    expect(after.map((p) => p.instanceId)).toEqual(before.map((p) => p.instanceId))
    expect(after.map((p) => p.inputs.source)).toEqual(before.map((p) => p.inputs.source))
    expect(new Set(after.map((p) => p.group.id))).toEqual(new Set([before[0].group.id]))
    expect(after[0].group).toEqual({ id: before[0].group.id, name: 'Nasdaq-100 E-Mini · COT', note: 'Net Contracts' })
  })

  it('8–10 · histograms, colours and the accepted one-pane presentation', () => {
    const after = cot(load(legacy.one))
    const def = registry.getDefinition('dataSeries')
    expect(after.map((p) => p.presentation.bar)).toEqual(sideBySideBars(3))
    expect(after.map((p) => p.inputs.color)).toEqual(['#2d8c4e', '#b18c33', '#4a90c2'])
    for (const p of after) expect(poolKey(presentedPlot(def.plots[0], p))).toBe('columns')
    expect(after[0].presentation.paneHeight).toBe(GROUP_PANE_HEIGHT)
  })

  it('it arrives IDENTICAL to a fresh add of the accepted single-pane implementation', () => {
    const cat = marketIndicatorResults([{
      id: 'COT:NQ', kind: 'product', symbol: 'COT:NQ', display: 'Nasdaq-100 E-Mini COT', short: 'NQ COT',
      family: 'positioning', family_label: 'Positioning', presentation: 'histogram', grouped: true,
      group_title: 'Nasdaq-100 E-Mini · COT', group_note: 'Net Contracts',
      components: ['COT:NQ:COMM', 'COT:NQ:LARGE', 'COT:NQ:SMALL'],
      component_rows: ['Commercials', 'Large Speculators', 'Small Speculators'].map((n, k) => ({
        id: `COT:NQ:${['COMM', 'LARGE', 'SMALL'][k]}`, display: `Nasdaq-100 E-Mini COT · ${n}`, short: n,
        presentation: 'histogram', domain: 'signed', palette: ['cot.commercials', 'cot.largeSpecs', 'cot.smallSpecs'][k] })),
    }])[0]
    const fresh = cot(createFromResult(mergeChartSettings({}), cat, registry))
    const strip = (p) => ({ ...p, instanceId: undefined, group: { ...p.group, id: undefined },
      placement: p.placement ? { target: p.placement.target.replace(p.placement.target.slice(1), 'HOST') } : undefined })
    expect(cot(load(legacy.one)).map(strip)).toEqual(fresh.map(strip))
  })

  it('6–7 · the Commercials pane keeps its place; stored heights give way to the 22% default', () => {
    const [c, l, s] = cot(legacy.arranged).map((p) => p.instanceId)
    expect(legacy.arranged.paneOrder).toEqual(['price', l, 'volume', c, s])
    const cs = load(legacy.arranged)
    expect(cs.paneOrder).toEqual(['price', 'volume', c])
    expect(cs.paneSizes || {}).toEqual({})           // never the sum of three
    // …and the member's recolour survives.
    expect(cot(cs)[1].inputs.color).toBe('#ff00aa')
  })

  it('visibility survives: a hidden old group arrives as a hidden one-pane group', () => {
    const cs = load(legacy.hidden)
    expect(cot(cs).map((p) => p.hidden)).toEqual([true, true, true])
    expect(cot(cs).every((p) => p.presentation.bar)).toBe(true)
  })

  it('15 · two old NQ groups convert into TWO independent single panes', () => {
    const cs = load(legacy.two)
    expect(cot(cs)).toHaveLength(6)
    expect(cotHosts(cs)).toHaveLength(2)
    expect(new Set(cot(cs).map((p) => p.group.id)).size).toBe(2)
    const [a] = cot(cs)
    expect(cot(removeInstance(cs, a.instanceId, registry))).toHaveLength(3)
  })

  it('16 · different markets stay independent; 19 · RSI, Price and Volume are untouched', () => {
    const before = legacy.mixed
    const cs = load(before)
    expect(cotHosts(cs)).toHaveLength(2)
    const names = cot(cs).filter((p) => p.presentation.paneHeight).map((p) => p.group.name)
    expect(names).toEqual(['Nasdaq-100 E-Mini · COT', 'S&P 500 E-Mini · COT'])
    const other = (x) => live(x).filter((i) => !String(i.inputs?.source || '').startsWith('sym:COT:'))
    expect(other(cs)).toEqual(other(load({ ...before, indicatorInstances: other(before) })))
    expect(hosts(cs)).toContain(live(cs).find((i) => i.defId === 'rsi').instanceId)
  })
})

describe('the entry-bundle constraint', () => {
  it('the inlined pane-target prefix is exactly the one sourceRef writes and parses', () => {
    expect(paneOfTarget('inst:dataSeries:1')).toBe(`${PANE_TARGET_PREFIX}inst:dataSeries:1`)
    const [host, guest] = cot(load(legacy.one))
    expect(parsePaneOfTarget(guest.placement.target)).toBe(host.instanceId)
  })
})

describe('idempotence', () => {
  it('12 · an already-new single-pane state is returned by IDENTITY', () => {
    const cs = load(legacy.one)
    expect(migrateLegacyCotGroups(cs)).toBe(cs)
  })

  it('13–14 · loading twice, and save → reload, stay one pane and change nothing', () => {
    const once = load(legacy.arranged)
    const twice = load(clone(once))
    expect(twice.indicatorInstances).toEqual(once.indicatorInstances)
    expect(twice.paneOrder).toEqual(once.paneOrder)
    expect(twice.paneSizes).toEqual(once.paneSizes)
    expect(cotHosts(twice)).toHaveLength(1)
  })

  it('a chart TAB’s own settings (mergeSettingsOverride) convert too, and only once', () => {
    const base = mergeChartSettings({})
    const merged = mergeSettingsOverride(base, clone({ indicatorInstances: legacy.one.indicatorInstances }))
    expect(cotHosts(merged)).toHaveLength(1)
    expect(migrateLegacyCotGroups(merged)).toBe(merged)
  })
})

describe('17–18 · ambiguous or unrelated state is LEFT EXACTLY ALONE', () => {
  const parts = () => clone(cot(legacy.one))
  const blob = (instances, extra = {}) => ({ indicatorInstances: instances, ...extra })
  const unchanged = (b) => expect(migrateLegacyCotGroups(b)).toBe(b)

  it('only Commercials / Commercials + Large (a partial group)', () => {
    unchanged(blob(parts().slice(0, 1)))
    unchanged(blob(parts().slice(0, 2)))
  })

  it('a child that was deleted (tombstoned)', () => {
    const p = parts(); p[2] = { instanceId: p[2].instanceId, deleted: true }
    unchanged(blob(p))
  })

  it('a duplicated child', () => {
    const p = parts(); p[2] = { ...p[1], instanceId: 'inst:dataSeries:9' }
    unchanged(blob(p))
  })

  it('mixed markets under one group id', () => {
    const p = parts(); p[2] = { ...p[2], inputs: { ...p[2].inputs, source: 'sym:COT:ES:SMALL:close' } }
    unchanged(blob(p))
  })

  it('a group id that does not name the Commercials part', () => {
    const p = parts().map((i) => ({ ...i, group: { ...i.group, id: 'grp:inst:dataSeries:2' } }))
    unchanged(blob(p))
  })

  it('a part the member moved into another pane', () => {
    const p = parts(); p[1] = { ...p[1], placement: { target: '@inst:rsi:1' } }
    unchanged(blob(p))
  })

  it('parts hidden differently', () => {
    const p = parts(); p[1] = { ...p[1], hidden: true }
    unchanged(blob(p))
  })

  it('three ungrouped series named Commercials / Large / Small', () => {
    const p = parts().map(({ group: _g, ...i }) => i)
    unchanged(blob(p))
  })

  it('an ordinary three-own-pane arrangement (QQQ / SPY / NVDA)', () => {
    let cs = { indicatorInstances: [] }
    for (let k = 0; k < 3; k++) cs = addInstance(cs, 'dataSeries', registry)
    cs = { ...cs, indicatorInstances: cs.indicatorInstances.map((i, k) => ({
      ...i, inputs: { ...i.inputs, source: `sym:${['QQQ', 'SPY', 'NVDA'][k]}:close` } })),
    paneOrder: ['price', 'volume'] }
    unchanged(cs)
  })

  it('no instances at all / not a blob', () => {
    unchanged(blob([]))
    expect(migrateLegacyCotGroups(null)).toBe(null)
    const noList = { candles: {} }
    expect(migrateLegacyCotGroups(noList)).toBe(noList)
  })
})
