import { describe, it, expect } from 'vitest'
import { Schema, Node } from 'prosemirror-model'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  DEGRADED,
  RERESOLVED_EXACT,
  VALID_EXACT,
  VALID_NOTE_ONLY,
  citationText,
  citedSources,
  flatToPmRange,
  resolveNoteCitation,
  splitAnswer,
} from './askCitation'

// ─────────────────────────────────────────────────────────────────────────
// WAVE K SLICE 6 — PARITY, NOT A SECOND AUTHORITY.
//
// Citation resolution now exists twice: in Python
// (note_citation_text.resolve_note_citation, which decides what the server may
// SEND) and here (which decides whether a click may NAVIGATE). Two
// implementations of one rule is the second-authority defect this repo keeps
// paying for, so they are pinned to the SAME ground truth —
// tests/fixtures_pm_citation_text.json, generated by
// tools/gen_pm_citation_fixtures.cjs from real prosemirror-model, and already
// the fixture the Python rails read.
//
// The schema below is copied from that generator on purpose: the fixtures were
// produced under it, so parsing them under anything else would compare this
// code against a doc the ground truth never described.
// ─────────────────────────────────────────────────────────────────────────

const schema = new Schema({
  nodes: {
    doc: { content: 'block+' },
    paragraph: { group: 'block', content: 'inline*', toDOM: () => ['p', 0] },
    heading: { group: 'block', content: 'inline*', attrs: { level: { default: 1 } }, toDOM: () => ['h1', 0] },
    blockquote: { group: 'block', content: 'block+', toDOM: () => ['blockquote', 0] },
    bulletList: { group: 'block', content: 'listItem+', toDOM: () => ['ul', 0] },
    listItem: { content: 'paragraph+', toDOM: () => ['li', 0] },
    text: { group: 'inline' },
    attachmentChip: { group: 'inline', inline: true, atom: true, attrs: { name: { default: 'file' } }, toDOM: () => ['a'] },
    documentExcerpt: { group: 'block', atom: true, toDOM: () => ['div'] },
  },
  marks: {
    bold: { toDOM: () => ['strong', 0] },
    italic: { toDOM: () => ['em', 0] },
    link: { attrs: { href: { default: '' } }, toDOM: () => ['a', 0] },
  },
})

const HERE = path.dirname(fileURLToPath(import.meta.url))
const FIXTURES = JSON.parse(fs.readFileSync(
  path.resolve(HERE, '../../../../../tests/fixtures_pm_citation_text.json'), 'utf8'))

const docOf = (name) => Node.fromJSON(schema, FIXTURES[name].json)
const NAMES = Object.keys(FIXTURES)

describe('the flat text matches the Python contract exactly', () => {
  it('reads a real, non-trivial fixture set', () => {
    // Non-vacuity: an empty or missing fixture file would make every
    // parity case below pass by iterating nothing.
    expect(NAMES.length).toBeGreaterThanOrEqual(9)
    expect(NAMES).toContain('markBoundary')
    expect(NAMES).toContain('duplicatePhrase')
  })

  it.each(NAMES)('%s: whole-doc text is byte-identical to the fixture', (name) => {
    const doc = docOf(name)
    expect(citationText(doc, 0, doc.content.size)).toBe(FIXTURES[name].text)
  })

  it.each(NAMES)('%s: content.size matches the fingerprint component', (name) => {
    // The Python fingerprint is sha256(text)[:16] + ":" + content_size. If
    // content.size disagreed here, a server-issued fingerprint could never be
    // reasoned about on this side.
    expect(docOf(name).content.size).toBe(FIXTURES[name].contentSize)
  })

  it.each(NAMES)('%s: every text span maps back to its ProseMirror range', (name) => {
    const doc = docOf(name)
    const flat = FIXTURES[name].text
    for (const span of FIXTURES[name].textSpans) {
      const start = flat.indexOf(span.text)
      expect(start, `${name}: span text not present in flat text`).toBeGreaterThanOrEqual(0)
      const range = flatToPmRange(doc, start, start + span.text.length)
      expect(range).toEqual({ from: span.pm_start, to: span.pm_end })
    }
  })
})

describe('a citation only navigates when it can be verified', () => {
  it('an unedited note resolves exactly', () => {
    const doc = docOf('twoParas')
    const out = resolveNoteCitation(doc, { from: 14, to: 26 }, 'Second para.')
    expect(out.state).toBe(VALID_EXACT)
    expect(citationText(doc, out.from, out.to)).toBe('Second para.')
  })

  it('a mark added around the passage does not break the citation', () => {
    // ⛔ THE MEASURED CASE. Bolding a phrase splits one text node into three
    // and shifts nothing else — the text at [from,to] is unchanged, so this
    // must stay VALID_EXACT rather than degrade on a cosmetic edit.
    const doc = docOf('markBoundary')
    const flat = FIXTURES.markBoundary.text
    const start = flat.indexOf('gross margins')
    const range = flatToPmRange(doc, start, start + 'gross margins'.length)
    const out = resolveNoteCitation(doc, range, 'gross margins')
    expect(out.state).toBe(VALID_EXACT)
  })

  it('an edit above the passage re-resolves it uniquely', () => {
    const doc = docOf('twoParas')
    // Stale positions: what they pointed at before a paragraph was inserted.
    const out = resolveNoteCitation(doc, { from: 40, to: 52 }, 'Second para.')
    expect(out.state).toBe(RERESOLVED_EXACT)
    expect(citationText(doc, out.from, out.to)).toBe('Second para.')
  })

  it('a duplicated phrase NEVER picks the first occurrence', () => {
    // ⛔ NEVER JUMP TO THE WRONG PASSAGE. A failed precise citation is
    // preferable to a confident mis-navigation.
    const doc = docOf('duplicatePhrase')
    // "Revenue" opens both sentences in this fixture, so a stale position
    // has two candidates and no honest way to choose between them.
    const phrase = 'Revenue'
    expect(FIXTURES.duplicatePhrase.text.split(phrase).length - 1).toBe(2)
    const out = resolveNoteCitation(doc, { from: 9999, to: 10000 }, phrase)
    expect(out.state).toBe(VALID_NOTE_ONLY)
    expect(out.ambiguous).toBe(true)
    expect(out.from).toBeUndefined()
  })

  it('a deleted passage degrades instead of guessing', () => {
    const out = resolveNoteCitation(docOf('twoParas'), { from: 1, to: 5 },
                                    'text that was deleted')
    expect(out.state).toBe(DEGRADED)
    expect(out.from).toBeUndefined()
  })

  it('an out-of-range position never throws', () => {
    const doc = docOf('simple')
    expect(citationText(doc, 0, 99999)).toBe('')
    expect(resolveNoteCitation(doc, { from: -5, to: 99999 }, 'Hello world.').state)
      .toBe(RERESOLVED_EXACT)
  })

  it('a missing doc or snippet degrades rather than throwing', () => {
    expect(resolveNoteCitation(null, { from: 1, to: 2 }, 'x').state).toBe(DEGRADED)
    expect(resolveNoteCitation(docOf('simple'), { from: 1, to: 2 }, '').state).toBe(DEGRADED)
  })
})

describe('handles resolve against the packet, never against punctuation', () => {
  const sources = [{ n: 1, label: 'A' }, { n: 2, label: 'B' }]

  it('a valid handle becomes a citation', () => {
    const parts = splitAnswer('Margins fell [2] sharply.', sources)
    expect(parts.map((p) => p.text)).toEqual(['Margins fell ', '[2]', ' sharply.'])
    expect(parts[1].source.label).toBe('B')
  })

  it('an invented handle stays literal text and is NOT a citation', () => {
    // The model citing a source that was never sent must not look like one.
    const parts = splitAnswer('As stated [9].', sources)
    expect(parts.every((p) => !p.source)).toBe(true)
    expect(parts.map((p) => p.text).join('')).toBe('As stated [9].')
  })

  it('a quoted phrase is NOT a citation any more', () => {
    // ⛔ The Wave 2 contract, deliberately dead: punctuation in model output
    // decided what a citation was.
    const parts = splitAnswer('The note says "margins compressed" here.', sources)
    expect(parts.some((p) => p.source)).toBe(false)
  })

  it('cited sources are listed once, in first-cited order', () => {
    expect(citedSources('[2] then [1] then [2]', sources).map((s) => s.n))
      .toEqual([2, 1])
  })

  it('an answer with no handles round-trips unchanged', () => {
    const text = "I couldn't find that in this note."
    expect(splitAnswer(text, sources).map((p) => p.text).join('')).toBe(text)
  })
})
