import { describe, it, expect } from 'vitest'
import { Schema, Node } from 'prosemirror-model'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  DEGRADED,
  PRECISE_STATES,
  RERESOLVED_EXACT,
  VALID_EXACT,
  VALID_NOTE_ONLY,
  citationAtomIdentity,
  citationText,
  citedSources,
  flatToPmRange,
  isBlockAtomRange,
  resolveNoteCitation,
  splitAnswer,
} from './askCitation'

// ─────────────────────────────────────────────────────────────────────────
// WAVE K SLICE 6 — PARITY, NOT A SECOND AUTHORITY.
//
// Citation resolution now exists twice: in Python
// (note_citation_text.resolve_note_citation, which decides what the server may
// SEND) and here (which decides whether a click may NAVIGATE). Two
// implementations of one rule is the second-authority defect this repo keeps
// paying for, so they are pinned to the SAME ground truth —
// tests/fixtures_pm_citation_text.json, generated by
// tools/gen_pm_citation_fixtures.cjs from real prosemirror-model, and already
// the fixture the Python rails read.
//
// The schema below is copied from that generator on purpose: the fixtures were
// produced under it, so parsing them under anything else would compare this
// code against a doc the ground truth never described. (The generator's copy
// is itself pinned to the editor's real schema by
// askCitation.schemaParity.test.js.)
// ─────────────────────────────────────────────────────────────────────────

const schema = new Schema({
  nodes: {
    doc: { content: 'block+' },
    paragraph: { group: 'block', content: 'inline*', toDOM: () => ['p', 0] },
    heading: { group: 'block', content: 'inline*', attrs: { level: { default: 1 } }, toDOM: () => ['h1', 0] },
    codeBlock: { group: 'block', content: 'text*', marks: '', code: true, toDOM: () => ['pre', ['code', 0]] },
    blockquote: { group: 'block', content: 'block+', toDOM: () => ['blockquote', 0] },
    bulletList: { group: 'block', content: 'listItem+', toDOM: () => ['ul', 0] },
    listItem: { content: 'paragraph block*', toDOM: () => ['li', 0] },
    table: { group: 'block', content: 'tableRow+', toDOM: () => ['table', ['tbody', 0]] },
    tableRow: { content: 'tableCell*', toDOM: () => ['tr', 0] },
    tableCell: { content: 'block+', toDOM: () => ['td', 0] },
    text: { group: 'inline' },
    hardBreak: { group: 'inline', inline: true, selectable: false, toDOM: () => ['br'] },
    noteLink: { group: 'inline', inline: true, atom: true, attrs: { noteId: { default: null } }, toDOM: () => ['span'] },
    attachmentChip: { group: 'block', atom: true, attrs: { href: { default: null }, name: { default: 'file' }, size: { default: null } }, toDOM: () => ['a'] },
    documentExcerpt: { group: 'block', atom: true, attrs: { excerptId: { default: null } }, toDOM: () => ['div'] },
    widgetEmbed: { group: 'block', atom: true, attrs: { widgetId: { default: null }, searchText: { default: null }, capturedAt: { default: null } }, toDOM: () => ['div'] },
    askInsert: { group: 'block', content: 'block+', toDOM: () => ['div', 0] },
    askCitation: { group: 'inline', inline: true, atom: true, attrs: { n: { default: null } }, toDOM: () => ['span'] },
  },
  marks: {
    bold: { toDOM: () => ['strong', 0] },
    italic: { toDOM: () => ['em', 0] },
    link: { attrs: { href: { default: '' } }, toDOM: () => ['a', 0] },
  },
})

const HERE = path.dirname(fileURLToPath(import.meta.url))
const FIXTURES = JSON.parse(fs.readFileSync(
  path.resolve(HERE, '../../../../../tests/fixtures_pm_citation_text.json'), 'utf8'))

const docOf = (name) => Node.fromJSON(schema, FIXTURES[name].json)
const NAMES = Object.keys(FIXTURES)

describe('the flat text matches the Python contract exactly', () => {
  it('reads a real, non-trivial fixture set', () => {
    // Non-vacuity: an empty or missing fixture file would make every
    // parity case below pass by iterating nothing.
    expect(NAMES.length).toBeGreaterThanOrEqual(9)
    expect(NAMES).toContain('markBoundary')
    expect(NAMES).toContain('duplicatePhrase')
  })

  it.each(NAMES)('%s: whole-doc text is byte-identical to the fixture', (name) => {
    const doc = docOf(name)
    expect(citationText(doc, 0, doc.content.size)).toBe(FIXTURES[name].text)
  })

  it.each(NAMES)('%s: content.size matches the fingerprint component', (name) => {
    // The Python fingerprint is sha256(text)[:16] + ":" + content_size. If
    // content.size disagreed here, a server-issued fingerprint could never be
    // reasoned about on this side.
    expect(docOf(name).content.size).toBe(FIXTURES[name].contentSize)
  })

  it.each(NAMES)('%s: every text span maps back to its ProseMirror range', (name) => {
    const doc = docOf(name)
    const flat = FIXTURES[name].text
    for (const span of FIXTURES[name].textSpans) {
      const start = flat.indexOf(span.text)
      expect(start, `${name}: span text not present in flat text`).toBeGreaterThanOrEqual(0)
      const range = flatToPmRange(doc, start, start + span.text.length)
      expect(range).toEqual({ from: span.pm_start, to: span.pm_end })
    }
  })
})

describe('a citation only navigates when it can be verified', () => {
  it('an unedited note resolves exactly', () => {
    const doc = docOf('twoParas')
    const out = resolveNoteCitation(doc, { from: 14, to: 26 }, 'Second para.')
    expect(out.state).toBe(VALID_EXACT)
    expect(citationText(doc, out.from, out.to)).toBe('Second para.')
  })

  it('a mark added around the passage does not break the citation', () => {
    // ⛔ THE MEASURED CASE. Bolding a phrase splits one text node into three
    // and shifts nothing else — the text at [from,to] is unchanged, so this
    // must stay VALID_EXACT rather than degrade on a cosmetic edit.
    const doc = docOf('markBoundary')
    const flat = FIXTURES.markBoundary.text
    const start = flat.indexOf('gross margins')
    const range = flatToPmRange(doc, start, start + 'gross margins'.length)
    const out = resolveNoteCitation(doc, range, 'gross margins')
    expect(out.state).toBe(VALID_EXACT)
  })

  it('an edit above the passage re-resolves it uniquely', () => {
    const doc = docOf('twoParas')
    // Stale positions: what they pointed at before a paragraph was inserted.
    const out = resolveNoteCitation(doc, { from: 40, to: 52 }, 'Second para.')
    expect(out.state).toBe(RERESOLVED_EXACT)
    expect(citationText(doc, out.from, out.to)).toBe('Second para.')
  })

  it('a duplicated phrase NEVER picks the first occurrence', () => {
    // ⛔ NEVER JUMP TO THE WRONG PASSAGE. A failed precise citation is
    // preferable to a confident mis-navigation.
    const doc = docOf('duplicatePhrase')
    // "Revenue" opens both sentences in this fixture, so a stale position
    // has two candidates and no honest way to choose between them.
    const phrase = 'Revenue'
    expect(FIXTURES.duplicatePhrase.text.split(phrase).length - 1).toBe(2)
    const out = resolveNoteCitation(doc, { from: 9999, to: 10000 }, phrase)
    expect(out.state).toBe(VALID_NOTE_ONLY)
    expect(out.ambiguous).toBe(true)
    expect(out.from).toBeUndefined()
  })

  it('a deleted passage degrades instead of guessing', () => {
    const out = resolveNoteCitation(docOf('twoParas'), { from: 1, to: 5 },
                                    'text that was deleted')
    expect(out.state).toBe(DEGRADED)
    expect(out.from).toBeUndefined()
  })

  it('an out-of-range position never throws', () => {
    const doc = docOf('simple')
    expect(citationText(doc, 0, 99999)).toBe('')
    expect(resolveNoteCitation(doc, { from: -5, to: 99999 }, 'Hello world.').state)
      .toBe(RERESOLVED_EXACT)
  })

  it('a missing doc or snippet degrades rather than throwing', () => {
    expect(resolveNoteCitation(null, { from: 1, to: 2 }, 'x').state).toBe(DEGRADED)
    expect(resolveNoteCitation(docOf('simple'), { from: 1, to: 2 }, '').state).toBe(DEGRADED)
  })

  it('a re-resolved single-hit range after an empty paragraph lands EXACTLY (fix round 1, Finding 4)', () => {
    // ⛔ An EMPTY paragraph made textBetween emit an extra separator that
    // flatToPmRange's old look-alike walker did not count, so a re-resolved
    // range landed on the WRONG text. Measured against the doc below, before
    // the verify guard: "Second." re-resolved to pm range {from:12, to:20},
    // and citationText(doc, 12, 20) read "econd.\n". The guard made that
    // decline (VALID_NOTE_ONLY) instead of mis-navigating, and this test used
    // to accept either answer. TIGHTENED (closeout-parity 2026-09-23): the
    // walker now counts separators with textBetween's own predicate, so this
    // must re-resolve exactly, onto exactly the cited text.
    const doc = Node.fromJSON(schema, { type: 'doc', content: [
      { type: 'paragraph', content: [{ type: 'text', text: 'First.' }] },
      { type: 'paragraph' },
      { type: 'paragraph', content: [{ type: 'text', text: 'Second.' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Third.' }] },
    ] })
    const out = resolveNoteCitation(doc, { from: 999, to: 1000 }, 'Second.')
    expect(out.state).toBe(RERESOLVED_EXACT)
    expect(citationText(doc, out.from, out.to)).toBe('Second.')
  })
})

describe('handles resolve against the packet, never against punctuation', () => {
  const sources = [{ n: 1, label: 'A' }, { n: 2, label: 'B' }]

  it('a valid handle becomes a citation', () => {
    const parts = splitAnswer('Margins fell [2] sharply.', sources)
    expect(parts.map((p) => p.text)).toEqual(['Margins fell ', '[2]', ' sharply.'])
    expect(parts[1].source.label).toBe('B')
  })

  it('an invented handle stays literal text and is NOT a citation', () => {
    // The model citing a source that was never sent must not look like one.
    const parts = splitAnswer('As stated [9].', sources)
    expect(parts.every((p) => !p.source)).toBe(true)
    expect(parts.map((p) => p.text).join('')).toBe('As stated [9].')
  })

  it('a quoted phrase is NOT a citation any more', () => {
    // ⛔ The Wave 2 contract, deliberately dead: punctuation in model output
    // decided what a citation was.
    const parts = splitAnswer('The note says "margins compressed" here.', sources)
    expect(parts.some((p) => p.source)).toBe(false)
  })

  it('cited sources are listed once, in first-cited order', () => {
    expect(citedSources('[2] then [1] then [2]', sources).map((s) => s.n))
      .toEqual([2, 1])
  })

  it('an answer with no handles round-trips unchanged', () => {
    const text = "I couldn't find that in this note."
    expect(splitAnswer(text, sources).map((p) => p.text).join('')).toBe(text)
  })
})

// ── Empty textblocks and block atoms (closeout-parity 2026-09-23) ──────────

/** Where a span starts in the flat text, as textBetween itself counts it: the
 * text through the END of the span, minus the span. (Reading up to the START
 * would miss the separator a block leaf emits when textBetween visits it.) */
const flatStartOf = (doc, span) => citationText(doc, 0, span.pm_end).length - span.text.length

describe('the walker IS textBetween (offsets derived, never searched for)', () => {
  it('non-vacuity: the fixtures hold text-reading leaves', () => {
    expect(NAMES.filter((n) => FIXTURES[n].leafSpans?.length).length).toBeGreaterThanOrEqual(8)
  })

  it.each(NAMES)('%s: every text node and every leaf that reads as text maps back exactly', (name) => {
    const doc = docOf(name)
    const flat = citationText(doc, 0, doc.content.size)
    for (const span of [...FIXTURES[name].textSpans, ...FIXTURES[name].leafSpans]) {
      const start = flatStartOf(doc, span)
      expect(flat.slice(start, start + span.text.length), `${name}: offset`).toBe(span.text)
      expect(flatToPmRange(doc, start, start + span.text.length), `${name}: ${span.text}`)
        .toEqual({ from: span.pm_start, to: span.pm_end })
    }
  })
})

describe('re-resolution after an edit above never lands on the wrong text', () => {
  it.each(NAMES)('%s: every passage re-resolves exactly, or declines', (name) => {
    const json = FIXTURES[name].json
    const edited = Node.fromJSON(schema, { ...json, content: [
      { type: 'paragraph', content: [{ type: 'text', text: 'Inserted above.' }] }, ...json.content] })
    const SHIFT = 'Inserted above.'.length + 2
    const full = citationText(edited, 0, edited.content.size)
    for (const span of FIXTURES[name].textSpans) {
      const out = resolveNoteCitation(edited, { from: span.pm_start, to: span.pm_end }, span.text)
      // Whatever it claims, it never claims a range holding different text.
      if (out.from != null) expect(citationText(edited, out.from, out.to).trim()).toBe(span.text.trim())
      // And a passage that occurs exactly once is always found again.
      const unique = full.split(span.text.trim()).length === 2
      if (unique && span.text.trim()) expect([VALID_EXACT, RERESOLVED_EXACT], `${name}: ${span.text}`).toContain(out.state)
    }
    for (const span of FIXTURES[name].leafSpans) {
      const stale = { from: span.pm_start, to: span.pm_end }
      // An atom with an identity is found again by it, exactly where it moved...
      if (span.atom) {
        expect(resolveNoteCitation(edited, { ...stale, atom: span.atom }, span.text), `${name}: ${span.text}`)
          .toEqual({ state: RERESOLVED_EXACT, from: stale.from + SHIFT, to: stale.to + SHIFT })
      }
      // ...and by its placeholder text alone, never: text names no ONE atom.
      expect(PRECISE_STATES.has(resolveNoteCitation(edited, stale, span.text).state), `${name}: ${span.text}`)
        .toBe(false)
    }
  })
})

describe('a block atom is its own line, and is opened by identity', () => {
  it('a block-atom range is selected as a node, an inline or text range is not', () => {
    const doc = docOf('chipMiddle')
    expect(isBlockAtomRange(doc, 9, 10)).toBe(true)
    expect(isBlockAtomRange(doc, 11, 17)).toBe(false)
    // An inline atom (the askCitation chip at 14) is never a block range.
    expect(isBlockAtomRange(docOf('askCitationChip'), 14, 15)).toBe(false)
  })

  it('a chip with no identity opens the note only, even unedited; with one it opens in place', () => {
    const doc = docOf('chipMiddle') // this chip has no href
    expect(resolveNoteCitation(doc, { from: 9, to: 10 }, '[file: q3-filing.pdf]').state).toBe(VALID_NOTE_ONLY)
    const withHref = Node.fromJSON(schema, { type: 'doc', content: [
      FIXTURES.chipMiddle.json.content[0],
      { type: 'attachmentChip', attrs: { name: 'q3-filing.pdf', href: '/files/9f/q3-filing.pdf' } },
      FIXTURES.chipMiddle.json.content[2]] })
    const atom = { type: 'attachmentChip', id: '/files/9f/q3-filing.pdf' }
    expect(resolveNoteCitation(withHref, { from: 9, to: 10, atom }, '[file: q3-filing.pdf]'))
      .toEqual({ state: VALID_EXACT, from: 9, to: 10 })
  })

  it('the paragraph AFTER the chip is its own passage (no longer glued)', () => {
    const doc = docOf('chipMiddle')
    expect(resolveNoteCitation(doc, { from: 11, to: 17 }, 'After.').state).toBe(VALID_EXACT)
    expect(citationText(doc, 0, doc.content.size)).toBe('Before.\n[file: q3-filing.pdf]\nAfter.')
  })

  it('isBlockAtomRange answers false outside the doc instead of throwing (fix round 1, M4)', () => {
    const doc = docOf('chipMiddle')
    const size = doc.content.size
    // Control: the primitive itself throws out there, so the guard is load-bearing.
    expect(() => doc.nodeAt(size + 5)).toThrow(RangeError)
    expect(isBlockAtomRange(doc, -1, 0)).toBe(false)
    expect(isBlockAtomRange(doc, size + 5, size + 6)).toBe(false)
    expect(isBlockAtomRange(doc, null, 10)).toBe(false)
    expect(isBlockAtomRange(doc, 9, 10)).toBe(true)
  })
})

// ── Fix round 2 (rereview-parity, 2026-09-23) ──────────────────────────────

describe('an atom is verified by IDENTITY, never by placeholder text (N1, N2)', () => {
  // Every excerpt reads "[excerpt]", every chip-less widget "[widget]", two
  // chips of one file alike. Round 1 counted placeholder occurrences, which
  // could not see a sibling that was the ONLY remaining occurrence (N1) and
  // refused a unique atom whose placeholder was also typed as text (N2).
  const EX = (excerptId) => ({ type: 'documentExcerpt', attrs: { excerptId } })
  const WIDGET = (capturedAt) => ({ type: 'widgetEmbed', attrs: { widgetId: 'chart', capturedAt } }) // "[widget]"
  const CHIP = (href) => ({ type: 'attachmentChip', attrs: { name: 'q3.pdf', href } })
  const para = (text) => ({ type: 'paragraph', content: [{ type: 'text', text }] })
  const build = (...content) => Node.fromJSON(schema, { type: 'doc', content })
  /** The citation the server issues for an atom: its range plus its identity. */
  const citeAtom = (doc, pred) => {
    let loc = null
    doc.descendants((n, pos) => {
      if (n.isAtom && pred(n)) loc = { from: pos, to: pos + n.nodeSize, atom: { type: n.type.name, id: citationAtomIdentity(n) } }
    })
    return loc
  }
  const byId = (id) => (n) => citationAtomIdentity(n) === id
  const notOpened = (out) => {
    expect(out.state).toBe(VALID_NOTE_ONLY)
    expect(out.from).toBeUndefined()
  }

  it('reviewer case 7: the adjacent twin that slid into place is never selected', () => {
    const before = build(para('Thesis'), EX('ex1'), EX('ex2'), para('After.'))
    const loc = citeAtom(before, byId('ex1'))
    expect(loc).toMatchObject({ from: 8, to: 9 })
    const after = build(para('Thesis'), EX('ex2'), para('After.'))
    expect(citationText(after, 8, 9)).toBe('[excerpt]') // the look-alike, in place
    notOpened(resolveNoteCitation(after, loc, '[excerpt]'))
    notOpened(resolveNoteCitation(after, { from: 8, to: 9 }, '[excerpt]')) // an old packet, no identity
  })

  it('reviewer case 8: a twin across a paragraph is never re-resolved onto', () => {
    const before = build(para('Thesis'), EX('ex1'), para('Between.'), EX('ex2'), para('After.'))
    const loc = citeAtom(before, byId('ex1'))
    const after = build(para('Thesis'), para('Between.'), EX('ex2'), para('After.'))
    // The survivor is now the UNIQUE text hit -- what round 1 jumped to.
    expect(citationText(after, 0, after.content.size).split('[excerpt]').length).toBe(2)
    notOpened(resolveNoteCitation(after, loc, '[excerpt]'))
    notOpened(resolveNoteCitation(after, { from: loc.from, to: loc.to }, '[excerpt]'))
  })

  it('reviewer case 9: the same for a [widget] twin', () => {
    const before = build(para('Thesis'), WIDGET('2026-09-01T14:00:00.000Z'), para('Between.'),
      WIDGET('2026-09-02T14:00:00.000Z'), para('After.'))
    const loc = citeAtom(before, byId('chart|2026-09-01T14:00:00.000Z'))
    const after = build(para('Thesis'), para('Between.'), WIDGET('2026-09-02T14:00:00.000Z'), para('After.'))
    notOpened(resolveNoteCitation(after, loc, '[widget]'))
    notOpened(resolveNoteCitation(after, { from: loc.from, to: loc.to }, '[widget]'))
  })

  it('N2: a unique atom opens exactly even when its placeholder is also ordinary text', () => {
    // Typed "[excerpt]", an inserted answer quoting "[file: q3.pdf]", a
    // widget's searchText in a paragraph: each made round 1 count two.
    const typed = build(para('I typed [excerpt] here.'), EX('ex1'))
    const ex = citeAtom(typed, byId('ex1'))
    expect(resolveNoteCitation(typed, ex, '[excerpt]')).toEqual({ state: VALID_EXACT, from: ex.from, to: ex.to })

    const quoted = build({ type: 'askInsert', content: [para('The filing [file: q3.pdf] says so.')] }, CHIP('/files/9f/q3.pdf'))
    const chip = citeAtom(quoted, byId('/files/9f/q3.pdf'))
    expect(resolveNoteCitation(quoted, chip, '[file: q3.pdf]')).toEqual({ state: VALID_EXACT, from: chip.from, to: chip.to })

    const search = build(para('NVDA daily chart looked heavy.'),
      { type: 'widgetEmbed', attrs: { widgetId: 'chart', searchText: 'NVDA daily chart', capturedAt: '2026-09-01T14:00:00.000Z' } })
    const w = citeAtom(search, (n) => n.type.name === 'widgetEmbed')
    expect(resolveNoteCitation(search, w, 'NVDA daily chart')).toEqual({ state: VALID_EXACT, from: w.from, to: w.to })
  })

  it('a moved atom re-resolves by identity to exactly where it went', () => {
    const before = build(para('Thesis'), EX('ex1'), EX('ex2'), para('After.'))
    const loc = citeAtom(before, byId('ex2'))
    const after = build(para('A new opening.'), para('Thesis'), EX('ex1'), EX('ex2'), para('After.'))
    const out = resolveNoteCitation(after, loc, '[excerpt]')
    expect(out).toEqual({ state: RERESOLVED_EXACT, from: loc.from + 16, to: loc.to + 16 })
    expect(after.nodeAt(out.from).attrs.excerptId).toBe('ex2')
  })

  it('an identity mis-positioned onto its twin is CORRECTED, not refused', () => {
    // The round-1 emoji case: ProseMirror puts ex1 at 16 and ex2 at 17; a
    // range naming ex2 at {16,17} holds ex1. Identity finds the real ex2.
    const doc = build(para('\u{1F680} NVDA thesis'), EX('ex1'), EX('ex2'), para('After.'))
    const out = resolveNoteCitation(doc, { from: 16, to: 17, atom: { type: 'documentExcerpt', id: 'ex2' } }, '[excerpt]')
    expect(out).toEqual({ state: RERESOLVED_EXACT, from: 17, to: 18 })
  })

  it('an identity found twice off position, or under another type, opens the note only', () => {
    const pasted = build(para('Thesis, rewritten.'), EX('ex1'), EX('ex1'))
    const out = resolveNoteCitation(pasted, { from: 8, to: 9, atom: { type: 'documentExcerpt', id: 'ex1' } }, '[excerpt]')
    expect(out).toMatchObject({ state: VALID_NOTE_ONLY, ambiguous: true })
    const doc = build(para('Thesis'), EX('ex1'))
    notOpened(resolveNoteCitation(doc, { from: 8, to: 9, atom: { type: 'attachmentChip', id: 'ex1' } }, '[excerpt]'))
  })

  it('a citation without identity never opens an atom, however unique and unchanged', () => {
    const one = build(para('Thesis'), EX('ex1'), { type: 'paragraph' })
    expect(isBlockAtomRange(one, 8, 9)).toBe(true)
    notOpened(resolveNoteCitation(one, { from: 8, to: 9 }, '[excerpt]'))
    // And a TEXT citation whose only remaining hit is an atom is refused too.
    const typedThenGone = build(para('Thesis'), EX('ex1'))
    notOpened(resolveNoteCitation(typedThenGone, { from: 9, to: 18 }, '[excerpt]'))
  })

  it('citationAtomIdentity: only a non-empty identity attr counts', () => {
    const t = (type, attrs) => citationAtomIdentity(schema.nodes[type].create(attrs))
    expect(t('documentExcerpt', { excerptId: 'ex1' })).toBe('ex1')
    expect(t('documentExcerpt', { excerptId: '' })).toBeNull()
    expect(t('attachmentChip', { href: '/f/a.pdf' })).toBe('/f/a.pdf')
    expect(t('attachmentChip', {})).toBeNull()
    expect(t('widgetEmbed', { widgetId: 'chart', capturedAt: 'T' })).toBe('chart|T')
    expect(t('widgetEmbed', { widgetId: 'chart' })).toBeNull() // the KIND alone names no instance
    expect(citationAtomIdentity(null)).toBeNull()
  })
})

describe('a passage near an astral character maps to ProseMirror\'s range (M3)', () => {
  const PASSAGES = NAMES.flatMap((name) => FIXTURES[name].passages.map((p) => [name, p]))

  it('non-vacuity: the fixtures carry astral text and cited passages', () => {
    expect(PASSAGES.length).toBeGreaterThanOrEqual(15)
    expect(NAMES.filter((n) => /[\u{10000}-\u{10FFFF}]/u.test(FIXTURES[n].text)).length).toBeGreaterThanOrEqual(5)
  })

  it.each(PASSAGES)('%s: %j', (name, p) => {
    const doc = docOf(name)
    const range = { from: p.pm_from, to: p.pm_to }
    expect(citationText(doc, range.from, range.to)).toBe(p.text)
    const full = citationText(doc, 0, doc.content.size)
    const i = full.indexOf(p.text)
    expect(flatToPmRange(doc, i, i + p.text.length)).toEqual(range)
    if (isBlockAtomRange(doc, range.from, range.to)) {
      // An atom passage maps to the atom -- but its text alone never opens
      // it, in place or re-found (fix round 2: identity, never placeholder).
      expect(resolveNoteCitation(doc, range, p.text).state).toBe(VALID_NOTE_ONLY)
      expect(resolveNoteCitation(doc, { from: 9999, to: 10000 }, p.text).state).toBe(VALID_NOTE_ONLY)
      return
    }
    expect(resolveNoteCitation(doc, range, p.text)).toEqual({ state: VALID_EXACT, ...range })
    // From a stale location, it is re-found at exactly the same range.
    expect(resolveNoteCitation(doc, { from: 9999, to: 10000 }, p.text)).toEqual({ state: RERESOLVED_EXACT, ...range })
  })
})
