// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © ceyhun

//@version=5

indicator('ATR Trailing Stop by ceyhun', overlay=true)

/////////notes////////////////////////////////////////
// This is based on the ATR trailing stop indicator //
// width addition of two levels of stops and        //
// different interpretation.                        //
// This is a fast-reacting system and is better     //
// suited for higher volatility markets             //
//////////////////////////////////////////////////////

SC = input(close, 'Source')

// Fast Trail //
AP1 = input(5, 'Fast ATR period')  // ATR Period
AF1 = input(0.5, 'Fast ATR multiplier')  // ATR Factor
SL1 = AF1 * ta.atr(AP1)  // Stop Loss
Trail1 = 0.0
iff_1 = SC > nz(Trail1[1], 0) ? SC - SL1 : SC + SL1
iff_2 = SC < nz(Trail1[1], 0) and SC[1] < nz(Trail1[1], 0) ? math.min(nz(Trail1[1], 0), SC + SL1) : iff_1
Trail1 := SC > nz(Trail1[1], 0) and SC[1] > nz(Trail1[1], 0) ? math.max(nz(Trail1[1], 0), SC - SL1) : iff_2

// Slow Trail //
AP2 = input(10, 'Slow ATR period')  // ATR Period
AF2 = input.float(3, 'Slow ATR multiplier')  // ATR Factor
SL2 = AF2 * ta.atr(AP2)  // Stop Loss
Trail2 = 0.0
iff_3 = SC > nz(Trail2[1], 0) ? SC - SL2 : SC + SL2
iff_4 = SC < nz(Trail2[1], 0) and SC[1] < nz(Trail2[1], 0) ? math.min(nz(Trail2[1], 0), SC + SL2) : iff_3
Trail2 := SC > nz(Trail2[1], 0) and SC[1] > nz(Trail2[1], 0) ? math.max(nz(Trail2[1], 0), SC - SL2) : iff_4

// Bar color for trade signal //
Green = Trail1 > Trail2 and close > Trail2 and low > Trail2
Blue = Trail1 > Trail2 and close > Trail2 and low < Trail2
Red = Trail2 > Trail1 and close < Trail2 and high < Trail2
Yellow = Trail2 > Trail1 and close < Trail2 and high > Trail2

// Signals //
Bull = ta.barssince(Green) < ta.barssince(Red)
Bear = ta.barssince(Red) < ta.barssince(Green)

Buy = ta.crossover(Trail1, Trail2)
Sell = ta.crossunder(Trail1, Trail2)
iff_5 = Trail2 > Trail1 ? -1 : 0
SR = Trail1 > Trail2 ? 1 : iff_5

TS1 = plot(Trail1, 'Fast Trail', style=plot.style_line, color=Trail1 > Trail2 ? color.blue : color.yellow, linewidth=2, display=display.none)
TS2 = plot(Trail2, 'Slow Trail', style=plot.style_line, color=Trail1 > Trail2 ? color.green : color.red, linewidth=2)
fill(TS1, TS2, Bull ? color.new(color.green, 90) : color.new(color.red, 90))

plotcolor = input(true, 'Paint color on chart')
plotbuysell = input(true, 'Plot Buy/Sell arrows')

bcl = plotcolor == 1 ? Blue ? color.blue : Green ? color.lime : Yellow ? color.yellow : Red ? color.red : color.white : na
barcolor(bcl)
plotshape(Buy and plotbuysell == 1, 'BUY', shape.labelup, location.belowbar, color.new(color.green, 0), text='BUY', textcolor=color.new(color.black, 0))
plotshape(Sell and plotbuysell == 1, 'SELL', shape.labeldown, location.abovebar, color.new(color.red, 0), text='SELL', textcolor=color.new(color.black, 0))

alertcondition(Buy, 'Buy Signal', 'Buy ATR Trailing Stop')
alertcondition(Sell, 'Sell Signal', 'Sell ATR Trailing Stop')

//==================================================
//InfoPanel
// Rounding levels to min tick
nround(x) =>
    n = math.round(x / syminfo.mintick) * syminfo.mintick
    n

// ———————————————————— Function used to round values.
RoundToTick(_price) =>
    math.round(_price / syminfo.mintick) * syminfo.mintick

Round(_val, _decimals) =>
    // Rounds _val to _decimals places.
    _p = math.pow(10, _decimals)
    math.round(math.abs(_val) * _p) / _p * math.sign(_val)

//
position = input(50)
h = ta.highest(position)
info_label_off = input(50, title='Info panel offset')
info_label_size = input.string(size.large, options=[size.tiny, size.small, size.normal, size.large, size.huge], title='Info panel label size')
info_panel_x = timenow + math.round(ta.change(time) * info_label_off)
info_panel_y = h
info_current_close = '\n\nCurrent Close : ' + str.tostring(close)

disp_panels1 = input(true, title='Buy info panels?')
disp_panels2 = input(true, title='Sell info panels?')

Long = '-=-=-Buy-=-=-   '
Short = '-=-=-Sell-=-=-   '

pp1 = '\nNumber of Candles : ' + str.tostring(ta.barssince(Buy), '##.##')
pp2 = '\nNumber of Candles : ' + str.tostring(ta.barssince(Sell), '##.##')

Buyprice = '\nBuy Price  : ' + str.tostring(ta.valuewhen(Buy, SC, 0), '##.##') + ''
ProfitLong = '\nProfit : ' + '(' + str.tostring(100 * ((SC - ta.valuewhen(Buy, SC, 0)) / ta.valuewhen(Buy, SC, 0)), '##.##') + '%' + ')'
Buydistance = '\nSupport Distance  : ' + '(' + str.tostring(100 * ((close - Trail2) / Trail2), '##.##') + '%' + ')'

Sellprice = '\nSell Price  : ' + str.tostring(ta.valuewhen(Sell, SC, 0), '##.##') + ''
ProfitShort = '\nProfit : ' + '(' + str.tostring(100 * ((ta.valuewhen(Sell, SC, 0) - SC) / ta.valuewhen(Sell, SC, 0)), '##.##') + '%' + ')'
Selldistance = '\nResistance Distance  : ' + '(' + str.tostring(100 * ((close - Trail2) / Trail2), '##.##') + '%' + ')'

info_textlongbuy = Long + info_current_close + pp1 + Buyprice + ProfitLong + Buydistance
info_textlongsell = Short + info_current_close + pp2 + Sellprice + ProfitShort + Selldistance
info_panellongbuy = SR == 1 and disp_panels1 ? label.new(x=info_panel_x, y=info_panel_y, text=info_textlongbuy, xloc=xloc.bar_time, yloc=yloc.price, color=color.green, style=label.style_label_up, textcolor=color.black, size=info_label_size) : na
info_panellongsell = SR == -1 and disp_panels2 ? label.new(x=info_panel_x, y=info_panel_y, text=info_textlongsell, xloc=xloc.bar_time, yloc=yloc.price, color=color.red, style=label.style_label_up, textcolor=color.black, size=info_label_size) : na
label.delete(info_panellongbuy[1])
label.delete(info_panellongsell[1])

