// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Hampeh

//Indicator
//
//The Bollinger Band Breakout strategy involves entering a trade when the price breaks through the upper or lower bands, signaling a potential continuation of the current trend. 
//Traders can establish long positions when the price breaks above the upper band and short positions when it breaks below the lower band.
//
//An “inside bar” pattern is a two-bar price action trading strategy in which the inside bar is smaller and within the high to low range of the prior bar, 
//i.e. the high is lower than the previous bar's high, and the low is higher than the previous bar's low.


//@version=5
indicator('Bolingger Bands + Inside Bar Boxes', shorttitle='BB + IB Boxes', overlay=true)

//General

EnableBB = input.string("Yes", title="Enable Bollinger Bands", options=["Yes", "No"], group = "GENERAL SETTING")
EnableIB = input.string("Yes", title="Enable Inside Bars", options=["Yes", "No"], group = "GENERAL SETTING")

DisplayBB = EnableBB == "Yes" ? true : false
DisplayIB = EnableIB == "Yes" ? true : false

//BOLLINGER BANDS

length = input.int(20, minval=1, group = "BOLLINGER BANDS SETTING")
maType = input.string("SMA", "Basis MA Type", options = ["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"], group = "BOLLINGER BANDS SETTING")
src = input(close, title="Source", group = "BOLLINGER BANDS SETTING")
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev", group = "BOLLINGER BANDS SETTING")

ma(source, length, _type) =>
    switch _type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA (RMA)" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)

basis = ma(src, length, maType)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev
offset = input.int(0, "Offset", minval = -500, maxval = 500, group = "BOLLINGER BANDS SETTING")

ShowBB = DisplayBB == true ? display.all : display.none

plot(basis, "Basis", color=#FF6D00, offset = offset, display = ShowBB)
p1 = plot(upper, "Upper", color=#2962FF, offset = offset, display = ShowBB)
p2 = plot(lower, "Lower", color=#2962FF, offset = offset, display = ShowBB)

fill(p1, p2, title = "Background", color=color.rgb(33, 149, 243, 95), display = ShowBB)


// INSIDE BAR
//inputs

//Body or highLow
IBRange = input.string("Body", title="Body or High Low Range", options=["Body", "HighLow"], group = "INSIDE BARS SETTING")

// buffer zone around high-low
highLowBuffer = input(0, 'High-Low buffer zone', group = "INSIDE BARS SETTING")

// bars highlight
barHighlight = input(false, 'Highlight bars in boxes', group = "INSIDE BARS SETTING")
// Show all or only last box
showOnlyLastBox = input(false, 'Show only last Box', group = "INSIDE BARS SETTING")
// show breaks
showBreak = input(true, 'Show boxes break', group = "INSIDE BARS SETTING")

// Box background color and transparency
bgTransparency = input(90, 'Box transparency', group = "INSIDE BARS SETTING")
bgColor = input(color.rgb(33, 243, 79), 'Background color', group = "INSIDE BARS SETTING")
// color for insibe bars if barHighlight is true
insideBarsColor = input(color.orange, 'Inside bars body color', group = "INSIDE BARS SETTING")


// variables
var box myBox = na

var float boxBodyHigh = na
var float boxBodyLow = na

if open >= close
    boxBodyHigh := open
else
    boxBodyHigh := close

if open >= close
    boxBodyLow := close
else
    boxBodyLow := open


var float boxH = na
var float boxL = na

varip int barIndex = 1
varip bool IBStatus = false

// check IB
isInsideBar(previousBar, IBRange) =>

    isIB = false
    if IBRange == "HighLow"
        hp = high[previousBar] + highLowBuffer * syminfo.mintick
        lp = low[previousBar] + highLowBuffer * syminfo.mintick

        isIB := close <= hp and close >= lp and open <= hp and open >= lp

    if IBRange == "Body"
        hp = boxBodyHigh[previousBar] + highLowBuffer * syminfo.mintick
        lp = boxBodyLow[previousBar] + highLowBuffer * syminfo.mintick

        isIB := close <= hp and close >= lp and open <= hp and open >= lp

    isIB

isIB = isInsideBar(barIndex, IBRange)

isBarHighlight = isIB and barHighlight

barcolor(isBarHighlight ? insideBarsColor : na)

if isIB and not isIB[1] and barstate.isconfirmed and DisplayIB

    if IBRange == "Body"
        boxH := boxBodyHigh[1]
        boxL := boxBodyLow[1]
        IBStatus := true

    if IBRange == "HighLow"
        boxH := high[1]
        boxL := low[1]
        IBStatus := true

    if showOnlyLastBox
        box.delete(id=myBox[1])

    if IBRange == "HighLow"
        myBox := box.new(bar_index - 1, high[1], bar_index, low[1], border_color = color(bgColor), bgcolor=color.new(bgColor, bgTransparency))
        barIndex += 1
        barIndex

    if IBRange == "Body"
        myBox := box.new(bar_index - 1, boxBodyHigh[1], bar_index, boxBodyLow[1], border_color = color(bgColor), bgcolor=color.new(bgColor, bgTransparency))
        barIndex += 1
        barIndex

else if isIB and isIB[1] and barstate.isconfirmed
    box.set_right(myBox[1], bar_index)
    barIndex += 1
    barIndex

else if isIB[1] and not isIB and barstate.isconfirmed
    box.set_right(myBox[1], bar_index)
    barIndex := 1
    barIndex

else if not isIB[1] and not isIB
    IBStatus := false
    IBStatus


plotshape(showBreak and IBStatus and ta.crossover(close, boxH) and DisplayIB, color=color.new(color.green, 0), location=location.belowbar, style=shape.triangleup)
plotshape(showBreak and IBStatus and ta.crossunder(close, boxL) and DisplayIB, color=color.new(color.red, 0), location=location.abovebar, style=shape.triangledown)

