// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © TFlab
//@version=6
indicator("Linear Regression Channel [TradingFinder] Existing Trend Lines", overlay = true, max_bars_back = 5000)
TF_Choise = input.bool(false, 'Time Frame', inline = 'TF')
TF = input.timeframe('60', '', inline = 'TF')
n = input.int(100, 'Data Window Period')
RT = input.string('Standard', 'Regression Type', ['Standard', 'Advance'])
ST = input.string('Standard Deviation', 'Scaling Type', ['Standard Deviation', 'ATR'])
Lvl_1 = input.int(1 , 'Scaling Coefficient Level 1')
Lvl_2 = input.int(2 , 'Scaling Coefficient Level 2')
ExtenD = input.string('Extend None', 'Extend Channel', ['Extend None' , 'Extend Left', 'Extend Right', 'Extend Both'])
extend = switch ExtenD
    'Extend None' => extend.none
    'Extend Left'=> extend.left
    'Extend Right'=> extend.right
    'Extend Both' => extend.both

Linear_Regression(Y_Source, X_Source, k) =>
    STDEV = ta.stdev(Y_Source, k)
    ATR   = ta.atr(k)
    X_X0  = X_Source - k 
    X_X1  = X_Source
    T_X0  = time[k]
    T_X1  = time[0]
    Y_AVG = math.sum(Y_Source, k) / k
    X_AVG = math.sum(X_Source, k) / k 
    B1 = ((math.sum(((Y_AVG - Y_Source) * (X_AVG - X_X1)), k))) / (math.sum(math.pow((X_AVG - X_X1), 2) , k) )
    B0 = Y_AVG - (X_AVG * B1) 
    Y_Adv_X0 = (B1 * X_X0) + B0     
    Y_Adv_X1 = (B1 * X_X1) + B0 
    Y_Std_X0 = ta.linreg(Y_Source, k, k)    
    Y_Std_X1 = ta.linreg(Y_Source, k, 0)    
    [Y_Adv_X0, Y_Adv_X1, Y_Std_X0, Y_Std_X1, T_X0, T_X1, STDEV, ATR]    

[Y_Adv_X0, Y_Adv_X1, Y_Std_X0, Y_Std_X1, T_X0, T_X1, STDEV, ATR] = request.security(syminfo.tickerid, timeframe = TF_Choise == false ? timeframe.period : TF,expression =  Linear_Regression(close, bar_index, n)) 

ChannelDrawing(Y_Adv_X0, Y_Adv_X1, Y_Std_X0, Y_Std_X1, T_X0, T_X1, STDEV, ATR, RT, ST, C_1, C_2, Extend, Border_Color, Color_LvL_T, Color_LvL_B) => //Regression Type, Scaling Type, Coefficient
    var line RL         = na 
    var line RL_T1      = na
    var line RL_T2      = na
    var line RL_B1      = na
    var line RL_B2      = na 
    var linefill Fill_1 = na
    var linefill Fill_2 = na 
    X_0 = T_X0
    X_1 = T_X1
    Y_0 = RT == 'Advance' ? Y_Adv_X0 : Y_Std_X0
    Y_1 = RT == 'Advance' ? Y_Adv_X1 : Y_Std_X1
    Scaling = ST == 'ATR' ? ATR : STDEV
    Level_1 = Scaling * C_1
    Level_2 = Scaling * C_2
    RL     := line.new(X_0, Y_0           , X_1, Y_1           , color = Border_Color, extend =  Extend, xloc = xloc.bar_time, style = line.style_solid )
    RL_T1  := line.new(X_0, Y_0 + Level_1 , X_1, Y_1 + Level_1 , color = Border_Color, extend =  Extend, xloc = xloc.bar_time, style = line.style_dashed)  
    RL_T2  := line.new(X_0, Y_0 + Level_2 , X_1, Y_1 + Level_2 , color = Border_Color, extend =  Extend, xloc = xloc.bar_time, style = line.style_solid )  
    RL_B1  := line.new(X_0, Y_0 - Level_1 , X_1, Y_1 - Level_1 , color = Border_Color, extend =  Extend, xloc = xloc.bar_time, style = line.style_dashed)  
    RL_B2  := line.new(X_0, Y_0 - Level_2 , X_1, Y_1 - Level_2 , color = Border_Color, extend =  Extend, xloc = xloc.bar_time, style = line.style_solid )  
    Fill_1 := linefill.new(RL, RL_T2 , Color_LvL_T)
    Fill_2 := linefill.new(RL, RL_B2 , Color_LvL_B)
    line.delete(RL[1])
    line.delete(RL_T1[1])
    line.delete(RL_T2[1])
    line.delete(RL_B1[1])
    line.delete(RL_B2[1])
    linefill.delete(Fill_1[1])
    linefill.delete(Fill_2[1])

ChannelDrawing(Y_Adv_X0, Y_Adv_X1, Y_Std_X0, Y_Std_X1, T_X0, T_X1, STDEV, ATR, RT, ST, Lvl_1, Lvl_2, extend, color.black, #4caf4f45, #ff52522c)

