/**
 * Print-friendly report page. Opens in a new tab via the Generate
 * Report modal. Single-column, serif-friendly, hides all chrome when
 * printed. User hits Ctrl/Cmd+P.
 */

import { useMemo } from 'react'
import { useSearchParams } from 'react-router-dom'
import useSWR from 'swr'
import useJ2Accounts from '../hooks/useJ2Accounts'
import {
  fmtSignedDollar,
  fmtSignedPct,
} from '../lib/calendar'
import { money } from '../../../lib/journal-2-0'
import styles from './ReportPage.module.css'

const fetcher = (url) =>
  fetch(url, { credentials: 'include' }).then((r) => {
    if (!r.ok) throw new Error(`${r.status}`)
    return r.json()
  })

const PERIOD_LABELS = {
  week: 'This Week',
  month: 'This Month',
  'last-month': 'Last Month',
  ytd: 'Year to Date',
  all: 'All Time',
}

export default function ReportPage() {
  const [searchParams] = useSearchParams()
  const from = searchParams.get('from')
  const to = searchParams.get('to')
  const period = searchParams.get('period') || 'month'
  const accountId = searchParams.get('account_id')
  const sections = (searchParams.get('sections') || '').split(',').filter(Boolean)
  const show = (key) => sections.includes(key)

  // Build analytics URL
  const analyticsParams = new URLSearchParams()
  if (accountId) analyticsParams.set('account_id', accountId)
  if (from) analyticsParams.set('date_from', from)
  if (to) analyticsParams.set('date_to', to)
  const analyticsUrl = `/api/j2/analytics?${analyticsParams.toString()}`
  const { data: analytics } = useSWR(analyticsUrl, fetcher)

  // Trades URL
  const tradesParams = new URLSearchParams()
  if (accountId) tradesParams.set('account_id', accountId)
  const tradesUrl = `/api/j2/trades?${tradesParams.toString()}`
  const { data: tradesData } = useSWR(
    show('trades') ? tradesUrl : null, fetcher,
  )

  const { accounts } = useJ2Accounts()
  const accountName = accountId
    ? accounts.find((a) => a.id === accountId)?.name ?? '—'
    : 'All Accounts'

  const filteredTrades = useMemo(() => {
    if (!tradesData?.trades) return []
    let arr = tradesData.trades
    if (from) arr = arr.filter((t) => t.exitDate.slice(0, 10) >= from)
    if (to) arr = arr.filter((t) => t.exitDate.slice(0, 10) <= to)
    return arr.sort((a, b) => a.exitDate.localeCompare(b.exitDate))
  }, [tradesData, from, to])

  if (!analytics) {
    return <div className={styles.loading}>Preparing report…</div>
  }

  return (
    <div className={styles.wrap}>
      <div className={styles.noPrint}>
        <button type="button" className={styles.printBtn} onClick={() => window.print()}>
          🖨 Print / Save as PDF
        </button>
        <button type="button" className={styles.closeBtn} onClick={() => window.close()}>
          Close
        </button>
      </div>

      <header className={styles.header}>
        <h1 className={styles.title}>Trading Report</h1>
        <div className={styles.meta}>
          <span><strong>Account:</strong> {accountName}</span>
          <span><strong>Period:</strong> {PERIOD_LABELS[period] || period}</span>
          {from && to && (
            <span><strong>Range:</strong> {from} → {to}</span>
          )}
          <span><strong>Generated:</strong> {new Date().toLocaleString()}</span>
        </div>
      </header>

      {analytics.tradeCount === 0 ? (
        <p className={styles.empty}>No trades in this period.</p>
      ) : (
        <>
          {show('summary') && <SummarySection analytics={analytics} />}
          {show('equity') && <EquitySection equity={analytics.equity} />}
          {show('daily') && <DailySection performance={analytics.performance} />}
          {show('dow') && <DowSection performance={analytics.performance} />}
          {show('hourly') && <HourlySection performance={analytics.performance} />}
          {show('bySetup') && <BySetupSection attribution={analytics.attribution} />}
          {show('bySymbol') && <BySymbolSection attribution={analytics.attribution} />}
          {show('trades') && <TradesSection trades={filteredTrades} />}
        </>
      )}

      <footer className={styles.footer}>
        Generated by UCT Journal 2.0 · {new Date().getFullYear()}
      </footer>
    </div>
  )
}

function SummarySection({ analytics }) {
  const longShort = analytics.distribution?.longVsShort
  const totalPnl = (longShort?.long?.totalPnl ?? 0) + (longShort?.short?.totalPnl ?? 0)
  const totalTrades = analytics.tradeCount
  const lWins = Math.round((longShort?.long?.winRate ?? 0) * (longShort?.long?.tradeCount ?? 0))
  const sWins = Math.round((longShort?.short?.winRate ?? 0) * (longShort?.short?.tradeCount ?? 0))
  const totalWins = lWins + sWins
  const winRate = totalTrades > 0 ? totalWins / totalTrades : 0
  return (
    <section className={styles.section}>
      <h2>Summary</h2>
      <div className={styles.statGrid}>
        <Stat label="Net P&L" value={fmtSignedDollar(totalPnl)} positive={totalPnl > 0} negative={totalPnl < 0} />
        <Stat label="Total Trades" value={totalTrades} />
        <Stat label="Win Rate" value={`${(winRate * 100).toFixed(1)}%`} />
        <Stat label="Peak P&L" value={fmtSignedDollar(analytics.equity.kpis.peakPnl)} positive />
        <Stat label="Max Drawdown" value={fmtSignedDollar(analytics.equity.kpis.maxDrawdown)} negative />
        <Stat label="Max DD %" value={fmtSignedPct(analytics.equity.kpis.maxDrawdownPct, 2)} negative />
      </div>
      {analytics.edgeScore?.score != null && (
        <p className={styles.edge}>
          <strong>Edge Score:</strong> {analytics.edgeScore.score.toFixed(3)}
          &nbsp;(Win {(analytics.edgeScore.components.winRate * 100).toFixed(0)}%
          × PF {analytics.edgeScore.components.profitFactor.toFixed(2)}
          × R-Consistency {(analytics.edgeScore.components.rConsistency * 100).toFixed(0)}%)
        </p>
      )}
    </section>
  )
}

function EquitySection({ equity }) {
  return (
    <section className={styles.section}>
      <h2>Equity Curve</h2>
      <table className={styles.table}>
        <thead>
          <tr><th>Date</th><th className={styles.right}>Equity</th><th className={styles.right}>Drawdown</th></tr>
        </thead>
        <tbody>
          {equity.curve.map((p) => (
            <tr key={p.date}>
              <td>{p.date}</td>
              <td className={styles.right}>{money(p.equity)}</td>
              <td className={`${styles.right} ${p.drawdown < 0 ? styles.neg : ''}`}>
                {fmtSignedDollar(p.drawdown)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  )
}

function DailySection({ performance }) {
  return (
    <section className={styles.section}>
      <h2>Daily P&L</h2>
      <table className={styles.table}>
        <thead><tr><th>Date</th><th className={styles.right}>P&L</th></tr></thead>
        <tbody>
          {performance.byDay.map((d) => (
            <tr key={d.date}>
              <td>{d.date}</td>
              <td className={`${styles.right} ${d.pnl > 0 ? styles.pos : d.pnl < 0 ? styles.neg : ''}`}>
                {fmtSignedDollar(d.pnl)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  )
}

function DowSection({ performance }) {
  return (
    <section className={styles.section}>
      <h2>Day of Week</h2>
      <table className={styles.table}>
        <thead><tr><th>Day</th><th className={styles.right}>Trades</th><th className={styles.right}>P&L</th></tr></thead>
        <tbody>
          {performance.dayOfWeek.map((d) => (
            <tr key={d.day}>
              <td>{d.day}</td>
              <td className={styles.right}>{d.tradeCount}</td>
              <td className={`${styles.right} ${d.pnl > 0 ? styles.pos : d.pnl < 0 ? styles.neg : ''}`}>
                {fmtSignedDollar(d.pnl)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  )
}

function HourlySection({ performance }) {
  const filtered = performance.hourly.filter((h) => h.tradeCount > 0)
  if (filtered.length === 0) return null
  return (
    <section className={styles.section}>
      <h2>Hourly Performance (ET)</h2>
      <table className={styles.table}>
        <thead><tr><th>Hour</th><th className={styles.right}>Trades</th><th className={styles.right}>P&L</th></tr></thead>
        <tbody>
          {filtered.map((h) => (
            <tr key={h.hour}>
              <td>{h.hour}:00</td>
              <td className={styles.right}>{h.tradeCount}</td>
              <td className={`${styles.right} ${h.pnl > 0 ? styles.pos : h.pnl < 0 ? styles.neg : ''}`}>
                {fmtSignedDollar(h.pnl)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  )
}

function BySetupSection({ attribution }) {
  if (!attribution.bySetup?.length) return null
  return (
    <section className={styles.section}>
      <h2>By Setup</h2>
      <table className={styles.table}>
        <thead>
          <tr>
            <th>Setup</th>
            <th className={styles.right}>Trades</th>
            <th className={styles.right}>Win Rate</th>
            <th className={styles.right}>Avg R</th>
            <th className={styles.right}>P&L</th>
          </tr>
        </thead>
        <tbody>
          {attribution.bySetup.map((s) => (
            <tr key={s.setup}>
              <td>{s.setup}</td>
              <td className={styles.right}>{s.tradeCount}</td>
              <td className={styles.right}>{s.winRate != null ? `${(s.winRate * 100).toFixed(0)}%` : '—'}</td>
              <td className={styles.right}>{s.avgR != null ? `${s.avgR.toFixed(2)}R` : '—'}</td>
              <td className={`${styles.right} ${s.totalPnl > 0 ? styles.pos : styles.neg}`}>
                {fmtSignedDollar(s.totalPnl)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  )
}

function BySymbolSection({ attribution }) {
  if (!attribution.bySymbol?.length) return null
  return (
    <section className={styles.section}>
      <h2>By Symbol</h2>
      <table className={styles.table}>
        <thead>
          <tr>
            <th>Symbol</th>
            <th className={styles.right}>Trades</th>
            <th className={styles.right}>Win Rate</th>
            <th className={styles.right}>Avg P&L</th>
            <th className={styles.right}>P&L</th>
          </tr>
        </thead>
        <tbody>
          {attribution.bySymbol.map((s) => (
            <tr key={s.symbol}>
              <td>{s.symbol}</td>
              <td className={styles.right}>{s.tradeCount}</td>
              <td className={styles.right}>{s.winRate != null ? `${(s.winRate * 100).toFixed(0)}%` : '—'}</td>
              <td className={styles.right}>{s.avgPnl != null ? fmtSignedDollar(s.avgPnl) : '—'}</td>
              <td className={`${styles.right} ${s.totalPnl > 0 ? styles.pos : styles.neg}`}>
                {fmtSignedDollar(s.totalPnl)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  )
}

function TradesSection({ trades }) {
  if (!trades.length) return null
  return (
    <section className={styles.section}>
      <h2>Trade Log ({trades.length})</h2>
      <table className={styles.table}>
        <thead>
          <tr>
            <th>Date</th>
            <th>Symbol</th>
            <th>Side</th>
            <th className={styles.right}>Shares</th>
            <th className={styles.right}>Entry</th>
            <th className={styles.right}>Exit</th>
            <th>Setup</th>
            <th className={styles.right}>R</th>
            <th className={styles.right}>P&L</th>
            <th>Result</th>
          </tr>
        </thead>
        <tbody>
          {trades.map((t) => (
            <tr key={t.id}>
              <td>{t.exitDate.slice(0, 10)}</td>
              <td>{t.symbol}</td>
              <td>{t.side}</td>
              <td className={styles.right}>{t.shares}</td>
              <td className={styles.right}>${t.entryPrice.toFixed(2)}</td>
              <td className={styles.right}>${t.exitPrice.toFixed(2)}</td>
              <td>{t.setup || '—'}</td>
              <td className={styles.right}>{t.rMultiple != null ? `${t.rMultiple.toFixed(2)}R` : '—'}</td>
              <td className={`${styles.right} ${t.pnlDollar > 0 ? styles.pos : t.pnlDollar < 0 ? styles.neg : ''}`}>
                {fmtSignedDollar(t.pnlDollar)}
              </td>
              <td>{t.result}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  )
}

function Stat({ label, value, positive, negative }) {
  return (
    <div className={styles.stat}>
      <div className={styles.statLabel}>{label}</div>
      <div className={`${styles.statValue} ${positive ? styles.pos : ''} ${negative ? styles.neg : ''}`}>
        {value}
      </div>
    </div>
  )
}
