import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { renderHook } from '@testing-library/react'

// Mock useMobileSWR to capture the URLs requested and return canned data.
// Each entry is the honest { ok, httpStatus, body } shape the real fetcher
// now returns (TERM-088) -- never a bare value. `mutate` refs are module-level
// (stable per key) to mirror real SWR's guarantee.
const calls = []
const noop1 = () => {}
const noop2 = () => {}
const noop3 = () => {}
const noop4 = () => {}
vi.mock('../../../hooks/useMobileSWR', () => ({
  default: (url) => {
    calls.push(url)
    if (url?.includes('/api/ticker-meta/')) return { data: { ok: true, httpStatus: 200, body: { name: 'Apple Inc.', sector: 'Technology', industry: 'Consumer Electronics' } }, mutate: noop1 }
    if (url?.includes('/api/fundamentals/')) return { data: { ok: true, httpStatus: 200, body: { market_cap: '$2.95T', forward_pe: 28.5, beta: 1.22, week52_high: 243, week52_low: 164, div_yield: 0.42 } }, mutate: noop2 }
    if (url?.includes('/api/earnings/intel/')) return { data: { ok: true, httpStatus: 200, body: { consensus: { buy: 37, hold: 8, sell: 1 }, price_target: { targetLow: 230, targetMean: 251, targetHigh: 280 } } }, mutate: noop3 }
    return { data: undefined, mutate: noop4 }
  },
}))
vi.mock('../../../hooks/useLivePrices', () => ({ default: () => ({ prices: { AAPL: { price: 256.5, change_pct: 1.8 } } }) }))

import useResearchOverview from './useResearchOverview'

describe('useResearchOverview', () => {
  beforeEach(() => { calls.length = 0 })

  it('requests the composing endpoints for the upper-cased symbol', () => {
    renderHook(() => useResearchOverview('aapl'))
    expect(calls).toContain('/api/ticker-meta/AAPL?src=research')
    expect(calls).toContain('/api/fundamentals/AAPL')
    expect(calls).toContain('/api/earnings/intel/AAPL')
  })

  it('returns a normalized shape with meta, stats, analyst, live', () => {
    const { result } = renderHook(() => useResearchOverview('AAPL'))
    expect(result.current.meta.name).toBe('Apple Inc.')
    expect(result.current.stats.forward_pe).toBe(28.5)
    expect(result.current.analyst.consensus.buy).toBe(37)
    expect(result.current.live.change_pct).toBe(1.8)
    expect(result.current.error).toBe(false)
  })

  // The analysis is generated by an LLM when uncached; the read must never
  // trigger that on the request path.
  it('reads the earnings analysis cached-only', () => {
    renderHook(() => useResearchOverview('AAPL'))
    expect(calls).toContain('/api/earnings-analysis/AAPL?cached_only=1')
    expect(calls).not.toContain('/api/earnings-analysis/AAPL')
  })

  it('header:false (the terminal DES panel) skips the meta read and the live price', () => {
    const { result } = renderHook(() => useResearchOverview('AAPL', { header: false }))
    expect(calls.some((u) => u && u.includes('/api/ticker-meta/'))).toBe(false)
    expect(calls).toContain('/api/fundamentals/AAPL')
    expect(result.current.live).toEqual({})
    expect(result.current.meta).toEqual({})
  })
})

// TERM-088 -- `fetchResearchOverviewPart` honesty + error/H14 coverage for the
// composed hook live in useResearchOverview.errorAndHonesty.test.js. A file
// with its own static `vi.mock` of the same module (above) cannot reliably
// have that mock overridden per-test by `vi.doMock` + dynamic import, so
// that coverage is isolated in a sibling file with no competing static mock
// -- the same pattern useDecisionRecord.test.js and the other research hooks
// use.
