// app/src/components/chart/engine/ast/formulaDocs.js
//
// ─── 📖 THE MEMBER'S REFERENCE, DERIVED FROM THE MANIFEST ────────────────────
//
// Segment G6 asks for "the grammar, the functions with their sentences
// (generated from the manifest, never hand-listed), what imports and what does
// not, and why", and says why: ⛔ "Generate from `closedTable.json` so it cannot
// go stale."
//
// ⭐ THE SENTENCES ARE ALREADY WRITTEN AND ALREADY SHIPPED. Every function,
// scalar and clock entry carries the `sentence` the READ-BACK renders to a
// member inside the builder — so a generated reference is not new prose, it is
// the same prose in one place. A hand-written page would be a SECOND authority
// over what `rsi` means, and it would drift the first time an entry moved.
//
// ⚠️ WHAT THIS FILE DOES NOT INVENT: `series` and `operators` carry no
// `sentence` in the manifest (measured: 0 of 5 and 0 of 15). They are rendered
// from what they DO carry — the bar field, the arity, the yield — rather than
// given prose written here, because prose written here is exactly the second
// authority the paragraph above rules out.

import TABLE from './closedTable.json'

const YIELD_ENGLISH = Object.freeze({
  num: 'a number',
  bool: 'true or false',
})

/** `lookback: "arg1"` → "as many bars as argument 1 asks for". */
function lookbackText(spec) {
  const lb = spec && spec.lookback
  if (lb === undefined || lb === null) return 'none'
  if (typeof lb === 'number') return `${lb} bar${lb === 1 ? '' : 's'}`
  const m = /^arg(\d+)$/.exec(String(lb))
  if (m) {
    const role = spec.argRoles && spec.argRoles[Number(m[1])]
    return role ? `whatever \`${role}\` asks for` : `whatever argument ${m[1]} asks for`
  }
  if (lb === 'session') return `a session (${TABLE.sessionMaxBars} bars)`
  return String(lb)
}

/** `rsi(source, period)` — the signature a member types, from the roles. */
function signature(name, spec) {
  const roles = (spec.argRoles && spec.argRoles.length)
    ? spec.argRoles
    : (spec.args || []).map((a, i) => `${a}${i + 1}`)
  return `${name}(${roles.join(', ')})`
}

/** A read-back template with its `{0}` slots filled by the ARGUMENT ROLES.
 *
 *  ⛔ THE SENTENCES ARE WRITTEN FOR THE READ-BACK, where `{0}` is replaced by the
 *  member's actual argument — "the 14-bar RSI of close". On a reference page there
 *  is no actual argument, and printing the raw template ("the {1}-bar RSI of {0}")
 *  shows a member the engine's internals instead of a sentence. The roles are the
 *  right filler because they are what the SIGNATURE column already names, so the
 *  two columns read as one thought.
 *  ⚠️ A slot with no matching role is left ALONE rather than blanked — a missing
 *  role is a manifest defect, and silently swallowing it would hide it. */
function fillRoles(sentence, spec) {
  const roles = (spec && spec.argRoles) || []
  return String(sentence || '').replace(/\{(\d+)\}/g, (whole, i) => {
    const role = roles[Number(i)]
    return role ? `\`${role}\`` : whole
  })
}

const esc = (s) => String(s).replace(/\|/g, '\|')

function table(headers, rows) {
  const out = [`| ${headers.join(' | ')} |`,
    `|${headers.map(() => '---').join('|')}|`]
  for (const r of rows) out.push(`| ${r.map(esc).join(' | ')} |`)
  return out.join('\n')
}

/**
 * The whole reference, as Markdown.
 *
 * ⛔ PURE, AND IT TAKES THE TABLE AS AN ARGUMENT. The default is the shipped
 * manifest; passing one in is how the freshness rail regenerates without
 * touching the file, and how a test can prove the page follows the manifest by
 * feeding it a table it has never seen.
 */
export function renderFormulaDocs(t = TABLE) {
  const L = []
  const P = (s = '') => L.push(s)

  P('# The formula grammar')
  P()
  P('> Generated from `app/src/components/chart/engine/ast/closedTable.json`.')
  P('> Do not edit this file by hand — see "How this page stays true" at the end.')
  P()
  P(`Manifest version **${t.tableVersion}**. Every name below is one this engine`)
  P('can compute, chart, save and run across the whole universe as a screen.')
  P()
  P('## Why the list is closed')
  P()
  P('A formula here has to be decidable **before it runs**: the engine works out how')
  P('much history it needs by adding up the tree, without evaluating anything. That is')
  P('what lets one saved formula sweep thousands of symbols on a schedule instead of')
  P('being redrawn one chart at a time. It is also why a window has to be a plain whole')
  P('number, and why a running total has to say where it starts.')
  P()
  P('If a pasted script names something absent from this page, the door refuses it and')
  P('says which name and why — it never guesses a meaning.')
  P()

  // ── series ────────────────────────────────────────────────────────────────
  P('## Price and volume')
  P()
  P(table(['Name', 'Reads'],
    Object.entries(t.series || {}).map(([k, v]) => [`\`${k}\``, (v && v.doc) || `the bar's ${k}`])))
  P()

  // ── clock ─────────────────────────────────────────────────────────────────
  P('## The clock')
  P()
  P(table(['Name', 'Means'],
    Object.entries(t.clock || {}).map(([k, v]) => [`\`${k}\``, (v && v.sentence) || ''])))
  P()

  // ── operators ─────────────────────────────────────────────────────────────
  P('## Operators')
  P()
  P('⚠️ These carry no sentence in the manifest, so they are listed by what they')
  P('declare — how many operands they take and what they answer.')
  P()
  P(table(['Operator', 'Operands', 'Answers'],
    Object.entries(t.operators || {}).map(([k, v]) => [
      `\`${k}\``, String((v && v.arity) ?? ''), YIELD_ENGLISH[v && v.yields] || String((v && v.yields) || '')])))
  P()

  // ── functions ─────────────────────────────────────────────────────────────
  const fns = Object.entries(t.functions || {}).sort(([a], [b]) => a.localeCompare(b))
  P(`## Functions (${fns.length})`)
  P()
  P('`Needs` is how far back the function reads — the number the engine adds up to')
  P('decide whether a formula can run at all.')
  P()
  P(table(['Call', 'Answers', 'Needs', 'Means'],
    fns.map(([k, v]) => [
      `\`${signature(k, v)}\``,
      YIELD_ENGLISH[v.yields] || String(v.yields || ''),
      lookbackText(v),
      fillRoles(v.sentence, v)])))
  P()

  // ── scalars ───────────────────────────────────────────────────────────────
  const scalars = Object.entries(t.scalars || {}).sort(([a], [b]) => a.localeCompare(b))
  P(`## Per-symbol values (${scalars.length})`)
  P()
  P('One value per symbol rather than one per bar — a fundamental, a rating, a count.')
  P('`Refreshed` is how often the number behind it moves.')
  P()
  P(table(['Name', 'Answers', 'Refreshed', 'Means'],
    scalars.map(([k, v]) => [
      `\`${k}\``,
      YIELD_ENGLISH[v.yields] || String(v.yields || ''),
      String((v && v.cadence) || 'unstated'),
      v.sentence || ''])))
  P()

  P('## How this page stays true')
  P()
  P('It is generated from the manifest, and a test regenerates it on every run and')
  P('fails if this file differs. So it cannot drift from what the engine actually')
  P('declares — the failure mode a hand-written reference has, where a function is')
  P('renamed and the page keeps describing the old one.')
  P()
  P('To update it after changing the manifest:')
  P()
  P('```')
  P('cd app && FORMULA_DOCS_WRITE=1 npx vitest run src/components/chart/engine/ast/formulaDocs.test.js')
  P('```')
  P()
  return L.join('\n')
}
