// app/src/components/chart/engine/ast/formulaDocs.test.js
//
// ─── 🔴 THE REFERENCE CANNOT GO STALE ────────────────────────────────────────
//
// Segment G6 asks for member-facing docs "generated from `closedTable.json` so
// it cannot go stale". This is the half that makes that true: the page is
// regenerated in memory on EVERY run and compared with what is committed, so a
// manifest edit that leaves the page behind fails here rather than shipping a
// reference that describes a function nobody has any more.
//
// ⭐ IT IS NOT A `toMatchSnapshot`. An auto-updating snapshot records what
// happened; this compares against a file a reviewer read and approved, and the
// diff is the thing they read. Same shape as `pineCorpus.json`'s regenerator,
// which this repo already trusts.

import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

import TABLE from './closedTable.json'

const YIELD_ENGLISH = Object.freeze({
  num: 'a number',
  bool: 'true or false',
})

/** `lookback: "arg1"` → "as many bars as argument 1 asks for". */
function lookbackText(spec) {
  const lb = spec && spec.lookback
  if (lb === undefined || lb === null) return 'none'
  if (typeof lb === 'number') return `${lb} bar${lb === 1 ? '' : 's'}`
  const m = /^arg(\d+)$/.exec(String(lb))
  if (m) {
    const role = spec.argRoles && spec.argRoles[Number(m[1])]
    return role ? `whatever \`${role}\` asks for` : `whatever argument ${m[1]} asks for`
  }
  if (lb === 'session') return `a session (${TABLE.sessionMaxBars} bars)`
  return String(lb)
}

/** `rsi(source, period)` — the signature a member types, from the roles. */
function signature(name, spec) {
  const roles = (spec.argRoles && spec.argRoles.length)
    ? spec.argRoles
    : (spec.args || []).map((a, i) => `${a}${i + 1}`)
  return `${name}(${roles.join(', ')})`
}

/** A read-back template with its `{0}` slots filled by the ARGUMENT ROLES.
 *
 *  ⛔ THE SENTENCES ARE WRITTEN FOR THE READ-BACK, where `{0}` is replaced by the
 *  member's actual argument — "the 14-bar RSI of close". On a reference page there
 *  is no actual argument, and printing the raw template ("the {1}-bar RSI of {0}")
 *  shows a member the engine's internals instead of a sentence. The roles are the
 *  right filler because they are what the SIGNATURE column already names, so the
 *  two columns read as one thought.
 *  ⚠️ A slot with no matching role is left ALONE rather than blanked — a missing
 *  role is a manifest defect, and silently swallowing it would hide it. */
function fillRoles(sentence, spec) {
  const roles = (spec && spec.argRoles) || []
  return String(sentence || '').replace(/\{(\d+)\}/g, (whole, i) => {
    const role = roles[Number(i)]
    return role ? `\`${role}\`` : whole
  })
}

const esc = (s) => String(s).replace(/\|/g, '\|')

function table(headers, rows) {
  const out = [`| ${headers.join(' | ')} |`,
    `|${headers.map(() => '---').join('|')}|`]
  for (const r of rows) out.push(`| ${r.map(esc).join(' | ')} |`)
  return out.join('\n')
}

/**
 * The whole reference, as Markdown.
 *
 * ⛔ PURE, AND IT TAKES THE TABLE AS AN ARGUMENT. The default is the shipped
 * manifest; passing one in is how the freshness rail regenerates without
 * touching the file, and how a test can prove the page follows the manifest by
 * feeding it a table it has never seen.
 */
function renderFormulaDocs(t = TABLE) {
  const L = []
  const P = (s = '') => L.push(s)

  P('# The formula grammar')
  P()
  P('> Generated from `app/src/components/chart/engine/ast/closedTable.json`.')
  P('> Do not edit this file by hand — see "How this page stays true" at the end.')
  P()
  P(`Manifest version **${t.tableVersion}**. Every name below is one this engine`)
  P('can compute, chart, save and run across the whole universe as a screen.')
  P()
  P('## Why the list is closed')
  P()
  P('A formula here has to be decidable **before it runs**: the engine works out how')
  P('much history it needs by adding up the tree, without evaluating anything. That is')
  P('what lets one saved formula sweep thousands of symbols on a schedule instead of')
  P('being redrawn one chart at a time. It is also why a window has to be a plain whole')
  P('number, and why a running total has to say where it starts.')
  P()
  P('If a pasted script names something absent from this page, the door refuses it and')
  P('says which name and why — it never guesses a meaning.')
  P()

  // ── series ────────────────────────────────────────────────────────────────
  P('## Price and volume')
  P()
  P(table(['Name', 'Reads'],
    Object.entries(t.series || {}).map(([k, v]) => [`\`${k}\``, (v && v.doc) || `the bar's ${k}`])))
  P()

  // ── clock ─────────────────────────────────────────────────────────────────
  P('## The clock')
  P()
  P(table(['Name', 'Means'],
    Object.entries(t.clock || {}).map(([k, v]) => [`\`${k}\``, (v && v.sentence) || ''])))
  P()

  // ── operators ─────────────────────────────────────────────────────────────
  P('## Operators')
  P()
  P('⚠️ These carry no sentence in the manifest, so they are listed by what they')
  P('declare — how many operands they take and what they answer.')
  P()
  P(table(['Operator', 'Operands', 'Answers'],
    Object.entries(t.operators || {}).map(([k, v]) => [
      `\`${k}\``, String((v && v.arity) ?? ''), YIELD_ENGLISH[v && v.yields] || String((v && v.yields) || '')])))
  P()

  // ── functions ─────────────────────────────────────────────────────────────
  const fns = Object.entries(t.functions || {}).sort(([a], [b]) => a.localeCompare(b))
  P(`## Functions (${fns.length})`)
  P()
  P('`Needs` is how far back the function reads — the number the engine adds up to')
  P('decide whether a formula can run at all.')
  P()
  P(table(['Call', 'Answers', 'Needs', 'Means'],
    fns.map(([k, v]) => [
      `\`${signature(k, v)}\``,
      YIELD_ENGLISH[v.yields] || String(v.yields || ''),
      lookbackText(v),
      fillRoles(v.sentence, v)])))
  P()

  // ── scalars ───────────────────────────────────────────────────────────────
  const scalars = Object.entries(t.scalars || {}).sort(([a], [b]) => a.localeCompare(b))
  P(`## Per-symbol values (${scalars.length})`)
  P()
  P('One value per symbol rather than one per bar — a fundamental, a rating, a count.')
  P('`Refreshed` is how often the number behind it moves.')
  P()
  P(table(['Name', 'Answers', 'Refreshed', 'Means'],
    scalars.map(([k, v]) => [
      `\`${k}\``,
      YIELD_ENGLISH[v.yields] || String(v.yields || ''),
      String((v && v.cadence) || 'unstated'),
      v.sentence || ''])))
  P()

  P('## How this page stays true')
  P()
  P('It is generated from the manifest, and a test regenerates it on every run and')
  P('fails if this file differs. So it cannot drift from what the engine actually')
  P('declares — the failure mode a hand-written reference has, where a function is')
  P('renamed and the page keeps describing the old one.')
  P()
  P('To update it after changing the manifest:')
  P()
  P('```')
  P('cd app && FORMULA_DOCS_WRITE=1 npx vitest run src/components/chart/engine/ast/formulaDocs.test.js')
  P('```')
  P()
  return L.join('\n')
}


// ⚰️ THE RENDERER LIVES HERE, NOT IN ITS OWN MODULE, and the reachability rail
// is why. `app/src/components/screener/reachable.test.js` sweeps all of `app/src`
// and refuses a module no route reaches: "these modules are BUILT and possibly
// GREEN, and no route a member can navigate to reaches them — mount them, delete
// them, or record the decision; do not leave them looking shipped." A doc
// generator has exactly one consumer — the regenerate-and-check case below — so
// shipping it as an app module would have left an orphan that looks like product
// code. Taking the exemption instead would have been the easy wrong answer.
//
// ⚠️ AND IT IS NOT A SECOND AUTHORITY OVER THE IN-APP REFERENCE.
// `pages/formulas/FormulaReference.jsx` renders the same manifest for the web
// page (`import { TABLE } from …/parse`), so both presentations derive from
// `closedTable.json` and neither can drift from it. A markdown file and a React
// page are different media, not two opinions.

const DOC = path.resolve(process.cwd(), '../docs/formulas/GRAMMAR.md')

describe('the formula reference is derived, and it is current', () => {
  it('⭐⭐ regenerating changes nothing — the page matches the manifest', () => {
    const fresh = renderFormulaDocs()
    if (process.env.FORMULA_DOCS_WRITE) {
      fs.mkdirSync(path.dirname(DOC), { recursive: true })
      fs.writeFileSync(DOC, fresh)
    }
    expect(fs.existsSync(DOC),
      'docs/formulas/GRAMMAR.md is missing — regenerate with FORMULA_DOCS_WRITE=1').toBe(true)
    const onDisk = fs.readFileSync(DOC, 'utf8')
    expect(onDisk === fresh,
      'the committed reference no longer matches the manifest. Regenerate with '
      + '`cd app && FORMULA_DOCS_WRITE=1 npx vitest run '
      + 'src/components/chart/engine/ast/formulaDocs.test.js` and read the diff.').toBe(true)
  })

  it('⛔ every function, scalar and clock name in the manifest appears on the page', () => {
    // ⚠️ THE COMPARISON ABOVE CANNOT CATCH A GENERATOR THAT SILENTLY DROPS A
    // SECTION — it would regenerate the same truncated page and agree with
    // itself. This asks the MANIFEST what should be there.
    const page = renderFormulaDocs()
    const missing = []
    for (const section of ['functions', 'scalars', 'clock', 'series', 'operators']) {
      for (const name of Object.keys(TABLE[section] || {})) {
        if (!page.includes(`\`${name}\``) && !page.includes(`\`${name}(`)) {
          missing.push(`${section}.${name}`)
        }
      }
    }
    expect(missing).toEqual([])
    // …and the page is not one enormous name list with no prose.
    expect(page).toMatch(/Why the list is closed/)
  })

  it('⭐ it renders a manifest it has never seen — so it is derived, not transcribed', () => {
    // ⛔⛔ THE NON-VACUITY THAT MATTERS. A generator with the real table's names
    // hard-coded would pass both cases above. This feeds it a table that shares
    // nothing with the shipped one and asserts the invented names come out.
    const fake = {
      tableVersion: 99,
      sessionMaxBars: 7,
      series: { zzprice: { field: 'z', doc: 'a planted series' } },
      clock: { zzclock: { sentence: 'a planted clock value' } },
      operators: { '%%': { arity: 2, yields: 'bool' } },
      functions: {
        zzfn: { args: ['series', 'int'], argRoles: ['source', 'period'],
          lookback: 'arg1', yields: 'num', sentence: 'a planted function of {0}' },
      },
      scalars: { zzscalar: { yields: 'num', cadence: 'nightly', sentence: 'a planted scalar' } },
    }
    const page = renderFormulaDocs(fake)
    expect(page).toContain('zzfn(source, period)')
    // ⭐ THE `{0}` SLOT IS FILLED FROM THE ARG ROLE, not printed raw. The
    // sentences are written for the READ-BACK, where `{0}` becomes the member's
    // actual argument; on a reference page there is no actual argument, and the
    // raw template shows a member the engine's internals. This case caught the
    // improvement going in — it asserted the raw form and had to move.
    expect(page).toContain('a planted function of `source`')
    expect(page).not.toContain('a planted function of {0}')
    expect(page).toContain('zzscalar')
    expect(page).toContain('zzclock')
    expect(page).toContain('%%')
    expect(page).toMatch(/version \*\*99\*\*/)
    // …and the lookback is DERIVED from the role, not printed raw.
    expect(page).toContain('whatever `period` asks for')
    // ⛔ and none of the REAL table leaked into a page built from the fake one.
    expect(page).not.toContain('rsi(')
    expect(page).not.toContain('market_cap')
  })

  it('⛔ a manifest entry with no sentence is rendered honestly, not invented', () => {
    // `series` and `operators` carry no `sentence` (measured: 0 of 5, 0 of 15).
    // The page must show what they DO declare rather than prose written in the
    // generator, which would be a second authority over what a name means.
    const page = renderFormulaDocs({
      tableVersion: 1, sessionMaxBars: 1,
      series: {}, clock: {}, functions: {}, scalars: {},
      operators: { '@@': { arity: 2, yields: 'num' } },
    })
    expect(page).toContain('`@@`')
    expect(page).toContain('a number')
  })
})
