// app/src/components/chart/engine/ast/screenerColumns.test.js
//
// ─── ⭐⭐ THE COLUMNS THE SCREENER CORPUS PRODUCES, FROZEN FOR THE OTHER LANE ──
//
// `tests/fixtures/pine_screener/*.pine` proves those scripts TRANSLATE and yield
// boolean columns. It cannot prove the PYTHON lane computes the same numbers,
// because translation is JS-only — and that is the reliability claim that
// actually matters to a member: what the chart draws and what the screen filters
// on have to be one number.
//
// ⭐ SO THIS FILE FREEZES THE FORMULAS AND THEIR TREES, and
// `tests/test_screener_lane_parity.py` runs them through BOTH interpreters on
// 400 real SPY daily bars. Neither file can make that claim alone.
//
// ⛔⛔ AND THE FIXTURE CANNOT GO STALE, which is the whole reason it is generated
// here rather than written by hand. This test REGENERATES it from the `.pine`
// sources every run and fails if what is committed differs — the same
// regenerate-and-check shape `formulaDocs.test.js` uses for `GRAMMAR.md`. A
// frozen artifact nobody re-derives is a claim about a run that happened once.

import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

import { translatePine } from './pine.js'
import { parseFormula } from './parse.js'

const DIR = path.resolve(process.cwd(), '../tests/fixtures/pine_screener')
const FIXTURE = path.resolve(process.cwd(), '../tests/fixtures/ast/screener_columns.json')

/** Derived from the `.pine` sources, never typed. */
function derive() {
  const cases = []
  for (const f of fs.readdirSync(DIR).filter((x) => x.endsWith('.pine')).sort()) {
    const out = translatePine(fs.readFileSync(path.join(DIR, f), 'utf8'))
    if (!out.ok) continue
    const row = out.outputs[out.selected]
    const parsed = parseFormula(row.formula)
    if (!parsed.ok) continue
    cases.push({ id: f.replace(/\.pine$/, ''), source: row.formula, ast: parsed.ast })
  }
  return {
    _: 'GENERATED by app/src/components/chart/engine/ast/screenerColumns.test.js '
      + 'from tests/fixtures/pine_screener/*.pine. Do not hand-edit: the test '
      + 'regenerates it and fails on any difference. Consumed by '
      + 'tests/test_screener_lane_parity.py, which runs both interpreters over it.',
    bars: 'tests/fixtures/alerts/replay_bars.json#spy_daily',
    cases,
  }
}

describe('the screener columns are frozen for the Python lane to read', () => {
  it('⛔⛔ the committed fixture is what the sources produce TODAY', () => {
    const want = derive()
    // ⭐ Regenerating on demand rather than only checking, so a legitimate change
    // to a fixture or the translator is one command away.
    if (process.env.SCREENER_COLUMNS_WRITE) {
      fs.writeFileSync(FIXTURE, `${JSON.stringify(want, null, 1)}\n`)
    }
    expect(fs.existsSync(FIXTURE), `${FIXTURE} is missing — regenerate with `
      + 'SCREENER_COLUMNS_WRITE=1').toBe(true)
    const have = JSON.parse(fs.readFileSync(FIXTURE, 'utf8'))
    expect(have.cases.map((c) => c.id)).toEqual(want.cases.map((c) => c.id))
    for (const c of want.cases) {
      const got = have.cases.find((x) => x.id === c.id)
      expect(got.source, `${c.id} formula drifted`).toBe(c.source)
      expect(got.ast, `${c.id} tree drifted`).toEqual(c.ast)
    }
  })

  it('⭐ it is not empty, and every case carries a tree the parser accepts', () => {
    // ⛔ A FIXTURE THAT EMPTIED WOULD MAKE THE PYTHON RAIL PASS OVER NOTHING —
    // the failure mode that file cannot see from where it stands.
    const have = JSON.parse(fs.readFileSync(FIXTURE, 'utf8'))
    expect(have.cases.length).toBeGreaterThanOrEqual(34)
    for (const c of have.cases) {
      expect(parseFormula(c.source).ok, `${c.id}: ${c.source}`).toBe(true)
    }
  })
})
