"""TERM-061 / BRK-06 / FT-040 -- the published agent skill file and its endpoint whitelist.

    GET /api/skill.md         the skill file, text/markdown
    GET /api/skill/whitelist  the same two lists as JSON

Both are generated by `api/services/skill_whitelist.py` from THIS app's own route table
(`request.app`), so the published list is the enforced set by construction: there is no second
copy to drift. Owner ruling T-16 (docs/terminal-research/12-decisions/2026-10-07-owner-delegated-
decisions.md:61): publish once RATE_LIMIT_POLICY=enforce (A4, same file :141, read live
2026-10-07); no MCP server.

Deliberately anonymous: an agent reads the skill file before it holds any credential, and the
file names only paths, tiers and limits, never data. Recorded as `public` in
api/auth_surface_read_baseline.json; rate-limited under the `docs` family.

Routes do not change at runtime, so each document is built once per app and cached in-process;
`Cache-Control: public, max-age=300` lets the edge hold it too.
"""
from __future__ import annotations

import threading

from fastapi import APIRouter, Request
from fastapi.responses import JSONResponse, Response
from starlette.concurrency import run_in_threadpool

from api.services import skill_whitelist as sw

router = APIRouter(tags=["skill"])

CACHE_CONTROL = "public, max-age=300"

_lock = threading.Lock()
_cache: dict[tuple[int, int], dict] = {}


def _built(app) -> dict:
    """`{"data": ..., "md": ...}` for this app, built once. Keyed on the app's identity and its
    route count, so a test app and the real app never share an entry."""
    key = (id(app), len(getattr(app, "routes", [])))
    with _lock:
        hit = _cache.get(key)
    if hit is not None:
        return hit
    data = sw.build(app)
    out = {"data": data, "md": sw.to_skill_md(data)}
    with _lock:
        _cache[key] = out
    return out


def reset_cache() -> None:
    with _lock:
        _cache.clear()


@router.get(sw.SKILL_MD_PATH, include_in_schema=False)
async def skill_md(request: Request):
    built = await run_in_threadpool(_built, request.app)
    return Response(content=built["md"], media_type="text/markdown; charset=utf-8",
                    headers={"Cache-Control": CACHE_CONTROL})


@router.get(sw.WHITELIST_PATH, include_in_schema=False)
async def skill_whitelist(request: Request):
    built = await run_in_threadpool(_built, request.app)
    return JSONResponse(built["data"], headers={"Cache-Control": CACHE_CONTROL})
