"""TERM-061 / BRK-06 / FT-040 -- the published agent skill file and its endpoint whitelist.

    GET /api/skill.md         the skill file, text/markdown
    GET /api/skill/whitelist  the same two lists as JSON

Both are generated by `api/services/skill_whitelist.py` from THIS app's own route table
(`request.app`), so the published list is the enforced set by construction: there is no second
copy to drift. Owner ruling T-16 (docs/terminal-research/12-decisions/2026-10-07-owner-delegated-
decisions.md:61): publish once RATE_LIMIT_POLICY=enforce (A4, same file :141, read live
2026-10-07); no MCP server.

SIGNED-IN MEMBERS ONLY (`get_current_user`, the same gate as the personal-token management
routes): the file is a map of endpoint paths, and the owner's OPEN_READS_GATE intent is that
an anonymous visitor does not get one. A personal token is refused here too (the gate reads the
cookie only). Being Depends-gated, the routes are counted as gated by the auth-surface census
and so are NOT in api/auth_surface_read_baseline.json (an entry there for a gated route is a
stale-baseline finding). Rate-limited under the `docs` family.

Routes do not change at runtime, so each document is built once per app and cached in-process.
`Cache-Control: private, max-age=300`: never `public`, because an edge cache keys on the URL,
not the cookie, and would hand a member's copy to an anonymous caller.
"""
from __future__ import annotations

import threading

from fastapi import APIRouter, Depends, Request
from fastapi.responses import JSONResponse, Response
from starlette.concurrency import run_in_threadpool

from api.middleware.auth_middleware import get_current_user
from api.services import skill_whitelist as sw

router = APIRouter(tags=["skill"])

CACHE_CONTROL = "private, max-age=300"

_lock = threading.Lock()
_cache: dict[tuple[int, int], dict] = {}


def _built(app) -> dict:
    """`{"data": ..., "md": ...}` for this app, built once. Keyed on the app's identity and its
    route count, so a test app and the real app never share an entry."""
    key = (id(app), len(getattr(app, "routes", [])))
    with _lock:
        hit = _cache.get(key)
    if hit is not None:
        return hit
    data = sw.build(app)
    out = {"data": data, "md": sw.to_skill_md(data)}
    with _lock:
        _cache[key] = out
    return out


def reset_cache() -> None:
    with _lock:
        _cache.clear()


@router.get(sw.SKILL_MD_PATH, include_in_schema=False)
async def skill_md(request: Request, _user: dict = Depends(get_current_user)):
    built = await run_in_threadpool(_built, request.app)
    return Response(content=built["md"], media_type="text/markdown; charset=utf-8",
                    headers={"Cache-Control": CACHE_CONTROL})


@router.get(sw.WHITELIST_PATH, include_in_schema=False)
async def skill_whitelist(request: Request, _user: dict = Depends(get_current_user)):
    built = await run_in_threadpool(_built, request.app)
    return JSONResponse(built["data"], headers={"Cache-Control": CACHE_CONTROL})
