/**
 * Cross-language schema contract rail (Task 5, note-connectors).
 *
 * Connectors run server-side (Python, `note_connectors/convert/mddoc.py`) and
 * emit TipTap JSON directly — no browser, so the wizard's own client-side
 * `generateJSON` round-trip can never validate that output. This is the CI
 * tripwire: every fixture the Python side committed under
 * `__fixtures__/server_convert/*.json` (generated by
 * `python -m api.services.journal_two.note_connectors.convert.fixtures_gen`
 * from `convert/fixtures_in/*.md`) must parse cleanly through the REAL
 * editor schema (`buildExtensions()` — the exact extension set the Notebook
 * editor mounts) and render to non-empty HTML. If the Python converter ever
 * emits a node/mark/attr shape the JS schema doesn't recognize, THIS test
 * goes red — not a silent runtime crash the next time a connector-imported
 * note is opened.
 *
 * Before any fixtures exist/are committed this whole file is vacuously
 * empty (`describe.each([])` runs zero tests) — the TDD-red state this task
 * started from was "no server_convert/*.json exist yet", not a thrown error.
 */
import { describe, it, expect, beforeAll } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { getSchema, generateHTML } from '@tiptap/core'
import { buildExtensions } from '../tiptap'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const FIXTURES_DIR = path.join(__dirname, '__fixtures__', 'server_convert')

function loadFixtures() {
  if (!fs.existsSync(FIXTURES_DIR)) return []
  return fs
    .readdirSync(FIXTURES_DIR)
    .filter((f) => f.endsWith('.json'))
    .sort()
    .map((file) => {
      const raw = fs.readFileSync(path.join(FIXTURES_DIR, file), 'utf-8')
      return { file, fixture: JSON.parse(raw) }
    })
}

const fixtures = loadFixtures()
const extensions = buildExtensions()
// NOTE: `getSchema` already calls `resolveExtensions` internally (see
// @tiptap/core's own source) — wrapping it in an explicit `resolveExtensions()`
// call here would double-resolve (re-flatten already-flattened StarterKit
// child extensions) and trip its own "Duplicate extension names found" warning.
// `schema.nodeFromJSON(doc)` below is the canonical single-resolve API.
const schema = getSchema(extensions)

describe('server_convert fixtures validate against the real editor schema', () => {
  // A non-vacuity control: if the fixtures directory is empty or missing,
  // fail loudly rather than let `describe.each([])` report zero tests as a
  // silent pass — that is exactly the "no fixtures yet" red state this rail
  // must NOT be mistaken for green once fixtures are expected to exist.
  it('found at least one committed fixture', () => {
    expect(fixtures.length).toBeGreaterThan(0)
  })

  describe.each(fixtures.map(({ file, fixture }) => [file, fixture]))('%s', (file, fixture) => {
    it('has the {doc, media, links} shape the generator produces', () => {
      expect(fixture).toHaveProperty('doc')
      expect(fixture.doc).toHaveProperty('type', 'doc')
      expect(Array.isArray(fixture.media)).toBe(true)
      expect(Array.isArray(fixture.links)).toBe(true)
    })

    it('parses through the real schema without throwing', () => {
      expect(() => schema.nodeFromJSON(fixture.doc)).not.toThrow()
    })

    it('renders non-empty HTML via generateHTML', () => {
      const html = generateHTML(fixture.doc, extensions)
      expect(typeof html).toBe('string')
      expect(html.length).toBeGreaterThan(0)
    })
  })
})

// ---------------------------------------------------------------------------
// Semantic pins — these must not merely "not throw"; specific import-critical
// behavior (checked task state, table structure, link hrefs) must survive
// the JSON -> schema -> HTML round trip byte-for-byte.
// ---------------------------------------------------------------------------

describe('semantic pins', () => {
  it('at least one fixture keeps a checked taskItem\'s checked state as data-checked="true" in HTML', () => {
    const matches = fixtures.filter(({ fixture }) => generateHTML(fixture.doc, extensions).includes('data-checked="true"'))
    expect(matches.length).toBeGreaterThan(0)
  })

  it('at least one fixture renders a <table> element', () => {
    const matches = fixtures.filter(({ fixture }) => generateHTML(fixture.doc, extensions).includes('<table'))
    expect(matches.length).toBeGreaterThan(0)
  })

  it('at least one fixture preserves a link mark href in the rendered HTML', () => {
    const matches = fixtures.filter(({ fixture }) => generateHTML(fixture.doc, extensions).includes('href="https://example.com/design"'))
    expect(matches.length).toBeGreaterThan(0)
  })

  // Scoped to ONE fixture (07-onenote-task-list, produced by html_to_tiptap's
  // additive `data-uct-task` branch, mddoc.py::_html_list_or_tasklist) rather
  // than the generic "at least one fixture" pins above: 02-mixed-task-list
  // (the markdown checkbox path) already satisfies those independently of
  // whether the HTML branch's checked attr is right or wrong, so a mutation
  // localized to the HTML branch would slip past them silently. This pin is
  // the mutation-check target (task-5 brief): corrupt the taskItem `checked`
  // attr in `_html_list_or_tasklist`, regenerate fixtures, and THIS goes red.
  it('07-onenote-task-list fixture keeps both checked and unchecked task states', () => {
    const entry = fixtures.find(({ file }) => file === '07-onenote-task-list.json')
    expect(entry).toBeTruthy()
    const html = generateHTML(entry.fixture.doc, extensions)
    expect(html).toContain('data-checked="true"')
    expect(html).toContain('data-checked="false"')
  })
})
