"""Prewarm the Company Panel "story" (stock_brief) for the whole universe.

The story -- one sentence on what the company does plus 2-3 on why it has moved
this year -- is generated by Claude on FIRST VIEW, which is the 5-10s wait a
member sees on a ticker nobody has opened before. It is cached per (symbol,
year) and refreshed quarterly, so generating it ahead of time removes that wait
permanently for the cost of one generation per symbol.

Run it here rather than through the API: `_generate_and_store` is the exact
function the on-view background thread calls, so a prewarmed story is
byte-identical to a lazily generated one -- this only changes WHEN it happens.

    PYTHONPATH=/app python scripts/prewarm_stock_briefs.py [--workers 6] [--limit N]

Resumable and idempotent by construction: anything already cached and still
fresh is skipped, so re-running after an interruption costs nothing. Safe to
kill at any point.
"""
from __future__ import annotations

import argparse
import os
import sys
import threading
import time

# ⛔ BEFORE importing the service: _DAILY_CAP is read at import time. It exists to
# stop live per-view generation from running away, which is not what a bounded,
# deliberate prewarm is -- so lift it for THIS PROCESS ONLY. The web pod keeps
# its own cap.
os.environ.setdefault("STOCK_BRIEF_DAILY_CAP", "1000000")

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from concurrent.futures import ThreadPoolExecutor, as_completed  # noqa: E402

from api.services import cap_universe                            # noqa: E402
from api.services.stock_brief import service as sb               # noqa: E402
from api.services.stock_brief import store as sb_store           # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--workers", type=int, default=6,
                    help="parallel generations (Anthropic rate limit is the ceiling)")
    ap.add_argument("--limit", type=int, default=0, help="stop after N symbols")
    ap.add_argument("--symbols", default="", help="comma-separated override")
    args = ap.parse_args()

    year = sb._year()
    period = sb._period(year)

    if args.symbols:
        universe = [s.strip().upper() for s in args.symbols.split(",") if s.strip()]
    else:
        universe = sorted(cap_universe.symbols())

    todo = [s for s in universe
            if sb_store.needs_generation(s, period, sb._RETRY_AFTER, sb._REFRESH_AFTER)]
    if args.limit:
        todo = todo[:args.limit]

    print(f"universe={len(universe)} already_fresh={len(universe) - len(todo)} "
          f"to_generate={len(todo)} workers={args.workers} period={period}",
          flush=True)
    if not todo:
        print("nothing to do", flush=True)
        return 0

    t0 = time.time()
    done = 0
    lock = threading.Lock()

    def one(sym: str) -> str:
        nonlocal done
        try:
            sb._generate_and_store(sym)
        except Exception as e:                            # noqa: BLE001
            print(f"  !! {sym}: {type(e).__name__}: {e}", flush=True)
        with lock:
            done += 1
            if done % 50 == 0 or done == len(todo):
                el = time.time() - t0
                rate = done / el if el else 0
                eta = (len(todo) - done) / rate if rate else 0
                print(f"  {done}/{len(todo)}  {rate:.2f}/s  eta {eta/60:.1f} min",
                      flush=True)
        return sym

    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        for f in as_completed([pool.submit(one, s) for s in todo]):
            f.result()

    # Report what actually landed rather than what we attempted: a generation can
    # return nothing (model refused, API failure) and that is marked for retry.
    stored = sum(1 for s in todo if sb_store.has_content(s, period))
    print(f"done in {(time.time()-t0)/60:.1f} min: {stored}/{len(todo)} stored, "
          f"{len(todo)-stored} left for the retry cooldown", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
