"""emit_tables.py — write the committable demand tables from the CORRECTED aggregates."""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.abspath(os.path.join(HERE, "..", "research"))
OUT = os.path.join(HERE, "tables")
os.makedirs(OUT, exist_ok=True)


def j(p):
    return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None


cor = j(os.path.join(RES, "agg_presentation_corrected.json"))
raw = j(os.path.join(HERE, "agg_presentation.json"))
comp = j(os.path.join(HERE, "agg_computation.json"))
const = j(os.path.join(HERE, "agg_constants.json"))
wt = j(os.path.join(HERE, "weighted.json")) or {}

HEAD = """<!-- GENERATED by tools/pine_survey — do not hand-edit. Regenerate from the survey. -->
"""

# ── presentation
if cor:
    raw_by = {r["primitive"]: r for r in (raw or {}).get("primitives", [])}
    L = [HEAD, "# Demand-weighted presentation primitives\n",
         "Every presentation primitive in Pine, ranked by the share of surveyed scripts that call it.",
         "**This is the renderer's build order.**\n",
         "- Population: **%s** scripts — every open-source script TradingView's catalogue returned, not a sample."
         % "{:,}".format(cor["n_scripts"]),
         "- Counts are **call sites**, not runtime objects. The gap is up to two orders of magnitude; see the",
         "  capacity caveat below before sizing anything.",
         "- `corrected` columns include Pine's method-call syntax (`myLine.set_x2()`), which a namespace-only",
         "  scan cannot see. `Δ` is the share recovered by that correction.",
         "- Plot-family rows are externally validated: they agree exactly with TradingView's own compiler counts.\n",
         "| # | primitive | % scripts | Δ | call sites | named arguments actually passed |",
         "|---:|---|---:|---:|---:|---|"]
    for i, r in enumerate(cor["primitives"], 1):
        old = raw_by.get(r["primitive"], {}).get("pct_scripts")
        d = ""
        if old is not None and abs(old - r["pct_scripts"]) > 0.05:
            d = "+%.1f" % (r["pct_scripts"] - old)
        args = ", ".join("`%s`" % a for a in list((r.get("named_args") or {}).keys())[:10]) or "—"
        L.append("| %d | `%s` | %.1f%% | %s | %s | %s |"
                 % (i, r["primitive"], r["pct_scripts"], d, "{:,}".format(r["call_sites"]), args))
    L += ["", "## Capacity caveat — read before sizing", "",
          "Call sites are not objects. Across the corpus, scripts reserve **1,350,528** drawing objects via",
          "`max_*_count` against **21,625** constructor call sites (62x), and declare **299,259** table cells",
          "against **16,808** `cell()` sites (17.8x). A single `box.new` inside a loop can hold ~945 boxes.",
          "Use this table to decide *what* to implement, never *how much* to allocate.", "",
          "## Two blind spots this table does not fix", "",
          "1. **Library-mediated drawing.** 344 scripts (7.0%) import a library; 2,943 alias-mediated calls are",
          "   uncounted, and 59 scripts reserve drawing capacity while calling no constructor of their own.",
          "2. **`display.none`.** 1,798 of 16,907 `plot` sites (10.6%) are declared invisible. That affects what",
          "   *paints*, not what the parser must accept, so it is deliberately not netted out of the rows above.", ""]
    open(os.path.join(OUT, "demand-presentation.md"), "w", encoding="utf-8").write("\n".join(L))
    print("demand-presentation.md  %d rows" % len(cor["primitives"]))

# ── computation
if comp:
    L = [HEAD, "# Demand-weighted computation and language features\n",
         "- Population: **%s** open-source scripts." % "{:,}".format(comp["n_scripts"]),
         "- `feat:` rows are language constructs; `bare:` rows are un-namespaced pre-v5 builtins, which appear",
         "  only in v1–v4 scripts — all of which TradingView still compiles and serves.\n",
         "| feature | % scripts | call sites |", "|---|---:|---:|"]
    for r in comp["features"]:
        L.append("| `%s` | %.1f%% | %s |" % (r["feature"], r["pct_scripts"], "{:,}".format(r["call_sites"])))
    open(os.path.join(OUT, "demand-computation.md"), "w", encoding="utf-8").write("\n".join(L))
    print("demand-computation.md   %d rows" % len(comp["features"]))

# ── constants
if const:
    L = [HEAD, "# Demand-weighted enumerated constants\n",
         "Which members of Pine's constant namespaces are actually used, over **%s** scripts."
         % "{:,}".format(const["n_scripts"]),
         "This is the support order for constant handling.\n",
         "| constant | % scripts | call sites |", "|---|---:|---:|"]
    for r in const["constants"]:
        L.append("| `%s` | %.1f%% | %s |" % (r["constant"], r["pct_scripts"], "{:,}".format(r["call_sites"])))
    open(os.path.join(OUT, "demand-constants.md"), "w", encoding="utf-8").write("\n".join(L))
    print("demand-constants.md     %d rows" % len(const["constants"]))

# ── popularity weighting
if wt:
    order = ["all_open_source", "top_2000_by_boosts", "top_1000_by_boosts", "top_250_by_boosts"]
    labels = ["all", "top 2,000", "top 1,000", "top 250"]
    keys = [k for k in wt[order[0]].keys() if k != "n"]
    L = [HEAD, "# The same survey, weighted two ways\n",
         "The catalogue was walked most-boosted-first, so the popular cohort and the full set are different",
         "populations — and they disagree. A feature that **rises to the right is under-stated** by a flat",
         "per-script count: it matters more to what members actually put on charts than the headline suggests.\n",
         "| feature | " + " | ".join(labels) + " |", "|---|" + "---:|" * len(labels)]
    L.append("| **n** | " + " | ".join("{:,}".format(wt[o]["n"]) for o in order) + " |")
    for k in keys:
        vals = []
        for o in order:
            v = wt[o].get(k)
            vals.append(("%s" % v) if k == "median_lines" else ("%.1f%%" % v))
        L.append("| `%s` | " % k + " | ".join(vals) + " |")
    open(os.path.join(OUT, "demand-popularity-weighted.md"), "w", encoding="utf-8").write("\n".join(L))
    print("demand-popularity-weighted.md")
