//@version=6

indicator("Pocket Pivot Breakout", overlay = true)
barsize=input(3, "% change")
ppdays=input(10, "Pocket Pivot Lookback Days")
gapcandle=input(false, "Gap-up Bar")
gapvalue=input(0.5, "Gap-up Value in %")
mymaxvolume = volume
greenday = close > open and (((close-open)/close)*100)>barsize
gapup = low > high[1] and ((low-high[1])/low)*100>gapvalue and gapcandle

ispp = false

volchk = array.new<float>(ppdays+1)

for i = 1 to ppdays
    if close[i] > open [i]
        array.set(volchk, i, 0)
    else
        array.set(volchk, i, volume[i])

ppchk = 0

for i = 1 to ppdays
    if mymaxvolume<array.get(volchk,i)
        ppchk += 1

if ppchk < 1 and greenday
    ispp := true

alertcondition(ispp, title='Pocket Pivot Breakout Alert', message='Pocket Pivot Breakout Alert')
alertcondition(gapup, title='Gap-Up Alert', message='Gap-Up Alert')

plotshape(ispp ? 1 : 0, style=shape.triangleup, location=location.belowbar, color= color.blue, size=size.auto)
barcolor(gapup ? color.blue : na, title="Gap-up Bar Color")