// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// Initially created by © LazySprinter - modified by me

//@version=6
indicator('S - SPY VIX Pot', overlay = true)

i_range_1 = input.string(title = 'Range (Day/Week)', options = ['D', 'W'], defval = 'D')
t = time(i_range_1)
start = na(t[1]) or t > t[1]

ticker = syminfo.ticker
i_show_VWAP = input(true, 'Show VWAP?', inline = '1')
i_VWAP_color = input.color(color.rgb(255, 196, 30), title = 'VWAP Color', inline = '1')
i_src = input(title = 'Source', defval = hl2)
i_IV_src = input.symbol(title = 'IV Source', defval = 'CBOE:VIX')
i_showhalflevels = input(true, 'Show 50% levels')
i_default_to_vix9d = input(true, title = 'Default to VIX when IV is not available')
i_up_color = input.color(color.rgb(12, 148, 30), title = 'Up Color', inline = '2')
i_dn_color = input.color(color.rgb(255, 23, 30), title = 'Down Color', inline = '2')

i_linestyle = input.string('Circles', 'Full Level Line Style', options = ['Line','LineBr', 'Stepline', 'Circles', 'Cross'])
i_line_wid = input.int(1, 'Full Level Width',minval = 1, maxval = 4)
i_half_linestyle = input.string('LineBr', 'Half Level Line Style', options = ['Line','LineBr', 'Stepline', 'Circles', 'Cross'])
i_half_line_wid = input.int(1, 'Full Level Width',minval = 1, maxval = 4)
i_fill = input(false, 'Fill between levels?')

vix(sym) =>
    request.security(ticker.new('CBOE', sym, syminfo.session), timeframe.period, i_src, barmerge.gaps_on)

d2exp = 30
IV = ticker == 'AAPL' ? vix('VXAPL') : na
IV := ticker == 'AMZN' ? vix('VXAZN') : IV
IV := ticker == 'IBM' ? vix('VXIBM') : IV
IV := ticker == 'GOOG' ? vix('VXGOG') : IV
IV := ticker == 'GS' ? vix('VXGS') : IV

vix_security = request.security(i_IV_src, timeframe.period, i_src)
if ticker == 'SPY' or na(IV) and i_default_to_vix9d
    IV := vix_security // vix("VIX")
    IV

// Standard deviation (expected 1 SD move) calculation from VIX (equivalent to 30 days Implied Volatility)
// Example: https://money.stackexchange.com/questions/81494/how-to-calculate-the-expected-move-of-a-stock
sd = i_src * (IV / 100.0) * math.sqrt(d2exp / 365.0) / d2exp

// UI code starts here --
// Dynamically shows the lines if price gets close to reduce the clutters

show_if_close_by_percentage = 99
keep_showing_once_shown = 25

is_near(l, lb) => math.abs(l[lb] - i_src[lb]) < show_if_close_by_percentage / 100.0 * sd

is_near_since_back(l, far) =>
    is_n = false
    for i = 0 to far by 1
        is_n := is_n or is_near(l, i)
        is_n
    is_n

show(l) =>
    is_near_since_back(l, keep_showing_once_shown) ? l : na

// Style & Colors

_style = switch i_linestyle
    'Line' => plot.style_line
    'LineBr'      => plot.style_linebr
    'Stepline'    => plot.style_stepline
    'Circles'      => plot.style_circles
    'Cross' => plot.style_cross
    =>
        plot.style_linebr

_style_half = switch i_half_linestyle
    'Line' => plot.style_line
    'LineBr'      => plot.style_linebr
    'Stepline'    => plot.style_stepline
    'Circles'      => plot.style_circles
    'Cross' => plot.style_cross
    =>
        plot.style_linebr

start_transp = 99
start_transp_line = 20
transp_delta = 5

vwapc = color.new(i_VWAP_color, start_transp_line - 3 * transp_delta)

uc3 = color.new(i_up_color, start_transp_line - 2 * transp_delta)
uc2 = color.new(i_up_color, start_transp_line - 1 * transp_delta)
uc1 = color.new(i_up_color, start_transp_line)
dc1 = color.new(i_dn_color, start_transp_line)
dc2 = color.new(i_dn_color, start_transp_line - 1 * transp_delta)
dc3 = color.new(i_dn_color, start_transp_line - 2 * transp_delta)


ufc3 = i_fill ? color.new(i_up_color, start_transp - 2 * transp_delta) : na
ufc2 = i_fill ? color.new(i_up_color, start_transp - 1 * transp_delta) : na
ufc1 = i_fill ? color.new(i_up_color, start_transp) : na
dfc1 = i_fill ? color.new(i_dn_color, start_transp) : na
dfc2 = i_fill ? color.new(i_dn_color, start_transp - 1 * transp_delta) : na
dfc3 = i_fill ? color.new(i_dn_color, start_transp - 2 * transp_delta) : na

// Plots

sumSrc = i_src * volume
sumVol = volume
sumSrc := start ? sumSrc : sumSrc + sumSrc[1]
sumVol := start ? sumVol : sumVol + sumVol[1]

// plot(sumSrc / sumVol, title="VWAP", color=color.blue)

vw1 = sumSrc / sumVol // vwap(src)
vw = start ? na : vw1

v = plot(i_show_VWAP ? vw : na, title = 'VWAP', color = vwapc, style = _style)

u_5         = show(vw + 5 * sd)
u_4_half    = show(vw + 4.5 * sd)
u_4         = show(vw + 4 * sd)
u_3_half    = show(vw + 3.5 * sd)
u_3         = show(vw + 3 * sd)
u_2_half    = show(vw + 2.5 * sd)
u_2         = show(vw + 2 * sd)
u_1_half    = show(vw + 1.5 * sd)
u_1         = show(vw + sd)
u_half      = show(vw + 0.5 * sd)

d_half      = show(vw - 0.5 * sd)
d_1         = show(vw - sd)
d_1_half    = show(vw - 1.5 * sd)
d_2         = show(vw - 2 * sd)
d_2_half    = show(vw - 2.5 * sd)
d_3         = show(vw - 3 * sd)
d_3_half    = show(vw - 3.5 * sd)
d_4         = show(vw - 4 * sd)
d_4_half    = show(vw - 4.5 * sd)
d_5         = show(vw - 5 * sd)

plot_u_5        = plot(u_5, '5 Std Dev', color = uc3, style = _style, linewidth = i_line_wid)
plot_u_4_half   = plot(i_showhalflevels ? u_4_half : na, '4.5 Std Dev', color = uc3, style = _style, linewidth = i_half_line_wid)
plot_u_4        = plot(u_4, '4 Std Dev', color = uc3, style = _style, linewidth = i_line_wid)
plot_u_3_half   = plot(i_showhalflevels ? u_3_half : na, '3.5 Std Dev', color = uc3, style = _style_half, linewidth = i_half_line_wid)
plot_u_3        = plot(u_3, '3 Std Dev', color = uc3, style = _style, linewidth = i_line_wid)
plot_u_2_half   = plot(i_showhalflevels ? u_2_half : na, '2.5 Std Dev', color = uc3, style = _style_half, linewidth = i_half_line_wid)
plot_u_2        = plot(u_2, '2 Std Dev', color = uc2, style = _style, linewidth = i_line_wid)
plot_u_1_half   = plot(i_showhalflevels ? u_1_half : na, '1.5 Std Dev', color = uc2, style = _style_half, linewidth = i_half_line_wid)
plot_u_1        = plot(u_1, '1 Std Dev', color = uc1, style = _style, linewidth = i_line_wid)
plot_u_half     = plot(i_showhalflevels ? u_half : na, '0.5 Std Dev', color = uc1, style = _style_half, linewidth = i_half_line_wid)

plot_d_half     = plot(i_showhalflevels ? d_half : na, '-0.5 Std Dev', color = dc1, style = _style_half, linewidth = i_half_line_wid)
plot_d_1        = plot(d_1, '-1 Std Dev', color = dc1, style = _style, linewidth = i_line_wid)
plot_d_1_half   = plot(i_showhalflevels ? d_1_half : na, '-1.5 Std Dev', color = dc2, style = _style_half, linewidth = i_half_line_wid)
plot_d_2        = plot(d_2, '-2 Std Dev', color = dc2, style = _style, linewidth = i_line_wid)
plot_d_2_half   = plot(i_showhalflevels ? d_2_half : na, '-2.5 Std Dev', color = dc3, style = _style_half, linewidth = i_half_line_wid)
plot_d_3        = plot(d_3, '-3 Std Dev', color = dc3, style = _style, linewidth = i_line_wid)
plot_d_3_half   = plot(i_showhalflevels ? d_3_half : na, '-3.5 Std Dev', color = dc3, style = _style_half, linewidth = i_half_line_wid)
plot_d_4        = plot(d_4, '-4 Std Dev', color = dc3, style = _style, linewidth = i_line_wid)
plot_d_4_half   = plot(i_showhalflevels ? d_4_half : na, '-4.5 Std Dev', color = dc3, style = _style_half, linewidth = i_half_line_wid)
plot_d_5        = plot(d_5, '-5 Std Dev', color = dc3, style = _style, linewidth = i_line_wid)

fill(plot_u_4, plot_u_5, color = ufc3)
fill(plot_u_3, plot_u_4, color = ufc3)
fill(plot_u_2, plot_u_3, color = ufc3)
fill(plot_u_1, plot_u_2, color = ufc2)
fill(v, plot_u_1, color = ufc1)
fill(v, plot_d_1, color = dfc1)
fill(plot_d_1, plot_d_2, color = dfc2)
fill(plot_d_2, plot_d_3, color = dfc3)
fill(plot_d_3, plot_d_4, color = dfc3)
fill(plot_d_4, plot_d_5, color = dfc3)