// Ground truth for the citation-text parity rails, generated by the REAL
// prosemirror-model (never by a reading of it).
//
// Run from app/, so module resolution finds the package:
//   NODE_PATH="$PWD/node_modules" node ../tools/gen_pm_citation_fixtures.cjs > ../tests/fixtures_pm_citation_text.json
//
// For each case it records the doc JSON, `content.size`, every text node's
// position, and:
//   - `text`: textBetween(0, size, '\n', citationLeafText) -- the leaf-text
//     function IMPORTED FROM THE CLIENT MODULE (askCitation.js), so the Python
//     `_ATOM_TEXT` table is pinned against the client's table through these
//     fixtures (tests/test_note_citation_text.py reads them);
//   - `leafSpans`: every leaf that reads as text, so the Python rail pins atom
//     positions too, not only text-node positions -- and each one's `atom`
//     identity from the client's citationAtomIdentity (null when it has none);
//   - `passages`: for the astral and hardBreak cases, cited passages with the ProseMirror
//     range textBetween gives them, so both rails pin the offset mapping INSIDE
//     a text node (positions count UTF-16 units; Python counts code points).
//
// ⛔ THE SCHEMA BELOW IS A HAND COPY OF THE APP'S, AND IT WAS WRONG ONCE: it
// declared attachmentChip INLINE while the app declares it a BLOCK atom (no
// case used it, so nothing noticed). askCitation.schemaParity.test.js now
// re-parses every fixture under getSchema(buildExtensions()) and requires the
// same size and text, so this copy cannot drift silently again.
const path = require('path')
const { pathToFileURL } = require('url')
const { Schema, Node } = require('prosemirror-model')

const ASK_CITATION_MODULE = path.resolve(__dirname, '../app/src/pages/journal-2-0/lib/askCitation.js')

const schema = new Schema({
  nodes: {
    doc: { content: 'block+' },
    paragraph: { group: 'block', content: 'inline*', toDOM: () => ['p', 0] },
    heading: { group: 'block', content: 'inline*', attrs: { level: { default: 1 } }, toDOM: () => ['h1', 0] },
    codeBlock: { group: 'block', content: 'text*', marks: '', code: true, toDOM: () => ['pre', ['code', 0]] },
    blockquote: { group: 'block', content: 'block+', toDOM: () => ['blockquote', 0] },
    bulletList: { group: 'block', content: 'listItem+', toDOM: () => ['ul', 0] },
    listItem: { content: 'paragraph block*', toDOM: () => ['li', 0] },
    table: { group: 'block', content: 'tableRow+', toDOM: () => ['table', ['tbody', 0]] },
    tableRow: { content: 'tableCell*', toDOM: () => ['tr', 0] },
    tableCell: { content: 'block+', toDOM: () => ['td', 0] },
    text: { group: 'inline' },
    hardBreak: { group: 'inline', inline: true, selectable: false, toDOM: () => ['br'] },
    noteLink: { group: 'inline', inline: true, atom: true, attrs: { noteId: { default: null } }, toDOM: () => ['span'] },
    attachmentChip: { group: 'block', atom: true, attrs: { href: { default: null }, name: { default: 'file' }, size: { default: null } }, toDOM: () => ['a'] },
    documentExcerpt: { group: 'block', atom: true, attrs: { excerptId: { default: null } }, toDOM: () => ['div'] },
    widgetEmbed: { group: 'block', atom: true, attrs: { widgetId: { default: null }, searchText: { default: null }, capturedAt: { default: null }, embedId: { default: null } }, toDOM: () => ['div'] },
    askInsert: { group: 'block', content: 'block+', toDOM: () => ['div', 0] },
    askCitation: { group: 'inline', inline: true, atom: true, attrs: { n: { default: null } }, toDOM: () => ['span'] },
    // Wave 5 (mathNodes.js): formulas are leaves holding their LaTeX in `latex`.
    inlineMath: { group: 'inline', inline: true, atom: true, attrs: { latex: { default: '' } }, toDOM: () => ['span'] },
    blockMath: { group: 'block', atom: true, attrs: { latex: { default: '' } }, toDOM: () => ['div'] },
    // Wave 6 (imageFigureNode.js): an image is a block leaf that reads as
    // nothing; its CAPTION is a textblock inside the figure container.
    image: { group: 'block', atom: true, attrs: { src: { default: null }, alt: { default: null }, align: { default: null } }, toDOM: () => ['img'] },
    imageFigure: { group: 'block', content: 'image imageCaption', toDOM: () => ['figure', 0] },
    imageCaption: { content: 'inline*', toDOM: () => ['figcaption', 0] },
  },
  marks: { bold: { toDOM: () => ['strong', 0] }, italic: { toDOM: () => ['em', 0] }, link: { attrs: { href: { default: '' } }, toDOM: () => ['a', 0] },
    // Wave 5 (textColor.js): a palette NAME, never a colour value.
    highlight: { attrs: { color: { default: null } }, toDOM: () => ['mark', 0] },
    textColor: { attrs: { color: { default: null } }, toDOM: () => ['span', 0] } },
})

const t = (text, marks) => (marks ? { type: 'text', text, marks: marks.map((m) => ({ type: m })) } : { type: 'text', text })
const inl = (c) => c.map((x) => (typeof x === 'string' ? t(x) : x))
const p = (...c) => (c.length ? { type: 'paragraph', content: inl(c) } : { type: 'paragraph' })
const doc = (...c) => ({ type: 'doc', content: c })
// An atom's IDENTITY attr is optional here on purpose: the cases without one
// are the controls that must carry no identity on either side.
const CHIP = (name = 'q3-filing.pdf', href) => ({ type: 'attachmentChip',
  attrs: href === undefined ? { name } : { name, href } })
const WIDGET = (searchText, capturedAt, embedId) => ({ type: 'widgetEmbed',
  attrs: { widgetId: 'chart', searchText: searchText ?? null, ...(capturedAt === undefined ? {} : { capturedAt }),
    ...(embedId === undefined ? {} : { embedId }) } })
const EXCERPT = (excerptId) => ({ type: 'documentExcerpt', attrs: { excerptId } })
const BR = { type: 'hardBreak' }
const MATH = (latex) => ({ type: 'inlineMath', attrs: { latex } })
const BMATH = (latex) => ({ type: 'blockMath', attrs: { latex } })
const IMG = (alt, align) => ({ type: 'image', attrs: { src: '/api/j2/notes/n1/images/a.png', alt, ...(align ? { align } : {}) } })

const CASES = {
  // ── text, marks, blocks, lists, quotes, ask inserts ──
  simple: {type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'Hello world.'}]}]},
  markBoundary: {type:'doc',content:[{type:'paragraph',content:[
    {type:'text',text:'Management expects '},
    {type:'text',text:'gross margins',marks:[{type:'bold'}]},
    {type:'text',text:' to normalize lower.'}]}]},
  adjacentMarks: {type:'doc',content:[{type:'paragraph',content:[
    {type:'text',text:'a'},
    {type:'text',text:'b',marks:[{type:'bold'}]},
    {type:'text',text:'c',marks:[{type:'italic'}]},
    {type:'text',text:'d',marks:[{type:'bold'},{type:'italic'}]},
    {type:'text',text:'e'}]}]},
  twoParas: {type:'doc',content:[
    {type:'paragraph',content:[{type:'text',text:'First para.'}]},
    {type:'paragraph',content:[{type:'text',text:'Second para.'}]}]},
  headingAndPara: {type:'doc',content:[
    {type:'heading',attrs:{level:2},content:[{type:'text',text:'NVDA Thesis'}]},
    {type:'paragraph',content:[{type:'text',text:'Margins normalize.'}]}]},
  nestedList: {type:'doc',content:[
    {type:'paragraph',content:[{type:'text',text:'Risks:'}]},
    {type:'bulletList',content:[
      {type:'listItem',content:[{type:'paragraph',content:[{type:'text',text:'China exposure'}]}]},
      {type:'listItem',content:[{type:'paragraph',content:[{type:'text',text:'Customer concentration'}]}]}]}]},
  blockquote: {type:'doc',content:[
    {type:'blockquote',content:[{type:'paragraph',content:[{type:'text',text:'Quoted claim.'}]}]},
    {type:'paragraph',content:[{type:'text',text:'After.'}]}]},
  linkAcross: {type:'doc',content:[{type:'paragraph',content:[
    {type:'text',text:'see '},
    {type:'text',text:'the filing',marks:[{type:'link',attrs:{href:'https://x'}}]},
    {type:'text',text:' for detail'}]}]},
  duplicatePhrase: {type:'doc',content:[
    {type:'paragraph',content:[{type:'text',text:'Revenue was strong.'}]},
    {type:'paragraph',content:[{type:'text',text:'Revenue guidance was raised.'}]}]},
  askCitationChip: {type:'doc',content:[{type:'paragraph',content:[
    {type:'text',text:'Margins fell '},
    {type:'askCitation',attrs:{n:1}},
    {type:'text',text:' in Q3.'}]}]},
  askInsertBlock: {type:'doc',content:[
    {type:'paragraph',content:[{type:'text',text:'My own view.'}]},
    {type:'askInsert',content:[
      {type:'paragraph',content:[
        {type:'text',text:'Inserted answer '},
        {type:'askCitation',attrs:{n:1}},
        {type:'text',text:' here.'}]}]},
    {type:'paragraph',content:[{type:'text',text:'After.'}]}]},
  // ── empty textblocks: textBetween emits a separator for EACH ──
  emptyParaStart: doc(p(), p('First.'), p('Second.')),
  emptyParaMiddle: doc(p('First.'), p(), p('Second.')),
  emptyParaEnd: doc(p('First.'), p('Second.'), p()),
  consecutiveEmpty: doc(p('First.'), p(), p(), p(), p('Second.')),
  onlyEmpty: doc(p()),
  twoEmpty: doc(p(), p()),
  emptyHeading: doc(p('Intro.'), { type: 'heading', attrs: { level: 2 } }, p('Body text.')),
  emptyListItem: doc(p('Risks:'), { type: 'bulletList', content: [
    { type: 'listItem', content: [p('China exposure')] },
    { type: 'listItem', content: [p()] },
    { type: 'listItem', content: [p('Customer concentration')] }] }),
  emptyBlockquoteChild: doc({ type: 'blockquote', content: [p(), p('Quoted claim.')] }, p('After.')),
  emptyTableCells: doc({ type: 'table', content: [
    { type: 'tableRow', content: [{ type: 'tableCell', content: [p('A1')] }, { type: 'tableCell', content: [p()] }] },
    { type: 'tableRow', content: [{ type: 'tableCell', content: [p()] }, { type: 'tableCell', content: [p('B2')] }] }] }),
  emptyCodeBlock: doc(p('Before.'), { type: 'codeBlock' }, p('After.')),
  // ── block atoms that read as text (textBetween's leafText argument) ──
  chipMiddle: doc(p('Before.'), CHIP(), p('After.')),
  chipFirst: doc(CHIP(), p('After.')),
  chipLast: doc(p('Before.'), CHIP()),
  excerptMiddle: doc(p('Before.'), { type: 'documentExcerpt', attrs: { excerptId: 'ex1' } }, p('After.')),
  widgetMiddle: doc(p('Before.'), WIDGET('NVDA daily chart'), p('After.')),
  widgetNoSearchText: doc(p('Before.'), WIDGET(null), p('After.')),
  chipThenBlockquote: doc(CHIP(), { type: 'blockquote', content: [p('Quoted.')] }),
  twoAtomsInARow: doc(p('Before.'), CHIP('a.pdf'), WIDGET('NVDA daily chart'), p('After.')),
  // ── inline leaves that read as NOTHING on both sides (controls) ──
  hardBreakInline: doc(p('line one', { type: 'hardBreak' }, 'line two')),
  noteLinkInline: doc(p('See ', { type: 'noteLink', attrs: { noteId: 'n2' } }, ' for more.')),
  realisticMixed: doc(
    { type: 'heading', attrs: { level: 2 }, content: [t('NVDA Thesis')] },
    p(),
    p('Management expects ', t('gross margins', ['bold']), ' to normalize.'),
    CHIP('q3-10q.pdf'),
    p('Guidance was raised for Q4.'),
    p(),
    WIDGET('NVDA daily chart, 50/200 SMA'),
    p('Conclusion: hold.')),
  // ── astral characters: ProseMirror counts UTF-16 units, so an emoji is TWO
  //    positions -- a count of code points puts everything after it early ──
  astralBefore: doc(p('\u{1F525} Margins fell sharply.'), p('Second.')),
  astralInside: doc(p('Revenue \u{1F525} grew \u{1D538} fast.')),
  astralAfter: doc(p('Guidance raised \u{1F525}'), p('Next \u{1D538}')),
  astralAcrossMarks: doc(p('Up ', t('\u{1F525}\u{1F525}', ['bold']), ' today \u{1D538}')),
  astralThenExcerpts: doc(p('\u{1F680} NVDA thesis'),
    { type: 'documentExcerpt', attrs: { excerptId: 'ex1' } },
    { type: 'documentExcerpt', attrs: { excerptId: 'ex2' } },
    p('After.')),
  astralThenChip: doc(p('\u{1F525} hot'), CHIP('q3.pdf'), p('After \u{1D538}.')),
  // ── atom IDENTITY (review-parity N1): every kind that carries one, beside
  //    look-alikes that read the same and differ only by identity ──
  identityAtoms: doc(p('Thesis.'),
    CHIP('q3.pdf', '/api/j2/notes/n1/attachments/9f2c/q3.pdf'),
    CHIP('q3.pdf', '/api/j2/notes/n1/attachments/41ab/q3.pdf'),
    EXCERPT('ex1'), EXCERPT('ex2'),
    WIDGET('NVDA daily chart', '2026-09-01T14:00:00.000Z'),
    WIDGET('NVDA daily chart', '2026-09-02T14:00:00.000Z'),
    p('After.')),
  identityAttrsEmpty: doc(p('Before.'), CHIP('q3.pdf', ''), EXCERPT(''), WIDGET('NVDA', ''), p('After.')),
  // ── charts exactly as the REAL chartInsertNodes builds them (rereview2
  //    R2-1; Wave 4): every chart of one /mtf or /compare insert shares ONE
  //    capturedAt, and each carries its OWN embedId. This node module cannot
  //    load widgetEmbedCore.js (extension-less imports), so these are
  //    literals -- askCitation.parity.test.js calls the real builder under a
  //    frozen clock and a scripted randomUUID and requires it to produce
  //    exactly these nodes (projected to the attrs citation text and identity
  //    read). ──
  chartsMtfThenSingle: doc(p('NVDA thesis.'),
    WIDGET('[chart: NVDA D]', '2026-09-01T14:00:00.000Z', 'e-mtf-d'),
    WIDGET('[chart: NVDA 1h]', '2026-09-01T14:00:00.000Z', 'e-mtf-1h'),
    WIDGET('[chart: NVDA 15m]', '2026-09-01T14:00:00.000Z', 'e-mtf-15m'),
    p('Later.'),
    WIDGET('[chart: AMD D]', '2026-09-01T14:05:00.000Z', 'e-amd-d')),
  chartsCompare: doc(p('Before the print.'),
    WIDGET('[chart: NVDA D]', '2026-09-02T14:00:00.000Z', 'e-cmp-before'),
    WIDGET('[chart: NVDA D]', '2026-09-02T14:00:00.000Z', 'e-cmp-after'),
    p('After.')),
  // ── the same inserts as stored BEFORE embedId existed: every chart of one
  //    insert shares widgetId|capturedAt, so ONE identity. The parity rail
  //    requires these to be the charts above minus embedId. ──
  chartsMtfThenSingleLegacy: doc(p('NVDA thesis.'),
    WIDGET('[chart: NVDA D]', '2026-09-01T14:00:00.000Z'),
    WIDGET('[chart: NVDA 1h]', '2026-09-01T14:00:00.000Z'),
    WIDGET('[chart: NVDA 15m]', '2026-09-01T14:00:00.000Z'),
    p('Later.'),
    WIDGET('[chart: AMD D]', '2026-09-01T14:05:00.000Z')),
  chartsCompareLegacy: doc(p('Before the print.'),
    WIDGET('[chart: NVDA D]', '2026-09-02T14:00:00.000Z'),
    WIDGET('[chart: NVDA D]', '2026-09-02T14:00:00.000Z'),
    p('After.')),
  // ── hardBreak reads as ONE space (Wave 4): inside, doubled, first and last
  //    in a paragraph, and beside a mark -- one position each, no separator ──
  hardBreaks: doc(
    p('Guidance', BR, 'raised', BR, BR, t('again', ['bold'])),
    p(BR, 'lead'),
    p('tail', BR)),
  // ── a block longer than the 400-character snippet cap (Wave 4), with astral
  //    characters inside the first 400 so code points and UTF-16 units differ
  //    exactly where the cut falls ──
  longBlock: doc(p('Intro.'),
    p(`Guidance \u{1F525} raised \u{1D538}: ${'the quarter closed with margins widening across every segment. '.repeat(8)}Final word.`),
    p('After.')),
  // ── formulas read as their LaTeX (Wave 5): an INLINE one mid-sentence (no
  //    separator, one position however long), a BLOCK one on its own line, an
  //    astral character inside the LaTeX (still one position), and EMPTY ones,
  //    which read as nothing and emit no separator on either side ──
  mathInline: doc(p('Area is ', MATH('\\pi r^2'), ' exactly.')),
  mathBlock: doc(p('Before.'), BMATH('E = mc^2'), p('After.')),
  mathAstral: doc(p('Set ', MATH('\u{1D538} \\subset \\mathbb{R}'), ' holds.'), BMATH('\\sum_{i=1}^{n} x_i')),
  mathEmpty: doc(p('A', MATH(''), 'B'), BMATH(''), p('C')),
  // ── colour and highlight are MARKS (Wave 5): they split text nodes and add
  //    nothing -- a passage across them reads and maps exactly as plain text ──
  colouredMarks: doc(p('Guidance ',
    { type: 'text', text: 'raised', marks: [{ type: 'highlight', attrs: { color: 'yellow' } }] },
    ' and ',
    { type: 'text', text: 'margins', marks: [{ type: 'textColor', attrs: { color: 'red' } }, { type: 'bold' }] },
    ' widened', { type: 'text', text: ' sharply', marks: [{ type: 'highlight', attrs: { color: null } }] }, '.')),
  // ── an image's caption is TEXT (wave 6): its own textblock inside the figure
  //    -- one separator before it like any textblock -- while the image beside
  //    it reads as nothing and takes one position. An EMPTY caption still emits
  //    its separator (it is a textblock). ──
  imageFigure: doc(p('Before.'),
    { type: 'imageFigure', content: [IMG('NVDA daily', 'center'),
      { type: 'imageCaption', content: [t('NVDA breakout, '), t('day 3', ['bold'])] }] },
    p('After.')),
  imageFigureEmptyCaption: doc(p('A.'),
    { type: 'imageFigure', content: [IMG('chart'), { type: 'imageCaption' }] }, p('B.')),
}

// Passages cited in the astral cases -- before, inside, across a mark, and
// after an astral character -- and across the hardBreak case's line breaks.
// Each must occur ONCE in its note. `passages`
// records the tightest range whose textBetween IS the passage, found by brute
// force over textBetween itself -- never by the walker the rails test.
const PASSAGES = {
  astralBefore: ['Margins fell', 'sharply.', 'Second.'],
  astralInside: ['Revenue', '\u{1F525} grew \u{1D538}', 'grew', 'fast.'],
  astralAfter: ['Guidance raised', '\u{1F525}', 'Next', '\u{1D538}'],
  astralAcrossMarks: ['Up', '\u{1F525} today', 'today \u{1D538}'],
  astralThenExcerpts: ['NVDA thesis', 'After.'],
  astralThenChip: ['hot', '[file: q3.pdf]', 'After \u{1D538}.'],
  hardBreaks: ['Guidance raised', 'raised  again', 'lead', 'tail'],
  mathInline: ['is \\pi r^2 exactly', '\\pi r^2', 'exactly.'],
  mathBlock: ['E = mc^2', 'After.'],
  // A formula is ONE position, so a passage holds a whole formula or none of
  // it -- never half its LaTeX.
  mathAstral: ['Set \u{1D538} \\subset \\mathbb{R} holds.', 'holds.', '\\sum_{i=1}^{n} x_i'],
  colouredMarks: ['raised and margins widened sharply', 'margins'],
  imageFigure: ['NVDA breakout, day 3', 'day 3', 'After.'],
}

function passageRange(d, passage, leafText) {
  const size = d.content.size
  let best = null
  for (let from = 0; from < size; from++) {
    for (let to = from + 1; to <= size; to++) {
      if (d.textBetween(from, to, '\n', leafText) !== passage) continue
      if (!best || from > best.pm_from || (from === best.pm_from && to < best.pm_to)) best = { pm_from: from, pm_to: to }
    }
  }
  if (!best) throw new Error(`passage not found: ${JSON.stringify(passage)}`)
  return best
}

;(async () => {
  const { citationLeafText, citationAtomIdentity } = await import(pathToFileURL(ASK_CITATION_MODULE).href)
  const out = {}
  for (const [name, json] of Object.entries(CASES)) {
    const d = Node.fromJSON(schema, json)
    d.check()
    const textSpans = []
    const leafSpans = []
    d.descendants((node, pos) => {
      if (node.isText) textSpans.push({ pm_start: pos, pm_end: pos + node.nodeSize, text: node.text })
      else if (node.isLeaf && citationLeafText(node)) {
        // `atom` pins the Python `_ATOM_IDENTITY` table against the client's
        // citationAtomIdentity, the way `text` pins `_ATOM_TEXT`.
        const id = citationAtomIdentity(node)
        leafSpans.push({ pm_start: pos, pm_end: pos + node.nodeSize, text: citationLeafText(node),
          atom: id ? { type: node.type.name, id } : null })
      }
    })
    const text = d.textBetween(0, d.content.size, '\n', citationLeafText)
    const passages = (PASSAGES[name] || []).map((passage) => {
      if (text.split(passage).length !== 2) throw new Error(`${name}: passage must occur once: ${JSON.stringify(passage)}`)
      return { text: passage, ...passageRange(d, passage, citationLeafText) }
    })
    out[name] = { json, text, contentSize: d.content.size, textSpans, leafSpans, passages }
  }
  console.log(JSON.stringify(out, null, 1))
})()
