"""One-shot generator: turns the firm's YouTube channel (@unchartedtrtyy) public
uploads — the ones NOT already in the workshop sheet — into
api/services/education_channel_seed.py (SEED_VIDEOS_CHANNEL).

Input TSV/CSV: id,title,tab (from yt-dlp --flat-playlist over /videos + /streams).
Categories assigned by title heuristic. Already-seeded ids (in education_seed.py
SEED_VIDEOS) are skipped. Re-runnable.

Run:  python tools/gen_channel_seed.py tools/_channel_new.csv
"""
from __future__ import annotations

import csv
import sys

MINDSET = "Mindset & Psychology"
MARKET = "Market Analysis & Breadth"
SETUPS = "Setups & Strategies"
TECH = "Technical Analysis & Relative Strength"
RISK = "Risk & Trade Management"
SCAN = "Scanning, Watchlists & Stock Selection"
FLOW = "Options & Flow"
INTERVIEWS = "Interviews"
RECAPS = "Post-Market Recaps"
LIVE = "Live Sessions"


def categorize(title: str) -> str:
    t = (title or "").lower()
    if "interview" in t or "chat w/" in t or "chat with" in t:
        return INTERVIEWS
    if "post-market recap" in t or "post market recap" in t or "post-market" in t:
        return RECAPS
    if any(k in t for k in ("pre-market", "premarket", "pre market",
                            "live trading", "live stream", "livestream")):
        return LIVE
    if "alexjones" in t or "flow" in t or "options" in t:
        return FLOW
    if "scan" in t:
        return SCAN
    if "stop" in t or "risk" in t:
        return RISK
    if any(k in t for k in ("launchpad", "launch pad", "inside day", "breakdown",
                            "breakout", "pullback", "setup", "steup")):
        return SETUPS
    if any(k in t for k in ("relative strength", "ichimoku", "hourly", " ema",
                            "ema ", "moving average")):
        return TECH
    if "thought" in t or "you don" in t:
        return MINDSET
    if "review" in t:
        return MARKET
    if "stocks" in t or t.strip() == "stocks":
        return SCAN
    return MARKET


CAT_ORDER = [MINDSET, MARKET, SETUPS, TECH, RISK, SCAN, FLOW, INTERVIEWS, RECAPS, LIVE]


def main():
    if len(sys.argv) < 2:
        print("usage: python tools/gen_channel_seed.py <csv>")
        sys.exit(1)
    with open(sys.argv[1], encoding="utf-8-sig") as f:
        rows = list(csv.DictReader(f))

    try:
        from api.services.education_seed import SEED_VIDEOS
        already = {v["youtube_id"] for v in SEED_VIDEOS}
    except Exception:
        already = set()

    seen: dict[str, dict] = {}
    skipped = 0
    for i, r in enumerate(rows):
        yt = (r.get("id") or "").strip()
        title = (r.get("title") or "").strip()
        if not yt or len(yt) != 11 or yt in already or yt in seen:
            skipped += 1
            continue
        seen[yt] = {
            "youtube_id": yt,
            "title": title,
            "description": "",
            "category": categorize(title),
            "_idx": i,
        }

    # sort_order within category = channel order (newest first).
    by_cat: dict[str, list] = {}
    for v in seen.values():
        by_cat.setdefault(v["category"], []).append(v)
    out: list[dict] = []
    for cat, vids in by_cat.items():
        vids.sort(key=lambda v: v["_idx"])
        for order, v in enumerate(vids):
            out.append({
                "youtube_id": v["youtube_id"],
                "title": v["title"],
                "description": v["description"],
                "category": cat,
                "sort_order": order,
            })
    out.sort(key=lambda v: (CAT_ORDER.index(v["category"]), v["sort_order"]))

    _emit(out, len(rows), skipped, by_cat)


def _emit(videos, total, skipped, by_cat):
    lines = [
        '"""Seed library (channel) for The Desk → Videos.',
        "",
        "Generated by tools/gen_channel_seed.py from the firm's YouTube channel",
        "(@unchartedtrtyy) public uploads that are NOT in the workshop sheet.",
        "Consumed by education_service.ensure_default_videos() alongside SEED_VIDEOS.",
        "Idempotent: inserts only youtube_ids not already present. Do NOT hand-edit.",
        '"""',
        "from __future__ import annotations",
        "",
        "SEED_VIDEOS_CHANNEL: list[dict] = [",
    ]
    for v in videos:
        lines.append("    {")
        lines.append(f"        \"youtube_id\": {v['youtube_id']!r},")
        lines.append(f"        \"title\": {v['title']!r},")
        lines.append(f"        \"description\": {v['description']!r},")
        lines.append(f"        \"category\": {v['category']!r},")
        lines.append(f"        \"sort_order\": {v['sort_order']},")
        lines.append("    },")
    lines.append("]")
    lines.append("")
    with open("api/services/education_channel_seed.py", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Wrote api/services/education_channel_seed.py: {len(videos)} videos "
          f"(from {total} channel rows, {skipped} skipped/dupe)")
    for cat in CAT_ORDER:
        n = len(by_cat.get(cat, []))
        if n:
            print(f"  {n:>3}  {cat}")


if __name__ == "__main__":
    main()
