"""Wave K Slice 1 — the canonical note text + position map that citations
locate against.

WHY THIS IS NOT `body_plain`
----------------------------
`notes.extract_plain_text` (which writes `body_plain`, the FTS index) joins
every text node with a SPACE. That is correct for its job -- FTS5 tokenizes
on non-alphanumerics, so an extra space is invisible to search -- but it means
`body_plain` is NOT the text a member sees:

    <p>Management expects <strong>gross margins</strong> to normalize.</p>

    body_plain : "Management expects  gross margins  to normalize."
    rendered   : "Management expects gross margins to normalize."

Two extra spaces appear at every mark boundary (the node's own trailing space
plus the join). A character offset into `body_plain` therefore does not
address the rendered document, so `body_plain` cannot carry a citation
location. Slice 0 proved the consequence from the other direction: a quoted
phrase can genuinely exist in a note and still be unresolvable by string
search, because a mark boundary splits it across text nodes.

WHAT THIS IS INSTEAD
--------------------
ProseMirror's own `textBetween(0, size, blockSeparator)` semantics, derived
from the real `prosemirror-model` package rather than from a reading of the
spec (see tests/test_note_citation_text.py, which pins this implementation
against fixtures generated by the library itself):

  - a text node contributes its characters, and nothing else
  - marks contribute NOTHING -- bold/italic/link boundaries are invisible
  - a block boundary contributes a single "\n"
  - atoms/leaves contribute their placeholder text

and alongside the text, a SPAN MAP giving each text node's ProseMirror
position. A citation therefore addresses `{from, to}` in ProseMirror
coordinates, which the editor can select and scroll to directly, and which
are immune to mark boundaries by construction.

TWO REPRESENTATIONS, ON PURPOSE
-------------------------------
`body_plain` finds CANDIDATE NOTES (tokenized, whitespace-insensitive).
This module locates the PASSAGE INSIDE one (offset-exact, mark-transparent).
They are different jobs and must not be unified: collapsing them would either
break Wave A search or reintroduce the offset error above. What §7 forbids is
three DIFFERENT normalizations across location-creation and
citation-resolution -- and this module is the single one both sides share.

POSITION DRIFT IS REAL, AND EPHEMERAL DOES NOT REMOVE IT
--------------------------------------------------------
My first reading of this was wrong and is corrected here rather than quietly
replaced: an Ask citation outlives RETRIEVAL, not the response. The note can
be edited or autosaved between the moment retrieval computed {from,to} and
the moment the member clicks that citation in the finished answer, and stale
positions frequently stay SYNTACTICALLY valid while addressing different
text. See `fingerprint` (the fast path) and `verify` (the actual guarantee).
"""
from __future__ import annotations

from typing import Any

# Placeholder text for atom nodes, mirroring notes.extract_plain_text so the
# two agree on what a non-text node "reads as". These occupy ONE ProseMirror
# position each regardless of placeholder length -- the map records that.
_ATOM_TEXT = {
    "attachmentChip": lambda a: f"[file: {a.get('name') or 'file'}]",
    "documentExcerpt": lambda a: "[excerpt]",
    "widgetEmbed": lambda a: (a.get("searchText") if isinstance(a.get("searchText"), str)
                              and a.get("searchText") else "[widget]"),
}

# Node types that are leaves in the schema (nodeSize 1, no content walked).
_LEAF_TYPES = frozenset({
    "attachmentChip", "documentExcerpt", "widgetEmbed", "videoTimestamp",
    "horizontalRule", "image", "hardBreak", "financialFact", "noteLink",
})

BLOCK_SEPARATOR = "\n"


def flatten(doc: dict[str, Any] | None) -> dict[str, Any]:
    """Canonical citation text + ProseMirror span map for a TipTap doc.

    Returns ``{"text": str, "spans": [{"flat_start", "flat_end", "pm_start",
    "pm_end", "is_atom"}]}``. Spans are in document order and cover every
    addressable run of text; the block separators between them are part of
    ``text`` but belong to no span, which is exactly why the two coordinate
    systems need an explicit map rather than a constant offset.
    """
    parts: list[str] = []
    spans: list[dict[str, Any]] = []
    state = {"flat": 0, "pending_sep": False}

    def emit(text: str, pm_start: int, pm_end: int, is_atom: bool) -> None:
        if not text:
            return
        if state["pending_sep"] and parts:
            parts.append(BLOCK_SEPARATOR)
            state["flat"] += len(BLOCK_SEPARATOR)
        state["pending_sep"] = False
        start = state["flat"]
        parts.append(text)
        state["flat"] += len(text)
        spans.append({
            "flat_start": start, "flat_end": state["flat"],
            "pm_start": pm_start, "pm_end": pm_end, "is_atom": is_atom,
        })

    def walk(node: Any, pos: int) -> int:
        """Returns the position immediately AFTER `node`."""
        if not isinstance(node, dict):
            return pos
        ntype = node.get("type")
        attrs = node.get("attrs")
        if not isinstance(attrs, dict):
            attrs = {}

        if ntype == "text":
            t = node.get("text")
            if isinstance(t, str) and t:
                emit(t, pos, pos + len(t), False)
                return pos + len(t)
            return pos

        if ntype in _LEAF_TYPES:
            maker = _ATOM_TEXT.get(ntype)
            if maker is not None:
                # A leaf occupies exactly ONE ProseMirror position no matter
                # how long its placeholder reads.
                emit(maker(attrs), pos, pos + 1, True)
            return pos + 1

        # Container: 1 for the open token, content, 1 for the close token.
        inner = pos + 1
        children = node.get("content") or []
        if isinstance(children, list):
            for child in children:
                inner = walk(child, inner)
        after = inner + 1
        if _is_block(ntype):
            state["pending_sep"] = True
        return after

    if not isinstance(doc, dict):
        return {"text": "", "spans": [], "content_size": 0}

    # The doc node itself is not addressable; its children start at 0. The
    # final position IS ProseMirror's `doc.content.size`.
    pos = 0
    for child in (doc.get("content") or []):
        pos = walk(child, pos)
    return {"text": "".join(parts), "spans": spans, "content_size": pos}


def _is_block(ntype: str | None) -> bool:
    """Block-level containers get a separator after them. Inline containers
    do not -- that distinction is the whole reason marks are invisible here."""
    return ntype not in (None, "text") and ntype not in _LEAF_TYPES


def pm_range(flat_start: int, flat_end: int, spans: list[dict[str, Any]]) -> dict[str, int] | None:
    """Map a half-open range in the canonical text to ProseMirror positions.

    Returns ``{"from", "to"}`` or None when the range addresses no text (for
    example a range that falls entirely inside a block separator). A range
    spanning several text nodes -- which is precisely the mark-boundary case
    Slice 0 proved unresolvable by string search -- maps cleanly, because
    ProseMirror positions do not know marks exist.
    """
    if flat_end <= flat_start:
        return None
    pm_from = pm_to = None
    for s in spans:
        if pm_from is None and s["flat_start"] <= flat_start < s["flat_end"]:
            if s["is_atom"]:
                pm_from = s["pm_start"]
            else:
                pm_from = s["pm_start"] + (flat_start - s["flat_start"])
        if s["flat_start"] < flat_end <= s["flat_end"]:
            if s["is_atom"]:
                pm_to = s["pm_end"]
            else:
                pm_to = s["pm_start"] + (flat_end - s["flat_start"])
    if pm_from is None or pm_to is None or pm_to <= pm_from:
        return None
    return {"from": pm_from, "to": pm_to}


def fingerprint(doc: dict[str, Any] | None) -> str:
    """A cheap token that changes if and only if a stored ProseMirror position
    could have stopped meaning what it meant.

    Composition measured against the real prosemirror-model, not reasoned:

      text alone           too weak   -- wrapping a paragraph in a blockquote
                                        leaves the text identical and shifts
                                        every later position (size 13 -> 15)
      text + span list     too strict -- adding a bold mark SPLITS a text node
                                        ([1,8] -> [1,3,8]) without invalidating
                                        any position, so this would degrade a
                                        citation on every formatting edit
      text + content_size  exact      -- catches the blockquote wrap, ignores
                                        the mark split

    Both runtimes compute it cheaply: the backend from `flatten`, the frontend
    from `doc.textBetween(0, size, '\n')` and `doc.content.size` -- the very
    primitives the cross-runtime equivalence rail already pins together.

    This is the FAST PATH, not the guarantee. `verify` is the guarantee.
    """
    import hashlib
    flat = flatten(doc)
    digest = hashlib.sha256(flat["text"].encode("utf-8")).hexdigest()[:16]
    return f"{digest}:{flat['content_size']}"


def verify(doc: dict[str, Any] | None, pm_from: int, pm_to: int, snippet: str) -> bool:
    """Does `snippet` still live at exactly [pm_from, pm_to) in this doc?

    THE ACTUAL GUARANTEE. A fingerprint can in principle be fooled (unwrap one
    blockquote, wrap another: net size unchanged, text unchanged, positions
    between them shifted). Rather than chase ever-more-precise fingerprints,
    the navigator re-reads the text at the range it is about to jump to and
    refuses if it is not the cited passage. Complete regardless of how the
    fingerprint was computed.
    """
    if not snippet or pm_to <= pm_from:
        return False
    flat = flatten(doc)
    lo = hi = None
    for s in flat["spans"]:
        if s["is_atom"]:
            continue
        if s["pm_start"] <= pm_from < s["pm_end"]:
            lo = s["flat_start"] + (pm_from - s["pm_start"])
        if s["pm_start"] < pm_to <= s["pm_end"]:
            hi = s["flat_start"] + (pm_to - s["pm_start"])
    if lo is None or hi is None or hi <= lo:
        return False
    return flat["text"][lo:hi] == snippet


def locate(doc: dict[str, Any] | None, needle: str) -> list[dict[str, Any]]:
    """Every occurrence of `needle` in a note's canonical text, as ProseMirror
    ranges. Ambiguity is REPORTED, never resolved by picking the first hit --
    Slice 0 recorded that silent first-match behaviour as a defect.
    """
    if not needle:
        return []
    flat = flatten(doc)
    text, spans = flat["text"], flat["spans"]
    out: list[dict[str, Any]] = []
    start = text.find(needle)
    while start != -1:
        rng = pm_range(start, start + len(needle), spans)
        if rng is not None:
            out.append({"flat_start": start, "flat_end": start + len(needle), **rng})
        start = text.find(needle, start + 1)
    return out


# ── Citation validity ────────────────────────────────────────────────────────
# Internal names. Member-facing copy stays simple ("open the note").
VALID_EXACT = "valid_exact"            # fingerprint matched AND text verified
RERESOLVED_EXACT = "reresolved_exact"  # note changed; re-found unambiguously
VALID_NOTE_ONLY = "valid_note_only"    # can open the note, not the passage
DEGRADED = "degraded"                  # ambiguous or gone; no passage claim

# The only states in which a caller may claim an exact passage jump. Anything
# else opens the note WITHOUT pretending precise navigation succeeded.
PRECISE_STATES = frozenset({VALID_EXACT, RERESOLVED_EXACT})


def resolve_note_citation(doc, pm_from, pm_to, snippet, expected_fingerprint,
                          prefix: str = "", suffix: str = ""):
    """Decide where a NOTE citation may navigate, given the note's CURRENT doc.

    The requirement is one-directional: a failed precise citation is fine, a
    confident jump to the wrong passage is not. Every path that cannot PROVE
    it is looking at the cited passage returns a non-precise state.

        1. fingerprint matches AND the text at [from,to) is still the snippet
           -> VALID_EXACT, original positions
        2. otherwise re-resolve the snippet against the CURRENT canonical text
           - exactly one occurrence               -> RERESOLVED_EXACT
           - several, but quote context picks one -> RERESOLVED_EXACT
           - several and context cannot decide    -> VALID_NOTE_ONLY (never the
             first occurrence: Slice 0 recorded that silent choice as a defect)
           - none                                 -> DEGRADED
    """
    if expected_fingerprint and fingerprint(doc) == expected_fingerprint:
        if verify(doc, pm_from, pm_to, snippet):
            return {"state": VALID_EXACT, "from": pm_from, "to": pm_to}
        # Fingerprint agreed but the text did not. Trust the text.

    hits = locate(doc, snippet)
    if len(hits) == 1:
        return {"state": RERESOLVED_EXACT, "from": hits[0]["from"], "to": hits[0]["to"]}
    if len(hits) > 1 and (prefix or suffix):
        ctx = locate(doc, f"{prefix}{snippet}{suffix}")
        if len(ctx) == 1:
            only = ctx[0]
            inner = pm_range(only["flat_start"] + len(prefix),
                             only["flat_end"] - len(suffix),
                             flatten(doc)["spans"])
            if inner:
                return {"state": RERESOLVED_EXACT, **inner}
    if hits:
        return {"state": VALID_NOTE_ONLY, "from": None, "to": None,
                "reason": f"{len(hits)} occurrences; cannot disambiguate"}
    return {"state": DEGRADED, "from": None, "to": None,
            "reason": "cited passage is no longer in this note"}
