"""Wave K Slice 1 — the canonical note text + position map that citations
locate against.

WHY THIS IS NOT `body_plain`
----------------------------
`notes.extract_plain_text` (which writes `body_plain`, the FTS index) joins
every text node with a SPACE. That is correct for its job -- FTS5 tokenizes
on non-alphanumerics, so an extra space is invisible to search -- but it means
`body_plain` is NOT the text a member sees:

    <p>Management expects <strong>gross margins</strong> to normalize.</p>

    body_plain : "Management expects  gross margins  to normalize."
    rendered   : "Management expects gross margins to normalize."

Two extra spaces appear at every mark boundary (the node's own trailing space
plus the join). A character offset into `body_plain` therefore does not
address the rendered document, so `body_plain` cannot carry a citation
location. Slice 0 proved the consequence from the other direction: a quoted
phrase can genuinely exist in a note and still be unresolvable by string
search, because a mark boundary splits it across text nodes.

WHAT THIS IS INSTEAD
--------------------
ProseMirror's own `textBetween(0, size, "\n", leafText)` semantics, derived
from the real `prosemirror-model` package rather than from a reading of the
spec (see tests/test_note_citation_text.py, which pins this implementation
against fixtures generated by the library itself):

  - a text node contributes its characters, and nothing else
  - marks contribute NOTHING -- bold/italic/link boundaries are invisible
  - R1: every TEXTBLOCK (`_TEXTBLOCK_TYPES`) is preceded by one "\n", an
    EMPTY one included -- two empty paragraphs read as two separators --
    except the very first node in the document to qualify for one
  - R2: a container that is not a textblock (blockquote, list, list item,
    table, table cell, askInsert, ...) never adds a separator of its own
  - R3: a BLOCK leaf is preceded by one "\n" only when it reads as text
    (`_ATOM_TEXT`); a block leaf that reads as nothing (image, rule, fact)
    adds nothing, and an INLINE leaf (`_INLINE_LEAF_TYPES`) never does
  - R4: a leaf reads as its `_ATOM_TEXT` placeholder, or as "" -- and it
    occupies ONE position however long that is. The client supplies the
    same table to the same primitive as textBetween's `leafText` ARGUMENT
    (askCitation.js::citationLeafText), never as a schema `leafText`: the
    argument overrides any schema leafText, and leaves the editor's
    textContent and plain-text clipboard untouched

That is prosemirror-model's Fragment.textBetween, verbatim:

    if (node.isBlock && (node.isLeaf && nodeText || node.isTextblock) && blockSeparator) {
        if (first) first = false;
        else text += blockSeparator;
    }

and alongside the text, a SPAN MAP giving each text node's ProseMirror
position. A citation therefore addresses `{from, to}` in ProseMirror
coordinates, which the editor can select and scroll to directly, and which
are immune to mark boundaries by construction.

POSITIONS COUNT UTF-16 UNITS; THE TEXT STAYS A PYTHON STR
---------------------------------------------------------
ProseMirror sizes a text node by JavaScript string length -- UTF-16 code
units -- so an astral character (most emoji, U+1F525) is TWO positions where
Python sees ONE character. Every span's `pm_start`/`pm_end` and
`content_size` are in UTF-16 units; `flat_start`/`flat_end` stay code-point
offsets into `text`; and an offset INSIDE a text node crosses between the two
through that node's own characters (`_pm_at`, `_flat_at`). Counting code
points put every position after an emoji one short per emoji.

TWO REPRESENTATIONS, ON PURPOSE
-------------------------------
`body_plain` finds CANDIDATE NOTES (tokenized, whitespace-insensitive).
This module locates the PASSAGE INSIDE one (offset-exact, mark-transparent).
They are different jobs and must not be unified: collapsing them would either
break Wave A search or reintroduce the offset error above. What §7 forbids is
three DIFFERENT normalizations across location-creation and
citation-resolution -- and this module is the single one both sides share.

POSITION DRIFT IS REAL, AND EPHEMERAL DOES NOT REMOVE IT
--------------------------------------------------------
My first reading of this was wrong and is corrected here rather than quietly
replaced: an Ask citation outlives RETRIEVAL, not the response. The note can
be edited or autosaved between the moment retrieval computed {from,to} and
the moment the member clicks that citation in the finished answer, and stale
positions frequently stay SYNTACTICALLY valid while addressing different
text. See `fingerprint` (the fast path) and `verify` (the actual guarantee).
"""
from __future__ import annotations

from bisect import bisect_left, bisect_right
from collections import Counter
from functools import cached_property
from typing import Any

# Placeholder text for atom nodes, mirroring notes.extract_plain_text so the
# two agree on what a non-text node "reads as". These occupy ONE ProseMirror
# position each regardless of placeholder length -- the map records that.
# The client's copy is askCitation.js::citationLeafText; the two are pinned
# together through tests/fixtures_pm_citation_text.json (the generator calls
# the client function) and askCitation.schemaParity.test.js (reads these keys).
# KEEP them: with the placeholders removed, Ask Current Note retrieval answered
# "no_answer" to 2 of 3 questions about an attached filing and an embedded
# chart (closeout-parity probe, 2026-09-23) -- an atom that reads as nothing
# cannot be asked about.
_ATOM_TEXT = {
    "attachmentChip": lambda a: f"[file: {a.get('name') or 'file'}]",
    "documentExcerpt": lambda a: "[excerpt]",
    "widgetEmbed": lambda a: (a.get("searchText") if isinstance(a.get("searchText"), str)
                              and a.get("searchText") else "[widget]"),
}


def _nonempty(v: Any) -> str | None:
    return v if isinstance(v, str) and v else None


def _widget_identity(a: dict[str, Any]) -> str | None:
    own = _nonempty(a.get("embedId"))
    if own:
        return own
    kind, at = _nonempty(a.get("widgetId")), _nonempty(a.get("capturedAt"))
    return f"{kind}|{at}" if kind and at else None


# ⛔ AN ATOM IS CITED BY IDENTITY, NEVER BY ITS PLACEHOLDER (review-parity N1).
# Every excerpt reads "[excerpt]" and two chips of one file read alike, so text
# cannot say WHICH atom a citation meant: after one delete, a text match lands
# on a look-alike. These attrs survive edits and saves:
#   documentExcerpt  excerptId            the immutable j2_note_excerpts row
#   attachmentChip   href                 the upload URL, minted with a uuid4
#   widgetEmbed      embedId              one per NODE, stamped at build
#                                         (widgetEmbedCore.js::newEmbedId)
#                    else widgetId|capturedAt  for an embed stored before
#                                         embedId existed
# ⛔ SURVIVING IS NOT NAMING ONE ATOM (rereview2 R2-1). Every chart of one /mtf
# or /compare insert is built in the same millisecond and shares its
# capturedAt -- which is why embedId exists; an embed without one still falls
# back to the shared stamp -- and a copy/paste duplicates any of these attrs,
# embedId included. So an identity is ISSUED only
# when exactly one atom of the note carries it at issue time (`atom_at`);
# otherwise the citation carries none and opens the note only. A copy made
# AFTER issue shares the identity: the client then finds it twice and opens
# the note only -- unless the cited position still holds one of the copies,
# or the original is deleted and only the copy is left.
# A type absent here, or an atom missing its attr, carries NO identity, and a
# citation to it opens the note without claiming a passage. The client's copy
# is askCitation.js::citationAtomIdentity, pinned through the fixtures.
_ATOM_IDENTITY = {
    "documentExcerpt": lambda a: _nonempty(a.get("excerptId")),
    "attachmentChip": lambda a: _nonempty(a.get("href")),
    "widgetEmbed": _widget_identity,
}

# Node types that are leaves in the schema (nodeSize 1, no content walked).
_LEAF_TYPES = frozenset({
    "attachmentChip", "documentExcerpt", "widgetEmbed", "videoTimestamp",
    "horizontalRule", "image", "hardBreak", "financialFact", "noteLink",
    # G-064: an Ask citation chip is an inline atom with no leafText, exactly
    # like noteLink -- one position, no text. Missing here, it was walked as a
    # container: two positions plus a block separator, shifting every later
    # citation position in the note (spec §7.1).
    "askCitation",
})

# Leaves that sit INSIDE a textblock. textBetween only ever emits a separator
# for a BLOCK leaf, so the walker must know which leaves are inline.
_INLINE_LEAF_TYPES = frozenset({"hardBreak", "noteLink", "askCitation", "videoTimestamp"})

# Textblocks (content is inline). An EMPTY one still emits a separator in
# textBetween, and an empty one carries no `content` to infer that from -- so
# the type must be known. Pinned against getSchema(buildExtensions()) by
# askCitation.schemaParity.test.js, which reads these literals.
_TEXTBLOCK_TYPES = frozenset({"paragraph", "heading", "codeBlock", "toggleSummary"})

# Every OTHER type with content -- lists, quotes, tables, toggles, callouts,
# askInsert, the doc itself. `isTextblock` is a TYPE property in ProseMirror,
# so a known container is never a textblock whatever its JSON holds: a
# malformed-but-loadable tableCell holding text directly gets no separator
# from textBetween, and must get none here. Only a genuinely UNKNOWN type is
# inferred from its content (`_is_textblock`). Pinned against the real schema
# by askCitation.schemaParity.test.js, which reads these literals.
_BLOCK_CONTAINER_TYPES = frozenset({
    "doc", "blockquote", "bulletList", "orderedList", "listItem", "taskList",
    "taskItem", "table", "tableRow", "tableHeader", "tableCell", "callout",
    "toggle", "toggleContent", "askInsert",
})

# G-064 (spec §7.2): a container whose text is an inserted Ask Notebook answer.
# Its runs are FLAGGED, never removed -- the text must stay ProseMirror's own.
ASK_INSERT_TYPE = "askInsert"

BLOCK_SEPARATOR = "\n"


def _u16(s: str) -> int:
    """`s.length` in JavaScript: UTF-16 code units, the unit ProseMirror
    positions count. `surrogatepass` so a lone surrogate from JSON counts as
    the one unit it is in the browser instead of raising."""
    return len(s.encode("utf-16-le", "surrogatepass")) // 2


def utf16_length(s: str) -> int:
    """`s.length` as the browser measures it -- the unit of a note location's
    `text_length` (ask_retrieval._note_blocks), which the client compares with
    the snippet it was sent (askCitation.js::isTruncatedSnippet)."""
    return _u16(s)


def _pm_at(s: dict[str, Any], flat_offset: int) -> int:
    """ProseMirror position of a flat (code-point) offset inside text span `s`."""
    return s["pm_start"] + _u16(s["text"][: flat_offset - s["flat_start"]])


def _flat_at(s: dict[str, Any], pm: int) -> int | None:
    """Flat (code-point) offset of ProseMirror position `pm` inside text span
    `s` -- or None when `pm` falls BETWEEN the two halves of an astral
    character, a position no code-point offset can name."""
    want = pm - s["pm_start"]
    units = 0
    for i, ch in enumerate(s["text"]):
        if units == want:
            return s["flat_start"] + i
        if units > want:
            return None
        units += 2 if ord(ch) > 0xFFFF else 1
    return s["flat_end"] if units == want else None


def _is_textblock(node: dict[str, Any]) -> bool:
    """R1's `node.isTextblock`, from JSON. A known type answers by TYPE, as
    ProseMirror does -- a textblock even when EMPTY (no `content` to look at),
    a container never, even holding inline content. Only a type in neither
    table is inferred: holding inline content, it is treated as a textblock,
    since in a valid doc only a textblock can hold inline nodes."""
    ntype = node.get("type")
    if ntype in _TEXTBLOCK_TYPES:
        return True
    if ntype in _BLOCK_CONTAINER_TYPES:
        return False
    children = node.get("content")
    return isinstance(children, list) and any(
        isinstance(c, dict) and (c.get("type") == "text" or c.get("type") in _INLINE_LEAF_TYPES)
        for c in children)


def flatten(doc: dict[str, Any] | None) -> dict[str, Any]:
    """Canonical citation text + ProseMirror span map for a TipTap doc.

    Returns ``{"text": str, "spans": [{"flat_start", "flat_end", "pm_start",
    "pm_end", "is_atom", "in_ask_insert", "text", "atom"}], "content_size": int}``
    (``atom`` is ``{"type", "id"}`` for an atom with an identity, else None).
    Spans are in document order and cover every addressable run of text; the
    block separators between them are part of ``text`` but belong to no span,
    which is exactly why the two coordinate systems need an explicit map
    rather than a constant offset. ``flat_*`` are code-point offsets into
    ``text``; ``pm_*`` and ``content_size`` are ProseMirror positions (UTF-16
    units); a span's own ``text`` is what maps one to the other inside it.
    """
    parts: list[str] = []
    spans: list[dict[str, Any]] = []
    state = {"flat": 0, "first": True, "ask_depth": 0}

    def separator() -> None:
        # textBetween: `if (first) first = false; else text += blockSeparator`
        if state["first"]:
            state["first"] = False
            return
        parts.append(BLOCK_SEPARATOR)
        state["flat"] += len(BLOCK_SEPARATOR)

    def emit(text: str, pm_start: int, pm_end: int, is_atom: bool,
             atom: dict[str, str] | None = None) -> None:
        if not text:
            return
        start = state["flat"]
        parts.append(text)
        state["flat"] += len(text)
        spans.append({
            "flat_start": start, "flat_end": state["flat"],
            "pm_start": pm_start, "pm_end": pm_end, "is_atom": is_atom,
            "in_ask_insert": state["ask_depth"] > 0, "text": text, "atom": atom,
        })

    def walk(node: Any, pos: int) -> int:
        """Returns the position immediately AFTER `node`."""
        if not isinstance(node, dict):
            return pos
        ntype = node.get("type")
        attrs = node.get("attrs")
        if not isinstance(attrs, dict):
            attrs = {}

        if ntype == "text":
            t = node.get("text")
            if isinstance(t, str) and t:
                # UTF-16 units, as ProseMirror sizes the node -- NOT len(t).
                end = pos + _u16(t)
                emit(t, pos, end, False)
                return end
            return pos

        if ntype in _LEAF_TYPES:
            maker = _ATOM_TEXT.get(ntype)
            leaf = maker(attrs) if maker is not None else ""
            if leaf and ntype not in _INLINE_LEAF_TYPES:
                separator()
            ident = _ATOM_IDENTITY.get(ntype, lambda a: None)(attrs)
            # A leaf occupies exactly ONE ProseMirror position no matter
            # how long its placeholder reads.
            emit(leaf, pos, pos + 1, True,
                 {"type": ntype, "id": ident} if ident else None)
            return pos + 1

        if _is_textblock(node):
            separator()
        # Container: 1 for the open token, content, 1 for the close token.
        inner = pos + 1
        children = node.get("content") or []
        is_ask = ntype == ASK_INSERT_TYPE
        if is_ask:
            state["ask_depth"] += 1
        if isinstance(children, list):
            for child in children:
                inner = walk(child, inner)
        if is_ask:
            state["ask_depth"] -= 1
        return inner + 1

    if not isinstance(doc, dict):
        return {"text": "", "spans": [], "content_size": 0}

    # The doc node itself is not addressable; its children start at 0. The
    # final position IS ProseMirror's `doc.content.size`.
    pos = 0
    for child in (doc.get("content") or []):
        pos = walk(child, pos)
    return {"text": "".join(parts), "spans": spans, "content_size": pos}


def member_text(flat: dict[str, Any], start: int = 0, end: int | None = None) -> str:
    """The canonical text in [start, end) with every run that sits inside an
    inserted Ask Notebook answer cut out (G-064, spec §7.2).

    For SNIPPETS only: the result is not position-bearing. Locations still come
    from `pm_range` over the untouched canonical text.
    """
    text = flat.get("text") or ""
    end = len(text) if end is None else end
    out: list[str] = []
    cur = start
    for s in flat.get("spans") or []:
        if not s.get("in_ask_insert"):
            continue
        a, b = max(s["flat_start"], start), min(s["flat_end"], end)
        if a >= b:
            continue
        if a > cur:
            out.append(text[cur:a])
        cur = max(cur, b)
    if cur < end:
        out.append(text[cur:end])
    return "".join(out)


class SpanIndex:
    """ONE flatten's spans, indexed so each lookup a citation needs is
    O(log n) or O(1) instead of a scan of every span.

    ⛔ WHY: Ask "This note" (`ask_retrieval._note_blocks`) asks four of these
    questions for EVERY block, so linear scans made a big note quadratic --
    3,000 paragraphs took ~3.7 s (final review M-1). Build one index per
    flatten and ask it; the module-level functions below build one per call,
    so there is exactly ONE implementation of each question.

    The answers equal the linear scans they replaced because `flatten` emits
    spans in document order, non-empty and non-overlapping: `flat_start` and
    `flat_end` both strictly increase, so a containing span is found by
    bisection, the spans overlapping a range are one contiguous run, and an
    atom's ProseMirror range is unique. The equality is proved against the
    previous implementation (parity-report "Final wave").
    """

    def __init__(self, spans: list[dict[str, Any]] | None):
        self.spans = spans or []

    @cached_property
    def _starts(self) -> list[int]:
        return [s["flat_start"] for s in self.spans]

    @cached_property
    def _ends(self) -> list[int]:
        return [s["flat_end"] for s in self.spans]

    @cached_property
    def _atoms(self) -> dict[tuple[Any, Any], dict[str, Any]]:
        out: dict[tuple[Any, Any], dict[str, Any]] = {}
        for s in self.spans:
            if s["is_atom"]:
                out.setdefault((s["pm_start"], s["pm_end"]), s)
        return out

    @cached_property
    def _carriers(self) -> Counter:
        return Counter((s["atom"]["type"], s["atom"]["id"])
                       for s in self.spans if s["is_atom"] and s.get("atom"))

    def in_ask_insert(self, flat_start: int, flat_end: int) -> bool:
        # The spans overlapping [flat_start, flat_end): those ending after its
        # start (a suffix) that also begin before its end (a prefix).
        lo = bisect_right(self._ends, flat_start)
        hi = bisect_left(self._starts, flat_end)
        return any(self.spans[k].get("in_ask_insert") for k in range(lo, hi))

    def pm_range(self, flat_start: int, flat_end: int) -> dict[str, int] | None:
        if flat_end <= flat_start:
            return None
        pm_from = pm_to = None
        i = bisect_right(self._starts, flat_start) - 1   # the span starting at or before it
        if i >= 0 and flat_start < self.spans[i]["flat_end"]:
            s = self.spans[i]
            pm_from = s["pm_start"] if s["is_atom"] else _pm_at(s, flat_start)
        j = bisect_left(self._starts, flat_end) - 1      # the span starting before it
        if j >= 0 and flat_end <= self.spans[j]["flat_end"]:
            s = self.spans[j]
            pm_to = s["pm_end"] if s["is_atom"] else _pm_at(s, flat_end)
        if pm_from is None or pm_to is None or pm_to <= pm_from:
            return None
        return {"from": pm_from, "to": pm_to}

    def atom_span_at(self, pm_from: Any, pm_to: Any) -> dict[str, Any] | None:
        try:
            return self._atoms.get((pm_from, pm_to))
        except TypeError:  # an unhashable position from a malformed location
            return next((s for s in self.spans if s["is_atom"]
                         and (s["pm_start"], s["pm_end"]) == (pm_from, pm_to)), None)

    def atom_at(self, rng: dict[str, int] | None) -> dict[str, str] | None:
        span = self.atom_span_at(rng.get("from"), rng.get("to")) if rng else None
        atom = span.get("atom") if span else None
        if not atom:
            return None
        return atom if self._carriers[(atom["type"], atom["id"])] == 1 else None

    def precise(self, rng: dict[str, int] | None) -> bool:
        if not rng:
            return False
        return self.atom_span_at(rng.get("from"), rng.get("to")) is None or self.atom_at(rng) is not None


def in_ask_insert(flat: dict[str, Any], flat_start: int, flat_end: int) -> bool:
    """True when any run overlapping [flat_start, flat_end) sits inside an
    inserted Ask Notebook answer (G-064, spec §7.2). Asking many times of one
    flatten? Use `SpanIndex(flat["spans"]).in_ask_insert`."""
    return SpanIndex(flat.get("spans")).in_ask_insert(flat_start, flat_end)


def pm_range(flat_start: int, flat_end: int, spans: list[dict[str, Any]]) -> dict[str, int] | None:
    """Map a half-open range in the canonical text to ProseMirror positions.

    Returns ``{"from", "to"}`` or None when the range addresses no text (for
    example a range that falls entirely inside a block separator). A range
    spanning several text nodes -- which is precisely the mark-boundary case
    Slice 0 proved unresolvable by string search -- maps cleanly, because
    ProseMirror positions do not know marks exist. `spans` is a `flatten`
    span list (document order). Asking many times? Use `SpanIndex.pm_range`.
    """
    return SpanIndex(spans).pm_range(flat_start, flat_end)


def atom_at(flat: dict[str, Any], rng: dict[str, int] | None) -> dict[str, str] | None:
    """The identity (``{"type", "id"}``) to ISSUE for the one atom a
    ProseMirror range covers exactly -- what a single-atom citation carries in
    its location. None for a text range, a range over several nodes, an atom
    with no identity (`_ATOM_IDENTITY`), and -- the R2-1 rule -- an atom whose
    identity any OTHER atom of the note also carries (the charts of one /mtf
    or /compare insert, a pasted copy). An identity that names two atoms would
    let the client select the wrong one, so such a citation opens the note
    only. Every atom counts, an inserted answer's included: the client's
    lookup walks the whole doc. Asking many times? Use `SpanIndex.atom_at`."""
    return SpanIndex(flat.get("spans")).atom_at(rng)


def precise_citation(flat: dict[str, Any], rng: dict[str, int] | None) -> bool:
    """Whether a citation to `rng` can ever open a precise passage: any text
    range can (it is verified by its text), a single atom only when an
    identity is issued for it (`atom_at`: it has one, and it is unique). The
    server's label must not promise a passage the client will refuse to open.
    Asking many times? Use `SpanIndex.precise`."""
    return SpanIndex(flat.get("spans")).precise(rng)


def _well_formed_atom(atom: Any) -> dict[str, str] | None:
    """A location's ``atom`` as ``{"type", "id"}``, or None unless it has the
    shape askCitation.js::resolveNoteCitation accepts: a string ``type`` and a
    non-empty string ``id`` (review M1: the mirror took any truthy value)."""
    if not isinstance(atom, dict) or not isinstance(atom.get("type"), str):
        return None
    ident = _nonempty(atom.get("id"))
    return {"type": atom["type"], "id": ident} if ident else None


def _atom_span_at(flat: dict[str, Any], pm_from: Any, pm_to: Any) -> dict[str, Any] | None:
    """The atom span whose ProseMirror range is exactly [pm_from, pm_to)."""
    return SpanIndex(flat.get("spans")).atom_span_at(pm_from, pm_to)


def fingerprint(doc: dict[str, Any] | None) -> str:
    """A cheap token that changes if and only if a stored ProseMirror position
    could have stopped meaning what it meant.

    Composition measured against the real prosemirror-model, not reasoned:

      text alone           too weak   -- wrapping a paragraph in a blockquote
                                        leaves the text identical and shifts
                                        every later position (size 13 -> 15)
      text + span list     too strict -- adding a bold mark SPLITS a text node
                                        ([1,8] -> [1,3,8]) without invalidating
                                        any position, so this would degrade a
                                        citation on every formatting edit
      text + content_size  exact      -- catches the blockquote wrap, ignores
                                        the mark split

    Both runtimes compute it cheaply: the backend from `flatten`, the frontend
    from `citationText(doc, 0, size)` and `doc.content.size` -- the very
    primitives the cross-runtime equivalence rail already pins together.

    This is the FAST PATH, not the guarantee. `verify` is the guarantee.
    """
    import hashlib
    flat = flatten(doc)
    digest = hashlib.sha256(flat["text"].encode("utf-8")).hexdigest()[:16]
    return f"{digest}:{flat['content_size']}"


def verify(doc: dict[str, Any] | None, pm_from: int, pm_to: int, snippet: str) -> bool:
    """Does `snippet` still live at exactly [pm_from, pm_to) in this doc?

    THE ACTUAL GUARANTEE. A fingerprint can in principle be fooled (unwrap one
    blockquote, wrap another: net size unchanged, text unchanged, positions
    between them shifted). Rather than chase ever-more-precise fingerprints,
    the navigator re-reads the text at the range it is about to jump to and
    refuses if it is not the cited passage. Complete regardless of how the
    fingerprint was computed.
    """
    if not snippet or pm_to <= pm_from:
        return False
    flat = flatten(doc)
    lo = hi = None
    for s in flat["spans"]:
        if s["is_atom"]:
            continue
        if s["pm_start"] <= pm_from < s["pm_end"]:
            lo = _flat_at(s, pm_from)
        if s["pm_start"] < pm_to <= s["pm_end"]:
            hi = _flat_at(s, pm_to)
    if lo is None or hi is None or hi <= lo:
        return False
    return flat["text"][lo:hi] == snippet


def locate(doc: dict[str, Any] | None, needle: str) -> list[dict[str, Any]]:
    """Every occurrence of `needle` in a note's canonical text, as ProseMirror
    ranges. Ambiguity is REPORTED, never resolved by picking the first hit --
    Slice 0 recorded that silent first-match behaviour as a defect.
    """
    if not needle:
        return []
    flat = flatten(doc)
    text, index = flat["text"], SpanIndex(flat["spans"])
    out: list[dict[str, Any]] = []
    start = text.find(needle)
    while start != -1:
        rng = index.pm_range(start, start + len(needle))
        if rng is not None:
            out.append({"flat_start": start, "flat_end": start + len(needle), **rng})
        start = text.find(needle, start + 1)
    return out


# ── Citation validity ────────────────────────────────────────────────────────
# Internal names. Member-facing copy stays simple ("open the note").
VALID_EXACT = "valid_exact"            # fingerprint matched AND text verified
RERESOLVED_EXACT = "reresolved_exact"  # note changed; re-found unambiguously
VALID_NOTE_ONLY = "valid_note_only"    # can open the note, not the passage
DEGRADED = "degraded"                  # ambiguous or gone; no passage claim

# The only states in which a caller may claim an exact passage jump. Anything
# else opens the note WITHOUT pretending precise navigation succeeded.
PRECISE_STATES = frozenset({VALID_EXACT, RERESOLVED_EXACT})


def resolve_note_citation(doc, pm_from, pm_to, snippet, expected_fingerprint,
                          prefix: str = "", suffix: str = "", atom=None):
    """Decide where a NOTE citation may navigate, given the note's CURRENT doc.

    The requirement is one-directional: a failed precise citation is fine, a
    confident jump to the wrong passage is not. Every path that cannot PROVE
    it is looking at the cited passage returns a non-precise state.

        0. an ATOM citation (`atom` = the location's ``{type, id}``) resolves
           by IDENTITY only, never by its placeholder text:
           - the atom at [from,to) carries that identity -> VALID_EXACT
           - exactly one atom elsewhere carries it       -> RERESOLVED_EXACT
           - none, or several                            -> VALID_NOTE_ONLY
        1. fingerprint matches AND the text at [from,to) is still the snippet
           -> VALID_EXACT, original positions
        2. otherwise re-resolve the snippet against the CURRENT canonical text
           - exactly one occurrence               -> RERESOLVED_EXACT
           - several, but quote context picks one -> RERESOLVED_EXACT
           - several and context cannot decide    -> VALID_NOTE_ONLY (never the
             first occurrence: Slice 0 recorded that silent choice as a defect)
           - none                                 -> DEGRADED
           and a re-found range that is ONE ATOM is never precise: without an
           identity, its placeholder cannot say which atom it was.

    Mirrored by askCitation.js::resolveNoteCitation, which is what navigates.
    Step 0 takes the same shape the client does -- a dict with a string
    ``type`` and a non-empty string ``id``; anything else is no identity and
    the citation is resolved by text, as the client resolves it.
    """
    flat = flatten(doc)
    want = _well_formed_atom(atom)
    if want:
        found = [s for s in flat["spans"] if s["is_atom"] and s.get("atom") == want]
        here = _atom_span_at(flat, pm_from, pm_to)
        if here is not None and here.get("atom") == want:
            return {"state": VALID_EXACT, "from": pm_from, "to": pm_to}
        if len(found) == 1:
            return {"state": RERESOLVED_EXACT, "from": found[0]["pm_start"], "to": found[0]["pm_end"]}
        return {"state": VALID_NOTE_ONLY, "from": None, "to": None,
                "reason": ("several atoms carry this identity" if found
                           else "the cited atom is no longer in this note")}

    if expected_fingerprint and fingerprint(doc) == expected_fingerprint:
        if verify(doc, pm_from, pm_to, snippet):
            return {"state": VALID_EXACT, "from": pm_from, "to": pm_to}
        # Fingerprint agreed but the text did not. Trust the text.

    no_identity = {"state": VALID_NOTE_ONLY, "from": None, "to": None,
                   "reason": "an atom is cited by identity, never by its placeholder"}
    hits = locate(doc, snippet)
    if len(hits) == 1:
        if _atom_span_at(flat, hits[0]["from"], hits[0]["to"]) is not None:
            return no_identity
        return {"state": RERESOLVED_EXACT, "from": hits[0]["from"], "to": hits[0]["to"]}
    if len(hits) > 1 and (prefix or suffix):
        ctx = locate(doc, f"{prefix}{snippet}{suffix}")
        if len(ctx) == 1:
            only = ctx[0]
            inner = pm_range(only["flat_start"] + len(prefix),
                             only["flat_end"] - len(suffix),
                             flat["spans"])
            if inner:
                if _atom_span_at(flat, inner["from"], inner["to"]) is not None:
                    return no_identity
                return {"state": RERESOLVED_EXACT, **inner}
    if hits:
        return {"state": VALID_NOTE_ONLY, "from": None, "to": None,
                "reason": f"{len(hits)} occurrences; cannot disambiguate"}
    return {"state": DEGRADED, "from": None, "to": None,
            "reason": "cited passage is no longer in this note"}
