"""
Apply cancel-class patches to FlowDB — tag matching rows as Color='ARB'.

Companion module to backfill_from_patches.py but with one key difference:
this is DISPOSITIVE. It overwrites Color to 'ARB' regardless of the row's
current Color value, because the cancel pattern wins over any prior
WHITE/YELLOW/MAGENTA classification.

Patches file format (generated by build_cancel_patches.py):
    {
      "ROOT|CP|Strike|Exp|Time": {"color": "ARB"},
      ...
    }

Matching strategy (matches backfill_from_patches.py pattern):
  - Symbol == ROOT
  - CallPut == CP
  - Strike == Strike (after numeric normalization)
  - ExpirationDate == Exp
  - CreatedTime within ±60s of patch Time (allows for worker write timing jitter)

For each matched row, set Color = 'ARB'.
Idempotent — rows already ARB are skipped (counted separately).

Endpoint: POST /api/admin/massive/apply-cancel-patches
  ?patches_file=patches-6-26-cancels.json&target_date=6/26/2026
"""
import sqlite3
import json
import os
import logging
from collections import defaultdict
import datetime

logger = logging.getLogger(__name__)
DB_PATH = os.environ.get("FLOW_DB_PATH", "/data/flow.db")

WINDOW_SECONDS = 60


def _norm_strike(s) -> str:
    """Normalize strike to canonical string for grouping ('300' vs '300.0' vs '300.00')."""
    try:
        f = float(s)
        if f == int(f):
            return str(int(f))
        return ("%g" % f)
    except (ValueError, TypeError):
        return str(s) if s is not None else ""


def _parse_time(t: str) -> int:
    """Parse 'H:MM:SS AM/PM' -> seconds since midnight. Returns -1 on failure."""
    if not t:
        return -1
    try:
        parts = t.strip().split(":")
        h = int(parts[0])
        m = int(parts[1])
        sec_part = parts[2]
        # Split out AM/PM
        is_pm = sec_part.upper().endswith("PM")
        is_am = sec_part.upper().endswith("AM")
        sec = int(sec_part[:-2].strip()) if (is_pm or is_am) else int(sec_part)
        if is_pm and h != 12:
            h += 12
        elif is_am and h == 12:
            h = 0
        return h * 3600 + m * 60 + sec
    except (ValueError, IndexError):
        return -1


def run_apply_cancel_patches(patches_path: str, target_date: str) -> dict:
    """Apply Color='ARB' patches to matching FlowDB rows for target_date."""
    if not target_date:
        raise ValueError("target_date is required")
    if not os.path.exists(patches_path):
        raise FileNotFoundError(f"patches file not found: {patches_path}")

    with open(patches_path) as f:
        patches = json.load(f)

    stats = {
        "target_date": target_date,
        "patches_loaded": len(patches),
        "production_rows_scanned": 0,
        "rows_matched_and_tagged": 0,
        "rows_already_arb": 0,
        "rows_overwritten_from_classified": 0,  # had YELLOW/MAGENTA prior
        "patches_with_no_match": 0,
    }

    # Build a lookup index of patches keyed by (Symbol, CP, NormalizedStrike, Exp).
    # The Time component is used as a window check per match.
    patches_by_contract = defaultdict(list)  # key -> [(time_str, time_seconds, color)]
    for key, val in patches.items():
        try:
            sym, cp, strike, exp, time_str = key.split("|")
        except ValueError:
            continue
        norm_key = (sym, cp, _norm_strike(strike), exp)
        patches_by_contract[norm_key].append({
            "time_str": time_str,
            "time_sec": _parse_time(time_str),
            "color": (val.get("color") or "ARB").upper(),
        })

    conn = sqlite3.connect(DB_PATH, timeout=30)
    conn.execute("PRAGMA journal_mode=WAL")
    try:
        cur = conn.cursor()

        # Pull all rows for target_date
        cur.execute("""
            SELECT id, Symbol, CallPut, Strike, ExpirationDate, CreatedTime, Color
            FROM flow
            WHERE CreatedDate = ?
        """, (target_date,))
        rows = cur.fetchall()
        stats["production_rows_scanned"] = len(rows)

        ids_to_tag = []
        matched_keys = set()
        for r in rows:
            rid, sym, cp, strike, exp, ct, color = r
            norm_key = (sym, cp, _norm_strike(strike), exp)
            candidates = patches_by_contract.get(norm_key)
            if not candidates:
                continue
            row_sec = _parse_time(ct or "")
            if row_sec < 0:
                continue
            # Find a patch within WINDOW_SECONDS
            for p in candidates:
                if p["time_sec"] < 0:
                    continue
                if abs(p["time_sec"] - row_sec) <= WINDOW_SECONDS:
                    cur_color = (color or "").upper().strip()
                    if cur_color == "ARB":
                        stats["rows_already_arb"] += 1
                    else:
                        ids_to_tag.append(rid)
                        if cur_color in ("YELLOW", "MAGENTA"):
                            stats["rows_overwritten_from_classified"] += 1
                    matched_keys.add(norm_key)
                    break  # one patch hit per row

        if ids_to_tag:
            cur.executemany(
                "UPDATE flow SET Color = 'ARB' WHERE id = ?",
                [(rid,) for rid in ids_to_tag],
            )
            stats["rows_matched_and_tagged"] = len(ids_to_tag)

        stats["patches_with_no_match"] = len(patches_by_contract) - len(matched_keys)

        conn.commit()
        logger.info(f"[apply_cancel_patches] done: {stats}")
        return stats

    except Exception:
        conn.rollback()
        logger.exception("[apply_cancel_patches] failed")
        raise
    finally:
        conn.close()
