// ⛔⛔ A CHANGE TO `PREVIEW_MODES` IS A CHANGE TO WHAT MEMBERS CAN REACH, AND IT MUST ARRIVE WITH A
// REGENERATED SURFACE MATRIX IN THE SAME COMMIT.
//
// ── THE FINDING THIS RAIL EXISTS FOR ───────────────────────────────────────────────────────────
// Between Increment 2 and Increment 7 exactly THREE actions were added to the registry
// (`chart.draw`, `journal.planTrade`, `notebook.voiceNote`). In the same window, four modes —
// `chart`, `catalysts`, `notebook`, `calendar` — left `PREVIEW_MODES`, and that carried
// **nineteen already-declared actions** onto members' glass. Nobody typed them, nobody reviewed
// them as new, and a glass checklist written from memory would have covered the three and missed
// the nineteen.
//
// ⭐ **The exposure change is the DELETION of a mode id from a Set.** One line, no new action, no
// new handler — and it is the single highest-leverage edit in the feature. This rail makes that
// edit impossible to make quietly: the matrix is regenerated, or the suite goes red.
//
// ── WHAT IT ASSERTS ────────────────────────────────────────────────────────────────────────────
// The two GENERATED artifacts under `docs/plans/joystick/` are byte-identical to what the
// generator produces from the registry as it stands right now:
//
//   * `surface-matrix.md`         — everything from its `<!-- GENERATED … -->` marker down
//   * `glass-acceptance-steps.md` — the whole file
//
// ⛔ NOT "the matrix mentions every mode". A containment check passes over a stale table that
// happens to name the right modes, which is exactly the failure mode here: the modes were all
// present in the registry the whole time — what changed was whether the projection hid them.
// Equality is the only comparison that can see a projection flip.
//
// ⛔ COMPARE NORMALISED LINE ENDINGS. The generator writes LF; git checks these files out as CRLF
// on Windows (`core.autocrlf`), so a raw comparison fails on every line of a perfectly current
// file and the first person to see it "fixes" the rail rather than the matrix.
import { describe, it, expect } from 'vitest'
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const REPO = path.resolve(HERE, '..', '..', '..')
const TOOL = path.join(REPO, 'tools', 'hub_surface_matrix.mjs')
const DOCS = path.join(REPO, 'docs', 'plans', 'joystick')
const MARKER = '<!-- GENERATED by tools/hub_surface_matrix.mjs'

/** ⛔ `process.execPath`, never the string "node". Resolving an executable off PATH is how
 *  `scripts/deploy_watch.py` logged forty FileNotFoundErrors and still exited 0 (CLAUDE.md rule
 *  14); the running interpreter is already the one we want. */
const generate = (args) =>
  execFileSync(process.execPath, [TOOL, ...args], { cwd: REPO, encoding: 'utf8', maxBuffer: 16e6 })

const lf = (s) => s.replace(/\r\n/g, '\n').trimEnd()
const committed = (name) => lf(readFileSync(path.join(DOCS, name), 'utf8'))

describe('the generated joystick artifacts are current', () => {
  // ── THE NON-VACUITY CONTROL, FIRST. Rule 14: an empty result satisfies almost any assertion, and
  // this generator shells out to `git show <baseline>` for the Increment-2 diff. A git that cannot
  // resolve the baseline, or a tool that dies at argument parsing, returns an empty string — and
  // `''.includes(…)` is false, but `expect('').toBe('')` would be GREEN against a stale file if the
  // committed side were also read wrong. So: prove the generator produced real content before any
  // equality means anything.
  it('the generator produces a real table before anything is compared', () => {
    const out = lf(generate([]))
    expect(out.length, 'the generator returned nothing — a failed invocation, not a clean tree').toBeGreaterThan(2000)
    expect(out).toContain(MARKER)
    // Named members, not a count: a count drifts, a name fails loudly. One mode that has always
    // been live, one that left PREVIEW_MODES, and one action that is genuinely new.
    expect(out).toContain('| **scan** |')
    expect(out).toContain('| **notebook** |')
    expect(out).toContain('`notebook.voiceNote`')
  })

  it('the Since-Inc-2 column DISCRIMINATES — it is computed, not decoration', () => {
    // ⭐ THE CONTROL THAT MAKES THE EQUALITY TESTS MEAN SOMETHING. If that column stopped being
    // computed — a hard-coded string, a baseline that silently failed to resolve — the documents
    // would still match the generator and every comparison below would pass for ever while
    // measuring nothing. So: the column must produce all THREE of its outcomes on this tree.
    //
    // ⛔ NO COUNT IS ASSERTED. "Exactly four modes left preview" is a hand-typed number beside the
    // thing it describes, which is the drift this whole rail exists to stop; and the number moves
    // the day a fifth mode flips, turning a correct change into a red rail.
    //
    // ⚰️ ITS FIRST VERSION COMPARED THE WORKTREE AGAINST `--baseline HEAD` and expected NO flips.
    // That is red for any uncommitted registry edit — including a legitimate one that HAS been
    // regenerated — so it would have gone off on the honest workflow and been muted within a week.
    const out = lf(generate([]))
    expect(out, 'no mode reads as having left PREVIEW_MODES').toContain('**LEFT PREVIEW**')
    expect(out, 'no action reads as new since Increment 2').toContain('**NEW action**')
    expect(out, 'no action reads as unchanged — the column is emitting a constant')
      .toMatch(/\| `wire\.flag` [^\n]*\|\s*\|/)
  })

  it('surface-matrix.md matches the registry as it stands', () => {
    const doc = committed('surface-matrix.md')
    const idx = doc.indexOf(MARKER)
    expect(idx, 'surface-matrix.md lost its GENERATED marker').toBeGreaterThan(-1)
    expect(
      doc.slice(idx),
      'surface-matrix.md is STALE. If you changed PREVIEW_MODES, the registry, or a section '
        + 'controller, regenerate it IN THIS COMMIT:\n'
        + '    node tools/hub_surface_matrix.mjs        (replace everything from the GENERATED marker down)',
    ).toBe(lf(generate([])))
  })

  it('glass-acceptance-steps.md matches the registry as it stands', () => {
    expect(
      committed('glass-acceptance-steps.md'),
      'glass-acceptance-steps.md is STALE — the glass sheet no longer describes the product. '
        + 'Regenerate it IN THIS COMMIT:\n'
        + '    node tools/hub_surface_matrix.mjs --glass > docs/plans/joystick/glass-acceptance-steps.md',
    ).toBe(lf(generate(['--glass'])))
  })

  it('the generator passes its own self-check', () => {
    // Its nine cases include the two false write attributions it made about itself while being
    // written. A deriver whose self-check is red cannot be trusted to say the docs are current.
    const out = generate(['--self-check'])
    expect(out).toContain('self-check OK')
  })
})

// ── MUTATION PROOF, PERFORMED 2026-09-12 ───────────────────────────────────────────────────────
// ⛔ Not a claim — a run, and the numbers are what it actually printed. `'flow'` was deleted from
// `PREVIEW_MODES` in `registry.js` and the suite re-run WITHOUT regenerating either document:
//
//     Tests  3 failed | 2 passed (5)
//
// Both equality tests went RED, each naming its own file and the command to regenerate it, and the
// diff they printed showed the new `GS-flow-*` rows the glass sheet had not grown. ⭐ The two that
// stayed GREEN are what prove the red came from the FLIP and not from the rail falling over: the
// non-vacuity test still saw a real table, and the generator still passed its own self-check. A
// mutation run where everything goes red proves only that something broke.
//
// The third red was the old baseline control, which compared the worktree against `--baseline HEAD`
// — correct on that run, wrong as a design, because it is also red for a legitimate registry edit
// that HAS been regenerated but not yet committed. It was replaced with the discriminator test
// above, which asserts the column produces all three of its outcomes and asserts no count.
//
// The edit was reverted BY EDITING IT BACK, never `git checkout`
// (`feedback_mutation_check_never_git_checkout`), and `git diff --stat` on `registry.js` came back
// empty. Redo exactly this, not a variation of it, if the rail is ever rewritten.
